### ISSUE TITLE
Can't even fire 'middleman init' command. I get  this error: "`template': uninitialized constant Middleman::VERSION (NameError)" .

### ISSUE THREAD

**Issue by nainira** [middleman/middleman#1247]
When I type 'middle init', I get this weird error that I assume no one gets.
I though it might be ruby version issue, so I tried 1.9.3, 2.0.0 and 2.1.1.
The error messages were the same.

```
$ middleman init project_name
create  Gemfile
(erb):5:in `template': uninitialized constant Middleman::VERSION (NameError)
    from /Users/nainira/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/erb.rb:849:in `eval'
    from /Users/nainira/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/erb.rb:849:in `result'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/middleman-core-3.3.0/lib/middleman-core/templates.rb:66:in `generate_bundler!'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/middleman-core-3.3.0/lib/middleman-core/cli/init.rb:53:in `init'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/middleman-core-3.3.0/lib/middleman-core/cli.rb:77:in `method_missing'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/middleman-core-3.3.0/lib/middleman-core/cli.rb:22:in `start'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/gems/middleman-core-3.3.0/bin/middleman:18:in `<top (required)>'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/bin/middleman:23:in `load'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/bin/middleman:23:in `<main>'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/bin/ruby_executable_hooks:15:in `eval'
    from /Users/nainira/.rvm/gems/ruby-2.0.0-p451@middleman/bin/ruby_executable_hooks:15:in `<main>'

```

I usually create a new gemset by making ' .ruby-version' file in new folder for a fresh start as below. 

.ruby-version 

```
2.0.0-p451@middleman
```

my OSX vesion
`
10.9.2
`

$ gem list

```

*** LOCAL GEMS ***

activesupport (4.0.4)
bigdecimal (1.2.0)
bundler (1.5.3)
bundler-unload (1.0.2)
chunky_png (1.3.0)
coffee-script (2.2.0)
coffee-script-source (1.7.0)
compass (1.0.0.alpha.19)
compass-core (1.0.0.alpha.19)
compass-import-once (1.0.4)
erubis (2.7.0)
execjs (2.0.2)
executable-hooks (1.3.1)
ffi (1.9.3)
gem-wrappers (1.2.4)
haml (4.1.0.beta.1)
hike (1.2.3)
hooks (0.4.0)
i18n (0.6.9)
io-console (0.4.2)
json (1.8.1, 1.7.7)
kramdown (1.3.3)
listen (1.1.6)
middleman (3.3.0)
middleman-core (3.3.0)
middleman-sprockets (3.3.2)
minitest (4.3.2)
multi_json (1.9.2)
padrino-helpers (0.12.1)
padrino-support (0.12.1)
psych (2.0.0)
rack (1.5.2)
rack-test (0.6.2)
rake (0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rb-kqueue (0.2.2)
rdoc (4.0.0)
rubygems-bundler (1.4.2)
rvm (1.11.3.9)
sass (3.3.4)
sprockets (2.12.0)
sprockets-helpers (1.1.0)
sprockets-sass (1.0.3)
test-unit (2.0.0.0)
thor (0.19.1)
thread_safe (0.3.2)
tilt (1.4.1)
tzinfo (0.3.39)
uber (0.0.4)
uglifier (2.5.0)
```

This is how I did

```
$ mkdir project & cd project
$ cat > .ruby-version
2.1.1@middleman
^C
$ cd ..; cd project
$ gem install middleman
$ middleman init .
```

Did I anything wrong?

**Comment by andreamoro** [comment]
Worth bringing to the attention that M4 still suffers of this issue and the workaround above is the only one to move ahead to initialise a new environment.
