### ISSUE TITLE
After bundle update error on maiddleman server about sprockets 

### ISSUE THREAD

**Issue by piermariacosina** [middleman/middleman#1429]
this is the error that appear 

It is a project that I haven't touch for a long time, I've updated with bundler update and this is the error I get. any idea?
````
 (Sprockets::ArgumentError)m/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/asset.rb:36:in `initialize': Asset logical path has no extension: certificates/high/Icon
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/base.rb:380:in `new'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/base.rb:380:in `build_asset'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/environment.rb:75:in `find_asset'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/sprockets-2.12.3/lib/sprockets/base.rb:295:in `[]'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-sprockets-3.4.1/lib/middleman-sprockets/asset.rb:12:in `initialize'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-sprockets-3.4.1/lib/middleman-sprockets/extension.rb:99:in `new'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-sprockets-3.4.1/lib/middleman-sprockets/extension.rb:99:in `block in manipulate_resource_list'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-sprockets-3.4.1/lib/middleman-sprockets/extension.rb:98:in `each'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-sprockets-3.4.1/lib/middleman-sprockets/extension.rb:98:in `manipulate_resource_list'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:215:in `block (2 levels) in ensure_resource_list_updated!'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:214:in `each'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:214:in `reduce'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:214:in `block in ensure_resource_list_updated!'
	from /Users/piermaria-cosina/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:208:in `ensure_resource_list_updated!'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/extensions/on_disk.rb:31:in `block in initialize'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/uber-0.0.13/lib/uber/options.rb:80:in `proc!'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/uber-0.0.13/lib/uber/options.rb:69:in `evaluate_for'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/request.rb:50:in `inst'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/preview_server.rb:103:in `new_app'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/preview_server.rb:21:in `start'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/cli/server.rb:78:in `server'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:20:in `start'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/gems/middleman-core-3.3.7/bin/middleman:18:in `<top (required)>'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/bin/middleman:23:in `load'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/bin/middleman:23:in `<main>'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/bin/ruby_executable_hooks:15:in `eval'
	from /Users/piermaria-cosina/.rvm/gems/ruby-2.2.0@middleman/bin/ruby_executable_hooks:15:in `<main>'
````

this is the config.rb
````
source 'https://rubygems.org'

gem "middleman-livereload", :platforms => [:ruby]

gem "middleman"
gem "middleman-favicon-maker"
gem "middleman-minify-html"
gem "therubyracer", :platforms => [:ruby]
gem 'oj'
gem "wdm", :platforms => [:mswin, :mingw]

gem "susy"
gem "compass-h5bp"
gem "builder"
gem "bootstrap-sass", :require => false
gem 'oily_png'
gem 'mini_magick'




gem 'font-awesome-middleman'

gem "middleman-imageoptim"
````
seams a problem already existing in sprocket
https://github.com/sstephenson/sprockets/issues/347

**Comment by tdreyno** [comment]
It does indeed look like an upstream Sprockets issue. Which gem is including this file?

**Comment by piermariacosina** [comment]
sorry I don't get the question, which file or list do you need, the bundler list? i can give you access to the whole project https://github.com/Belafonte-boat/millbo-website this is the repo

**Comment by tdreyno** [comment]
I'm asking where `certificates/high/Icon` is being referenced. Is it in your code or deep in one of those dependencies.

**Comment by piermariacosina** [comment]
Yes you are right, I've found that in some folder mac osx has generate a file called Icon deleted that has fixed the issue http://superuser.com/questions/298785/icon-file-on-os-x-desktop it should be ignored by sprockets, I wonder why mine was visible...
