### ISSUE TITLE
Error when including a .builder file

### ISSUE THREAD

**Issue by dwcramer** [middleman/middleman#1431]
When I include a `feed.xml.builder` file in my blog, I see the following error with middleman 4 alpha 6 middleman (4.0.0.alpha.6) and middleman-blog (3.6.0.beta.2) and ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]:
```
== The Middleman is loading
/Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:144:in `require': cannot load such file -- builder (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:144:in `require_template_library'
	from /Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt/builder.rb:14:in `initialize_engine'
	from /Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:56:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt.rb:98:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt.rb:98:in `block in []'
	from /Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt.rb:96:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt.rb:96:in `[]'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:251:in `strip_extensions'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:242:in `add_file_to_cache'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:218:in `block in update'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:217:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:217:in `update'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:162:in `poll_once!'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources.rb:212:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources.rb:212:in `find_new_files!'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/core_extensions/file_watcher.rb:48:in `before_configuration'
	from /Library/Ruby/Gems/2.0.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
	from /Library/Ruby/Gems/2.0.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `proc!'
	from /Library/Ruby/Gems/2.0.0/gems/uber-0.0.13/lib/uber/options.rb:69:in `evaluate_for'
	from /Library/Ruby/Gems/2.0.0/gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/application.rb:237:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/preview_server.rb:100:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/preview_server.rb:100:in `new_app'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/preview_server.rb:24:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-cli-4.0.0.alpha.6/lib/middleman-cli/server.rb:69:in `server'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-cli-4.0.0.alpha.6/bin/middleman:23:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/bin/middleman:23:in `load'
	from /Library/Ruby/Gems/2.0.0/bin/middleman:23:in `<main>'
```
The contents of the feed.xml.builder file follows:
```
xml.instruct!
xml.feed "xmlns" => "http://www.w3.org/2005/Atom" do
  site_url = "http://docs.xbudev.org/blog/"
  xml.title "Product Blog"
  #xml.subtitle "Blog subtitle"
  xml.id URI.join(site_url, blog.options.prefix.to_s)
  xml.link "href" => URI.join(site_url, blog.options.prefix.to_s)
  xml.link "href" => URI.join(site_url, current_page.path), "rel" => "self"
  xml.updated(blog.articles.first.date.to_time.iso8601) unless blog.articles.empty?
  xml.author { xml.name "Foo Team" }

  blog.articles[0..5000].each do |article|
    xml.entry do
      xml.title article.title
      xml.link "rel" => "alternate", "href" => URI.join(site_url, article.url)
      xml.id URI.join(site_url, article.url)
      xml.published article.date.to_time.iso8601
      xml.updated File.mtime(article.source_file).iso8601
      xml.author article.data.author
      #xml.summary article.summary, "type" => "html"
      xml.content article.body, "type" => "html"
    end
  end
end
```

**Comment by tdreyno** [comment]
Is `builder` in your Gemfile?

**Comment by dwcramer** [comment]
It was not and adding `gem "builder"` fixes the problem. I guess it was being pulled in as a dependency of something else before. Thanks!

**Comment by tdreyno** [comment]
I think adding the `.builder` automatically tries to load it.

**Comment by dwcramer** [comment]
Yeah, with middleman 3.x, just adding the file worked, but when I tested the site with 4 alpha 6, I got the error.

**Comment by tdreyno** [comment]
`middleman-blog` bundles it. So if that wasn't working right, then it would be "missing"
