### ISSUE TITLE
`middleman build` causes source file to load twice, crashing Middleman

### ISSUE THREAD

**Issue by jimmycuadra** [middleman/middleman#1450]
I'm trying to build a Middleman site inside a Docker container, and when I run `bundle exec middleman build`, I get:

```
`define_setting': Setting source already defined (RuntimeError)
```

It seems `middleman-core/application` is somehow getting loaded more than once, causing the first `define_setting` call to raise an exception on the second load. I can confirm that the file is loading twice by adding a `puts` statement to the top of `middleman-core/application`'s source file.

This issue does not happen on my laptop (OS X 10.10.2, Ruby 2.2.0).

I've tried it in Docker containers based on Ubuntu 14.04 with Ruby 2.2.0 installed via Brightbox's Ubuntu package, as well as my own Docker image for Ruby compiled from source, which is based on Debian 7.7.

Please see [this Dockerfile](https://gist.github.com/jimmycuadra/11b49fe1d05ddc9be473), which reproduces the error when built with `docker build`. For reference, the Gist also includes the output of `docker build`.

**Comment by r007** [comment]
I have the same issue.

**Comment by tdreyno** [comment]
Can you give some direction to how I can debug this VM? Sorry, never used Docker.

**Comment by jimmycuadra** [comment]
1) Install Docker for your platform: https://docs.docker.com/installation/
2) Download the "Dockerfile" in the linked Gist and save it as "Dockerfile" in an empty directory.
3) `cd` into that directory and run `docker build .` which will attempt to build a Docker image from the instructions in the Dockerfile. Towards the end of the process, it will fail and you'll see the error in question.
4) To get an interactive shell in the environment, run `docker run -it $IMAGE_ID /bin/bash` where `$IMAGE_ID` is the unique ID of the image that was created. You can find this ID by running `docker images` or looking in the output of the previously run `docker build`. Each instruction in the Dockerfile creates a new layer, and each layer is a new image with a unique ID. The ID you want to use is the last one successfully created, which consists of everything in the instructions other than the last one, which is the one that fails.

**Comment by tdreyno** [comment]
Thank you. Debugging now. Seems like something very docker specific, but it should be easy to work around.

**Comment by mqbeers** [comment]
I have exactly the same issue on Ubuntu 14.04 with a clean install of middleman 3.3.8 on ruby 2.1.5 using RVM. I am not running Docker, and the same code base works fine on OS X (with RVM) and Windows 7.

**Comment by tdreyno** [comment]
Seems like an issue with extensions requiring `middleman-core` with different paths, maybe. Weird that it just showed up. Maybe it's a recent Ruby 2.x change

**Comment by r007** [comment]
Like I said, I have the same problem, but with bundler.

```
$ uname -a
Linux ubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:08:14 UTC 2014 i686 i686 i686 GNU/Linux
$ ruby -v 
ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]
```
This is my fresh installation of middleman.
```
$ middleman build
/var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core/configuration.rb:159:in `define_setting': Setting source already defined (RuntimeError)
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core/application.rb:72:in `<class:Application>'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core/application.rb:28:in `<module:Middleman>'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core/application.rb:27:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core.rb:16:in `require'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core.rb:16:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core/cli/build.rb:50:in `require'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core/cli/build.rb:50:in `build'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core/cli.rb:72:in `method_missing'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/lib/middleman-core/cli.rb:20:in `start'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/bin/middleman:18:in `<top (required)>'
	from /usr/local/bin/middleman:23:in `load'
	from /usr/local/bin/middleman:23:in `<main>'
```

**Comment by tdreyno** [comment]
Can you all point your Gemfile at github and let me know if this is fixed.

```
gem "middleman", github: "middleman/middleman", branch: "v3-stable"
```

**Comment by r007** [comment]
```console
$ middleman build
/home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/file_watcher.rb:123:in `initialize': can't convert nil into String (TypeError)
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/file_watcher.rb:123:in `Pathname'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/file_watcher.rb:123:in `block in reload_path'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/file_watcher.rb:122:in `chdir'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/file_watcher.rb:122:in `reload_path'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/file_watcher.rb:36:in `block in registered'
	from /var/lib/gems/1.9.1/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
	from /var/lib/gems/1.9.1/gems/uber-0.0.13/lib/uber/options.rb:80:in `proc!'
	from /var/lib/gems/1.9.1/gems/uber-0.0.13/lib/uber/options.rb:69:in `evaluate_for'
	from /var/lib/gems/1.9.1/gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
	from /var/lib/gems/1.9.1/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
	from /var/lib/gems/1.9.1/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
	from /var/lib/gems/1.9.1/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
	from /var/lib/gems/1.9.1/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
	from /var/lib/gems/1.9.1/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
	from /var/lib/gems/1.9.1/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
	from /var/lib/gems/1.9.1/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/extensions.rb:156:in `initialize'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/data.rb:33:in `initialize'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/request.rb:52:in `new'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/core_extensions/request.rb:52:in `inst'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/cli/build.rb:95:in `shared_instance'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/cli/build.rb:62:in `build'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ubuntu/.bundler/ruby/1.9.1/middleman-fd3d9b206fe6/middleman-core/lib/middleman-core/cli.rb:20:in `start'
	from /var/lib/gems/1.9.1/gems/middleman-core-3.3.8/bin/middleman:18:in `<top (required)>'
	from /usr/local/bin/middleman:23:in `load'
	from /usr/local/bin/middleman:23:in `<main>'
```

**Comment by jimmycuadra** [comment]
I get the same result as @r007.

**Comment by tdreyno** [comment]
Okay, please `bundle update` to grab the latest commit and re-test. Works for me in the Dockerfile provided above.

**Comment by r007** [comment]
This fixes problem. Thank you, @tdreyno! :)

**Comment by tdreyno** [comment]
Great, pushing a build out now.

**Comment by moredip** [comment]
@tdreyno out of curiosity, can you share what the issue was (or point to the commit that fixed it)?

**Comment by tdreyno** [comment]
Not sure, doesn't look like I was smart enough to link to the actual commit back in Feb.
