### ISSUE TITLE
set_default_options has been deprecated

### ISSUE THREAD

**Issue by chrishough** [middleman/middleman#1455]
The error:
```
set_default_options has been deprecated, use set_options
default_options has been deprecated, use options
```

Anyone have any idea where this is coming from?  This occurs every time I build my site and I can not seem to locate where...  :cry:

**Comment by Arcovion** [comment]
Please check whether #1457 fixes this:
```ruby
gem 'middleman', github: 'arcovion/middleman', branch: 'slim-update'
```

**Comment by tdreyno** [comment]
Basically, Slim has a new major version which deprecates some method names. But, in v3 we support the old and new APIs. However, there wasn't a good way to figure out which API to use (without a lot of `respond_to?` nonsense) so we stuck with the backwards compatible approach. The side-effect is this warning.

In v4, we only support the new API and the warning is gone.

That said, it's been a year or so, maybe we can drop old Slim support.

**Comment by chrishough** [comment]
When I tried that branch @Arcovion I got the following error:
```
.bundle/ruby/2.1.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim/manifest_resource.rb:3:in `<module:Imageoptim>': uninitialized constant Middleman::Sitemap (NameError)
	from /Users/chrishough/GrokTrunkLive/Huedio/Content/Industry/.bundle/ruby/2.1.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim/manifest_resource.rb:2:in `<module:Middleman>'
	from /Users/chrishough/GrokTrunkLive/Huedio/Content/Industry/.bundle/ruby/2.1.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim/manifest_resource.rb:1:in `<top (required)>'
	from /Users/chrishough/GrokTrunkLive/Huedio/Content/Industry/.bundle/ruby/2.1.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim.rb:7:in `require'
	from /Users/chrishough/GrokTrunkLive/Huedio/Content/Industry/.bundle/ruby/2.1.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim.rb:7:in `<top (required)>'
	from /Users/chrishough/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
	from /Users/chrishough/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/chrishough/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
	from /Users/chrishough/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/chrishough/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
	from /Users/chrishough/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
	from /Users/chrishough/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
	from /Users/chrishough/GrokTrunkLive/Huedio/Content/Industry/.bundle/ruby/2.1.0/bundler/gems/middleman-0230e26a8c55/middleman-core/lib/middleman-core/load_paths.rb:37:in `setup_load_paths'
	from /Users/chrishough/GrokTrunkLive/Huedio/Content/Industry/.bundle/ruby/2.1.0/bundler/gems/middleman-0230e26a8c55/middleman-core/bin/middleman:10:in `<top (required)>'
	from /Users/chrishough/GrokTrunkLive/Huedio/Content/Industry/.bundle/ruby/2.1.0/bin/middleman:23:in `load'
	from /Users/chrishough/GrokTrunkLive/Huedio/Content/Industry/.bundle/ruby/2.1.0/bin/middleman:23:in `<main>'
===>  completed!
``` 

... so I rolled back to using

```
source 'https://rubygems.org'
source 'https://rails-assets.org'
ruby '2.1.0'

gem 'middleman'
gem 'middleman-deploy'
gem 'middleman-pry'
gem 'middleman-blog'
gem 'middleman-blog-similar'
gem 'middleman-imageoptim'
gem 'levenshtein-ffi', :require => 'levenshtein'
gem 'builder'
gem 'nokogiri'
gem 'slim'
gem 'pry'
gem 'font-awesome-middleman'
gem 'middleman-minify-html'
gem 'rake'
gem 'highline'
gem 'rails-assets-jquery'

# Live-reloading plugin
gem 'middleman-livereload', '~> 3.1.0'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw]
```

**Comment by chrishough** [comment]
@tdreyno cool, I was thinking it was just warning, but I wanted to be sure.

**Comment by Arcovion** [comment]
Ok, that's a separate issue:
https://github.com/plasticine/middleman-imageoptim/pull/36

Possibly unintended? @tdreyno

**Comment by tdreyno** [comment]
Unintended

**Comment by tdreyno** [comment]
Lets open a new ticket

**Comment by GiantRavens** [comment]
This also shows up if slim options are called with 'default_options'.

Calling like this does not throw the warning:

# config.rb
require 'slim'
Slim::Engine.options[:pretty] = true
