### ISSUE TITLE
'sass-globbing' error after 3.3.7

### ISSUE THREAD

**Issue by mattsacks** [middleman/middleman#1462]
Looks like using [sass-globbing](https://github.com/chriseppstein/sass-globbing) in 3.3.9 breaks `middleman build` but works fine in 3.3.7. Here's the error we're seeing:

```shell
.../ruby/1.9.1/gems/sass-globbing-1.1.1/lib/sass/globbing/importer.rb:4:in `<top (required)>': uninitialized constant Sass::Importers (NameError)
	from .../ruby/1.9.1/gems/sass-globbing-1.1.1/lib/sass/globbing.rb:6:in `require'
	from .../ruby/1.9.1/gems/sass-globbing-1.1.1/lib/sass/globbing.rb:6:in `<top (required)>'
	from .../ruby/1.9.1/gems/sass-globbing-1.1.1/lib/sass-globbing.rb:1:in `require'
	from .../ruby/1.9.1/gems/sass-globbing-1.1.1/lib/sass-globbing.rb:1:in `<top (required)>'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bundler-1.7.2/lib/bundler/runtime.rb:76:in `require'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bundler-1.7.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bundler-1.7.2/lib/bundler/runtime.rb:72:in `each'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bundler-1.7.2/lib/bundler/runtime.rb:72:in `block in require'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bundler-1.7.2/lib/bundler/runtime.rb:61:in `each'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bundler-1.7.2/lib/bundler/runtime.rb:61:in `require'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bundler-1.7.2/lib/bundler.rb:133:in `require'
	from .../ruby/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/load_paths.rb:37:in `setup_load_paths'
	from .../ruby/1.9.1/gems/middleman-core-3.3.9/bin/middleman:10:in `<top (required)>'
	from .../ruby/1.9.1/bin/middleman:23:in `load'
	from .../ruby/1.9.1/bin/middleman:23:in `<main>'
```

**Comment by tdreyno** [comment]
Any chance you could make a little test project that I can add to our test suite

**Comment by mattsacks** [comment]
I made https://github.com/mattsacks/middleman-sass-globbing-test to demonstrate the issue. Let me know if you need anything else!

**Comment by tdreyno** [comment]
Remove the gem from your Gemfile, works fine for me. That gem is dumb, our globbing is accomplished through sprockets anyways.

Also, that repo doesn't actually include any globbing :)

Let me know if the above doesn't fix the problem in your real app. Please re-open if that's the case.

**Comment by mattsacks** [comment]
:+1:

**Comment by mattsacks** [comment]
Yea, the repo had the same issue with Middleman starting up before I actually got to adding any files for globbing.
