### ISSUE TITLE
`forwardable` is used but not required

### ISSUE THREAD

**Issue by maxmeyer** [middleman/middleman#1479]
I think you need to require `forwardable` explicitly.

```bash
% middleman -h
/home/user/.gem/2.2.0/gems/middleman-core-4.0.0.alpha.5/lib/middleman-core/extension.rb:67:in `<class:Extension>': uninitialized constant Middleman::Extension::Forwardable (NameError)
from /home/user/.gem/2.2.0/gems/middleman-core-4.0.0.alpha.5/lib/middleman-core/extension.rb:66:in `<module:Middleman>'
from /home/user/.gem/2.2.0/gems/middleman-core-4.0.0.alpha.5/lib/middleman-core/extension.rb:5:in `<top (required)>'
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
from /home/user/.gem/2.2.0/gems/middleman-core-4.0.0.alpha.5/lib/middleman-core/extensions.rb:1:in `<top (required)>'
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
from /home/user/.gem/2.2.0/gems/middleman-core-4.0.0.alpha.5/lib/middleman-core.rb:15:in `<top (required)>'
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
from /home/user/.gem/2.2.0/gems/middleman-cli-4.0.0.alpha.5/lib/middleman-cli/server.rb:51:in `server'
from /home/user/.gem/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /home/user/.gem/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
[...]
```

**Comment by maxmeyer** [comment]
Was not closed by commit.
