### ISSUE TITLE
middleman 3.3.10 ruby issue on server start

### ISSUE THREAD

**Issue by ajrob27** [middleman/middleman#1485]
There seems to be an issue related to middleman 3.3.10 when trying to start the server with Ruby 2.2.1 or 2.1.3. There is no problem when using middleman 3.3.9. 

Back trace:
```
== The Middleman is loading
/Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/file_watcher.rb:123:in `initialize': no implicit conversion of nil into String (TypeError)
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/file_watcher.rb:123:in `Pathname'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/file_watcher.rb:123:in `block in reload_path'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/file_watcher.rb:122:in `chdir'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/file_watcher.rb:122:in `reload_path'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/file_watcher.rb:36:in `block in registered'
	from /Users/AJ/.gem/ruby/2.2.1/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
	from /Users/AJ/.gem/ruby/2.2.1/gems/uber-0.0.13/lib/uber/options.rb:80:in `proc!'
	from /Users/AJ/.gem/ruby/2.2.1/gems/uber-0.0.13/lib/uber/options.rb:69:in `evaluate_for'
	from /Users/AJ/.gem/ruby/2.2.1/gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
	from /Users/AJ/.gem/ruby/2.2.1/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
	from /Users/AJ/.gem/ruby/2.2.1/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
	from /Users/AJ/.gem/ruby/2.2.1/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
	from /Users/AJ/.gem/ruby/2.2.1/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
	from /Users/AJ/.gem/ruby/2.2.1/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
	from /Users/AJ/.gem/ruby/2.2.1/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
	from /Users/AJ/.gem/ruby/2.2.1/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/extensions.rb:156:in `initialize'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/data.rb:33:in `initialize'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:52:in `new'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:52:in `inst'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/preview_server.rb:103:in `new_app'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/preview_server.rb:21:in `start'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/cli/server.rb:78:in `server'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/AJ/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/lib/middleman-core/cli.rb:20:in `start'
	from /Users/AJ/.gem/ruby/2.2.1/gems/middleman-core-3.3.10/bin/middleman:18:in `<top (required)>'
	from /Users/AJ/.gem/ruby/2.2.1/bin/middleman:23:in `load'
	from /Users/AJ/.gem/ruby/2.2.1/bin/middleman:23:in `<main>'
```

**Comment by javierjulio** [comment]
@ajrobertson I have a similar setup. I'm running Ruby 2.1.3 with middleman 3.3.10 but I do **not** get this error. If you just created a new temp middleman project `middleman init my-project` and then run `middleman s` do you still get the same error?

**Comment by ajrobertson** [comment]
@javierjulio I do not get the error. It must have something to do with something included in the template. The template can be found here, https://github.com/clearsightstudio/middleman-template.

**Comment by tdreyno** [comment]
Duplicate.
