### ISSUE TITLE
no web page using Jruby 9.0.0

### ISSUE THREAD

**Issue by aplatypus** [middleman/middleman#1486]
Hi.  I started a fresh middleman project, ensuring the right bundles & versions (list attached).

When I point firefox at either:
-  http://0.0.0.0:4567/
-  http://localhost:4567/

There's an unable to connect.  The console output when --Verbose is set, show a NIL object some place:
-  The exception comes from **start**, so looks fairly basic.
-  [2015-03-21 21:25:11] ERROR NoMethodError: undefined method `[]' for nil:NilClass

The first questions are, 
1.  Does middleman run with JRuby? 
2.  Are the right gems and version installed?
3.  How can I find what is going wrong with all thos NIL object exceptions?
4.  Since I've done nothing just a middleman init and server commands -- What can I do to trouble shoot this kind of thing?  

Are there log or diagnostic options I can turn-on, etc?

Hope you can point me in the right direction. 

Regards,
             Will

Projects bundler list

```
----------------
jruby -S bundler list
Gems included by the bundle:
  * activesupport (4.1.10)
  * bundler (1.8.5)
  * celluloid (0.16.0)
  * chunky_png (1.3.4)
  * coffee-script (2.3.0)
  * coffee-script-source (1.9.1)
  * compass (1.0.3)
  * compass-core (1.0.3)
  * compass-import-once (1.0.5)
  * em-websocket (0.5.1)
  * erubis (2.7.0)
  * eventmachine (1.0.7)
  * execjs (2.4.0)
  * ffi (1.9.8)
  * haml (4.0.6)
  * hike (1.2.3)
  * hitimes (1.2.2)
  * hooks (0.4.0)
  * http_parser.rb (0.6.0)
  * i18n (0.7.0)
  * json (1.8.2)
  * kramdown (1.6.0)
  * listen (2.9.0)
  * middleman (3.3.10)
  * middleman-core (3.3.10)
  * middleman-livereload (3.1.1)
  * middleman-sprockets (3.4.2)
  * minitest (5.5.1)
  * multi_json (1.11.0)
  * padrino-helpers (0.12.5)
  * padrino-support (0.12.5)
  * rack (1.6.0)
  * rack-livereload (0.3.15)
  * rack-test (0.6.3)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.5)
  * sass (3.4.13)
  * sprockets (2.12.3)
  * sprockets-helpers (1.1.0)
  * sprockets-sass (1.3.1)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * timers (4.0.1)
  * tzinfo (1.2.2)
  * tzinfo-data (1.2015.1)
  * uber (0.0.13)
  * uglifier (2.7.1)
```

some -verbose output ...

```
----------------------
W:...> jruby -S middleman server  --verbose
WARN: Unresolved specs during Gem::Specification.reset:
      activesupport (>= 3.1, ~> 4.1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
== The Middleman is loading
== Activating: sprockets
== Reading:  Local config
Loaded extensions:
== Extension: sprockets
== Extension: frontmatter
== File Change: config.rb
== File Change: source/images/background.png
== File Change: source/images/middleman.png
== File Change: source/index.html.erb
== File Change: source/javascripts/all.js
== File Change: source/layouts/layout.erb
== File Change: source/stylesheets/all.css
== File Change: source/stylesheets/normalize.css
== Rebuilding resource list
[2015-03-21 21:25:08] INFO  WEBrick 1.3.1
[2015-03-21 21:25:08] INFO  ruby 2.2.0 (2015-01-20) [java]
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?

== The Middleman is standing watch at http://0.0.0.0:4567
== Inspect your site configuration at http://0.0.0.0:4567/__middleman/
[2015-03-21 21:25:08] INFO  WEBrick::HTTPServer#start: pid=5616 port=4567
== File Change: source/index.html.erb
== Rebuilding resource list
== File Change: source/javascripts/all.js
== Rebuilding resource list
== File Change: source/stylesheets/all.css
== Rebuilding resource list
== File Change: source/stylesheets/normalize.css
== Rebuilding resource list
== File Change: source/images/background.png
== Rebuilding resource list
== File Change: source/layouts/layout.erb
== Rebuilding resource list
== File Change: source/images/middleman.png
== Rebuilding resource list
[2015-03-21 21:25:10] INFO  going to shutdown ...
[2015-03-21 21:25:10] INFO  WEBrick::HTTPServer#start done.
== The Middleman is reloading
== Activating: sprockets
== Reading:  Local config
Loaded extensions:
== Extension: sprockets
== Extension: frontmatter
== File Change: config.rb
== File Change: source/images/background.png
== File Change: source/images/middleman.png
== File Change: source/index.html.erb
== File Change: source/javascripts/all.js
== File Change: source/layouts/layout.erb
== File Change: source/stylesheets/all.css
== File Change: source/stylesheets/normalize.css
== Rebuilding resource list
== The Middleman has reloaded
[2015-03-21 21:25:10] INFO  WEBrick::HTTPServer#start: pid=5616 port=4567
[2015-03-21 21:25:10] ERROR NoMethodError: undefined method `[]' for nil:NilClass
        B:/lang/ruby/v09.00-jRuby/lib/ruby/stdlib/webrick/server.rb:174:in `start'
[2015-03-21 21:25:10] ERROR NoMethodError: undefined method `[]' for nil:NilClass
        B:/lang/ruby/v09.00-jRuby/lib/ruby/stdlib/webrick/server.rb:174:in `start'
[2015-03-21 21:25:10] ERROR NoMethodError: undefined method `[]' for nil:NilClass
        B:/lang/ruby/v09.00-jRuby/lib/ruby/stdlib/webrick/server.rb:174:in `start'
[2015-03-21 21:25:10] ERROR NoMethodError: undefined method `[]' for nil:NilClass
        B:/lang/ruby/v09.00-jRuby/lib/ruby/stdlib/webrick/server.rb:174:in `start'
[2015-03-21 21:25:10] ERROR NoMethodError: undefined method `[]' for nil:NilClass
        B:/lang/ruby/v09.00-jRuby/lib/ruby/stdlib/webrick/server.rb:174:in `start'
[2015-03-21 21:25:11] ERROR NoMethodError: undefined method `[]' for nil:NilClass
        B:/lang/ruby/v09.00-jRuby/lib/ruby/stdlib/webrick/server.rb:174:in `start'
[2015-03-21 21:25:11] ERROR NoMethodError: undefined method `[]' for nil:NilClass
        B:/lang/ruby/v09.00-jRuby/lib/ruby/stdlib/webrick/server.rb:174:in `start'
```

**Comment by tdreyno** [comment]
We will try to support JRuby 9000 when it's feature complete. Looks like current release is not yet final.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation as a starting point for discussion around this.
