### ISSUE TITLE
Middleman v4 and HAML

### ISSUE THREAD

**Issue by rensverschuren** [middleman/middleman#1489]
It seems Middleman v4 (`4.0.0.alpha.6` to be exact) doesn’t work well with HAML files. I get this error when running `middleman server`:

```
/Users/rens/.rvm/gems/ruby-2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:144:in `require': cannot load such file -- haml (LoadError)
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:144:in `require_template_library'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/tilt-1.4.1/lib/tilt/haml.rb:14:in `initialize_engine'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:56:in `initialize'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/tilt-1.4.1/lib/tilt.rb:98:in `new'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/tilt-1.4.1/lib/tilt.rb:98:in `block in []'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/tilt-1.4.1/lib/tilt.rb:96:in `each'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/tilt-1.4.1/lib/tilt.rb:96:in `[]'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:251:in `strip_extensions'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:242:in `add_file_to_cache'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:218:in `block in update'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:217:in `each'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:217:in `update'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources/source_watcher.rb:162:in `poll_once!'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources.rb:212:in `each'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sources.rb:212:in `find_new_files!'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/core_extensions/file_watcher.rb:48:in `before_configuration'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `proc!'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/uber-0.0.13/lib/uber/options.rb:69:in `evaluate_for'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/application.rb:237:in `initialize'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/preview_server.rb:100:in `new'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/preview_server.rb:100:in `new_app'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/preview_server.rb:24:in `start'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-cli-4.0.0.alpha.6/lib/middleman-cli/server.rb:69:in `server'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/rens/.rvm/gems/ruby-2.1.0/gems/middleman-cli-4.0.0.alpha.6/bin/middleman:23:in `<top (required)>'
	from /Users/rens/.rvm/gems/ruby-2.1.0/bin/middleman:23:in `load'
	from /Users/rens/.rvm/gems/ruby-2.1.0/bin/middleman:23:in `<main>'
	from /Users/rens/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rens/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```
I have `layout.haml` and `index.html.haml`. This is the content of the `Gemfile`:

```ruby
source 'http://rubygems.org'

# Middleman Gems
gem 'middleman-core', '~> 4.0.0.alpha.6'
gem 'middleman-cli', '~> 4.0.0.alpha.6'
gem 'middleman-sprockets'
gem 'middleman-livereload'
```

Thanks,
Rens

**Comment by Arcovion** [comment]
The Haml dependency is [registered in `middleman`](https://github.com/middleman/middleman/blob/master/middleman/middleman.gemspec#L27) but you're using `middleman-core`.
You can either switch to `middleman` (which contains both core, CLI and sprockets) or simply add `haml` to your `Gemfile`.

**Comment by rensverschuren** [comment]
That fixed the issue. Thank you!
