### ISSUE TITLE
Bower Related Build Error

### ISSUE THREAD

**Issue by shaekuronen** [middleman/middleman#1513]
Have been running into this error occasionally (Middleman 3.3.10)
```
== Rebuilding resource list
== Prerendering CSS
== Request: /bower_components/jquery-modal/jquery.modal.css
== Finishing Request: bower_components/jquery-modal/jquery.modal.css (0.0s)
   identical  build/bower_components/jquery-modal/jquery.modal.css
== Request: /bower_components/jquery-modal/examples/highlight/github.css
== Finishing Request: bower_components/jquery-modal/examples/highlight/github.css (0.0s)
   identical  build/bower_components/jquery-modal/examples/highlight/github.css
== Request: /bower_components/skrollr/examples/fixed-positioning.css
== Finishing Request: bower_components/skrollr/examples/fixed-positioning.css (0.0s)
   identical  build/bower_components/skrollr/examples/fixed-positioning.css
== Request: /bower_components/skrollr/examples/main.css
== Finishing Request: bower_components/skrollr/examples/main.css (0.0s)
   identical  build/bower_components/skrollr/examples/main.css
== Request: /bower_components/slick.js/slick/slick-theme.css
       error  build/bower_components/slick.js/slick/slick-theme.css
undefined method `[]' for nil:NilClass
/Users/shae/.rvm/gems/ruby-2.2.0/gems/sprockets-sass-1.3.1/lib/sprockets/sass/functions.rb:128:in `sprockets_context'
/Users/shae/.rvm/gems/ruby-2.2.0/gems/sprockets-sass-1.3.1/lib/sprockets/sass/functions.rb:63:in `image_path'
/Users/shae/.rvm/gems/ruby-2.2.0/gems/sprockets-sass-1.3.1/lib/sprockets/sass/functions.rb:85:in `image_url'
/Users/shae/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/script/tree/funcall.rb:140:in `_perform'
/Users/shae/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/script/tree/node.rb:50:in `perform'
/Users/shae/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:402:in `visit_return'
```
config.rb is currently
```
###
# Compass
###

# Change Compass configuration
# http://blachniet.com/2014/04/29/middleman-foundation/
compass_config do |config|
  # Require any additional compass plugins here.
  config.output_style = :compact
end

configure :development do
  activate :livereload
  config[:file_watcher_ignore] += [
    /bower_components\//,
    /node_modules\//,
    /images\//
    ]
end

# http://middlemanapp.com/basics/pretty-urls/
activate :directory_indexes

# Add bower's directory to sprockets asset path
after_configuration do
  @bower_config = JSON.parse(IO.read("#{root}/.bowerrc"))
  sprockets.append_path File.join "#{root}", @bower_config["directory"]
end

set :css_dir, 'stylesheets'

set :js_dir, 'javascripts'

set :images_dir, 'images'

set :images_path, '/images'

# Build-specific configuration
configure :build do

  # For example, change the Compass output style for deployment
  activate :minify_css, ignore: [
    'bower_components/*',
    'stylesheets/vendor/*'
  ]

  # Minify Javascript on build
  activate :minify_javascript, ignore: [
    'javascripts/vendor/*',
    'bower_components/*',
  ]

  # Enable cache buster
  activate :asset_hash, ignore: [
    'javascripts/vendor/*',
    'bower_components/*',
    'fonts/*',
    'images/*',
    'stylesheets/vendor/*'
  ]

  activate :autoprefixer, ignore: [
    'bower_components/*',
    'stylesheets/vendor/*'
  ]

  # Use relative URLs
  # activate :relative_assets

  # Or use a different image path
  # set :http_prefix, "/Content/images/"

  # http://middlemanapp.com/advanced/file-size-optimization/#gzip-text-files
  activate :gzip

  # http://middlemanapp.com/advanced/file-size-optimization/#minify-html
  activate :minify_html

end
```
Any idea what's going on?

**Comment by shaekuronen** [comment]
commenting out
```
  # Enable cache buster
  activate :asset_hash, ignore: [
    'javascripts/vendor/*',
    'bower_components/*',
    'fonts/*',
    'images/*',
    'stylesheets/vendor/*'
]
```
resolves the bug, but need to rev files

**Comment by drwl** [comment]
@shaekuronen are you still experiencing this problem?

**Comment by shaekuronen** [comment]
Going to close, not currently an issue
