### ISSUE TITLE
 undefined method `set_options' for Slim::Engine:Class (NoMethodError)

### ISSUE THREAD

**Issue by maxmeyer** [middleman/middleman#1519]
I get this error when running middleman server in a non-middleman-directory:

```
[git:588f42f...]% be middleman server
== Could not find a Middleman project config.rb
== Treating directory as a static site to be served
== The Middleman is loading
/home/user/.gem/2.2.2/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
/home/user/data/projects/middleman/middleman-core/lib/middleman-core/renderers/slim.rb:31:in `registered': undefined method `set_options' for Slim::Engine:Class (NoMethodError)
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/core_extensions/extensions.rb:78:in `register'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/core_extensions/rendering.rb:74:in `registered'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/core_extensions/extensions.rb:78:in `register'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/application.rb:166:in `<class:Application>'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/application.rb:28:in `<module:Middleman>'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/application.rb:27:in `<top (required)>'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/preview_server.rb:99:in `new_app'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/preview_server.rb:24:in `start'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/cli/server.rb:81:in `server'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/user/.gem/2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/cli.rb:20:in `start'
        from /home/user/data/projects/middleman/middleman-core/bin/middleman:18:in `<top (required)>'
        from /home/user/.gem/2.2.2/bin/middleman:23:in `load'
        from /home/user/.gem/2.2.2/bin/middleman:23:in `<main>'
```

```
[git:588f42f...]% bundle show
Gems included by the bundle:
  * activesupport (4.1.10)
  * aruba (0.6.1)
  * asciidoctor (0.1.4)
  * ast (2.0.0)
  * astrolabe (1.3.0)
  * builder (3.2.2)
  * bundler (1.9.4)
  * celluloid (0.16.0)
  * childprocess (0.5.5)
  * chunky_png (1.3.4)
  * coderay (1.1.0)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * commonjs (0.2.7)
  * compass (1.0.3)
  * compass-core (1.0.3)
  * compass-import-once (1.0.5)
  * coveralls (0.7.1)
  * cucumber (1.3.17)
  * diff-lcs (1.2.5)
  * docile (1.1.5)
  * erubis (2.7.0)
  * execjs (2.2.2)
  * ffi (1.9.6)
  * fivemat (1.3.1)
  * gherkin (2.12.2)
  * haml (4.0.6)
  * hike (1.2.3)
  * hitimes (1.2.2)
  * hooks (0.4.0)
  * i18n (0.7.0)
  * json (1.8.2)
  * kramdown (1.7.0)
  * less (2.3.0)
  * libv8 (3.16.14.7)
  * liquid (2.6.1)
  * listen (2.10.0)
  * method_source (0.8.2)
  * middleman (3.3.12)
  * middleman-core (3.3.12)
  * middleman-sprockets (3.3.10 c8e491e)
  * mime-types (2.4.3)
  * minitest (5.6.1)
  * multi_json (1.10.1)
  * multi_test (0.1.1)
  * netrc (0.8.0)
  * padrino-helpers (0.12.5)
  * padrino-support (0.12.5)
  * parser (2.2.0.pre.6)
  * powerpack (0.0.9)
  * pry (0.10.1)
  * rack (1.5.2)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rainbow (2.0.0)
  * rake (10.3.2)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.5)
  * redcarpet (3.2.0)
  * ref (1.0.5)
  * rest-client (1.7.2)
  * rspec (3.1.0)
  * rspec-core (3.1.7)
  * rspec-expectations (3.1.2)
  * rspec-mocks (3.1.3)
  * rspec-support (3.1.2)
  * rubocop (0.27.0)
  * ruby-progressbar (1.6.1)
  * sass (3.4.13)
  * simplecov (0.9.0)
  * simplecov-html (0.8.0)
  * sinatra (1.4.5)
  * slim (2.1.0)
  * slop (3.6.0)
  * sprockets (2.12.3)
  * sprockets-helpers (1.1.0)
  * sprockets-sass (1.2.0)
  * stylus (1.0.1)
  * stylus-source (0.42.2)
  * temple (0.6.10)
  * term-ansicolor (1.3.0)
  * therubyracer (0.12.1)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * timers (4.0.1)
  * tins (1.3.3)
  * tzinfo (1.2.2)
  * uber (0.0.13)
  * uglifier (2.7.1)
  * yard (0.8.7.6)
```

Commit:

```
[git:588f42f...]% git show
commit 588f42f1dfbe388f7292fd41652fc8b5100b42ee
Merge: de52348 27684e2
Author: Eliott Appleford <Arcovion@users.noreply.github.com>
Date:   Wed May 6 14:36:26 2015 +0100

    Merge pull request #1512 from middleman/hostname

    Encode hostnames to fix #1510
```

**Comment by maxmeyer** [comment]
Ok. An update to slime 3.0.3 fixed the problem. Maybe you want to add a version for this to the gemspec?

**Comment by maxmeyer** [comment]
@tdreyno You can close the issue if you like.
