### ISSUE TITLE
Accessing Middleman Config Fails in Browser

### ISSUE THREAD

**Issue by fny** [middleman/middleman#1551]
Visiting http://localhost:4567/__middleman/config/ results in the following error:

```
undefined method `each' for #<Middleman::ExtensionManager:0x007fea9ee84a00>
```

**Comment by fny** [comment]
Seems to be resolved in latest beta.

Closing.

**Comment by zhusee2** [comment]
I'm encountering the same issue with `4.0.0.beta.2`.

```
NoMethodError: undefined method `each' for #<Middleman::ExtensionManager:0x007fa119a22af8>
  ~/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.0.0.beta.2/lib/middleman-core/meta_pages.rb:65:in `config'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.0.0.beta.2/lib/middleman-core/meta_pages.rb:39:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
  ~/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
  ~/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  ~/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  ~/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

I'd suggest closing this issue. If the problem resurfaces a repro or failing test would be a good start in solving this. Ideally also a patch with a fix.
