### ISSUE TITLE
[WINDOWS] uninitialized constant Padrino::Helpers::OutputHelpers

### ISSUE THREAD

**Issue by kiangtengl** [middleman/middleman#1601]
I'm encountering the following error when trying to run `bundle exec middleman build`. I've searched for the error but they seem to be in the past / due to configuration errors in the gemfiles.

**My environment (Installed using RailsInstaller)**

```
> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10240 N/A Build 10240
> ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
> gem -v
2.2.3
> bundler -v
DL is deprecated, please use Fiddle
Bundler version 1.7.7
> irb
DL is deprecated, please use Fiddle
irb(main):001:0> require 'padrino-helpers'
=> true
irb(main):002:0> Padrino::Helpers::OutputHelpers
=> Padrino::Helpers::OutputHelpers
```

**Stacktrace**

```
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-more/core_extensions/default_helpers.rb:7:in `<top (required)>': uninitialized constant Padrino::Helpers::OutputHelpers (NameError)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions.rb:30:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions.rb:30:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-core/application.rb:20:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-core/application.rb:20:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-core/cli/build.rb:95:in `shared_instance'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-core/cli/build.rb:62:in `build'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:72:in `method_missing'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:20:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/bin/middleman:18:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/bin/middleman:23:in `load'
        from C:/RailsInstaller/Ruby2.1.0/bin/middleman:23:in `<main>'
```

**Gemfile**

```
gem "middleman", "~> 3.4.0"
gem "middleman-blog", "~> 3.5.3"
gem "middleman-deploy", "~> 1.0"
gem "builder", "~> 3.0"
gem 'bitters'
gem 'bourbon'
gem 'neat'
```

**Gemfile.lock**
```
GEM
  remote: http://rubygems.org/
  specs:
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    bitters (1.1.0)
      bourbon (>= 4.2)
      sass (>= 3.4)
      thor
    bourbon (4.2.4)
      sass (~> 3.4)
      thor (~> 0.19)
    builder (3.2.2)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    chunky_png (1.3.4)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    erubis (2.7.0)
    execjs (2.6.0)
    ffi (1.9.10)
    ffi (1.9.10-x86-mingw32)
    haml (4.0.7)
      tilt
    hike (1.2.3)
    hooks (0.4.1)
      uber (~> 0.0.14)
    i18n (0.7.0)
    json (1.8.3)
    kramdown (1.8.0)
    listen (3.0.3)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    middleman (3.4.0)
      coffee-script (~> 2.2)
      compass (>= 1.0.0, < 2.0.0)
      compass-import-once (= 1.0.5)
      execjs (~> 2.0)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-core (= 3.4.0)
      middleman-sprockets (>= 3.1.2)
      sass (>= 3.4.0, < 4.0)
      uglifier (~> 2.5)
    middleman-blog (3.5.3)
      addressable (~> 2.3.5)
      middleman-core (~> 3.2)
      tzinfo (>= 0.3.0)
    middleman-core (3.4.0)
      activesupport (~> 4.1)
      bundler (~> 1.1)
      capybara (~> 2.4.4)
      erubis
      hooks (~> 0.3)
      i18n (~> 0.7.0)
      listen (~> 3.0.3)
      padrino-helpers (~> 0.12.3)
      rack (>= 1.4.5, < 2.0)
      thor (>= 0.15.2, < 2.0)
      tilt (~> 1.4.1, < 2.0)
    middleman-deploy (1.0.0)
      middleman-core (>= 3.2)
      net-sftp
      ptools
    middleman-sprockets (3.4.2)
      middleman-core (>= 3.3)
      sprockets (~> 2.12.1)
      sprockets-helpers (~> 1.1.0)
      sprockets-sass (~> 1.3.0)
    mime-types (2.6.2)
    mini_portile (0.6.2)
    minitest (5.8.0)
    multi_json (1.11.2)
    neat (1.7.2)
      bourbon (>= 4.0)
      sass (>= 3.3)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nokogiri (1.6.6.2-x86-mingw32)
      mini_portile (~> 0.6.0)
    padrino-helpers (0.12.5)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.12.5)
      tilt (~> 1.4.1)
    padrino-support (0.12.5)
      activesupport (>= 3.1)
    ptools (1.3.2)
    ptools (1.3.2-x86-mingw32)
      win32-file (>= 0.7.0)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    sass (3.4.18)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-helpers (1.1.0)
      sprockets (~> 2.0)
    sprockets-sass (1.3.1)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uber (0.0.15)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    win32-file (0.7.2)
      ffi
      win32-file-stat (>= 1.4.0)
    win32-file-stat (1.5.2)
      ffi
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby
  x86-mingw32

DEPENDENCIES
  bitters
  bourbon
  builder (~> 3.0)
  middleman (~> 3.4.0)
  middleman-blog (~> 3.5.3)
  middleman-deploy (~> 1.0)
  neat
```

**Comment by tdreyno** [comment]
Did you use `bundle exec` when starting MM?

**Comment by kiangtengl** [comment]
Yup

`bundle exec middleman build`

**Comment by tdreyno** [comment]
If you point your Gemfile at the following, does the issue still occur:

```
gem "middleman", github: "middleman/middleman", branch: "v3-stable"
```

**Comment by kiangtengl** [comment]
Yeah, the exact same error occurs

```
# Gemfile
gem "middleman", github: "middleman/middleman", branch: "v3-stable"

# .........
```

Bundle update output
```
> bundle update
DL is deprecated, please use Fiddle
Fetching git://github.com/middleman/middleman.git
Checking out files: 100% (1130/1130), done.
Fetching gem metadata from http://rubygems.org/..............
Fetching additional metadata from http://rubygems.org/..
Resolving dependencies...
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.4
Using addressable 2.3.8
Using sass 3.4.18
Using thor 0.19.1
Using bourbon 4.2.4
Using bitters 1.1.0
Using builder 3.2.2
Using bundler 1.7.7
Using mime-types 2.6.2
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rack 1.6.4
Using rack-test 0.6.3
Using xpath 2.0.0
Using capybara 2.4.4
Using chunky_png 1.3.4
Using coffee-script-source 1.9.1.1
Using execjs 2.6.0
Using coffee-script 2.4.1
Using multi_json 1.11.2
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.6
Using ffi 1.9.10
Using rb-inotify 0.9.5
Using compass 1.0.3
Using erubis 2.7.0
Using tilt 1.4.1
Using haml 4.0.7
Using hike 1.2.3
Using uber 0.0.15
Using hooks 0.4.1
Using kramdown 1.8.0
Using listen 3.0.3
Using padrino-support 0.12.5
Using padrino-helpers 0.12.5
Using middleman-core 3.4.0 from git://github.com/middleman/middleman.git (at v3-stable)
Using sprockets 2.12.4
Using sprockets-helpers 1.1.0
Using sprockets-sass 1.3.1
Using middleman-sprockets 3.4.2
Using uglifier 2.7.2
Using middleman 3.4.0 from git://github.com/middleman/middleman.git (at v3-stable)
Using middleman-blog 3.5.3
Using net-ssh 2.9.2
Using net-sftp 2.1.2
Using win32-file-stat 1.5.2
Using win32-file 0.7.2
Using ptools 1.3.2
Using middleman-deploy 1.0.0
Using neat 1.7.2
```

**Comment by tommysanterre** [comment]
I have the same issue

**Comment by tdreyno** [comment]
If you're point at Github:

```
gem "middleman", github: "middleman/middleman", branch: "v3-stable"
```

`bundle update` and let me know if the issue is still happening. Added a manual require on our side.

**Comment by tommysanterre** [comment]
I still have the same error.

**Comment by tommysanterre** [comment]
Actually the callstack is different now.

```
c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/meta_pages/sitemap_resource.rb:7:in `<class:SitemapResource>': uninitialized constant Padrino::Helpers::OutputHelpers (NameError)
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/meta_pages/sitemap_resource.rb:6:in `<module:MetaPages>'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/meta_pages/sitemap_resource.rb:4:in `<module:Middleman>'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/meta_pages/sitemap_resource.rb:3:in `<top (required)>'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/meta_pages/sitemap_tree.rb:1:in `require'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/meta_pages/sitemap_tree.rb:1:in `<top (required)>'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/meta_pages.rb:4:in `require'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/meta_pages.rb:4:in `<top (required)>'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/preview_server.rb:4:in `require'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/preview_server.rb:4:in `<top (required)>'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/cli/server.rb:63:in `require'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/cli/server.rb:63:in `server'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/lib/middleman-core/cli.rb:20:in `start'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-db1e8b8611ef/middleman-core/bin/middleman:18:in `<top (required)>'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bin/middleman:23:in `load'
        from c:/Ruby21/lib/ruby/gems/2.1.0/bin/middleman:23:in `<main>'
```

**Comment by tommysanterre** [comment]
I issued a pull request that fixes some more errors about Padrino::Helpers based on @tdreyno fix. I now have a different error.

I fixed some error but I still have one

```
== The Middleman is loading
c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:182:in `rescue in create_default_data_source': No source of timezone data could be found. (TZInfo::DataSourceNotFound)
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:179:in `create_default_data_source'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:40:in `block in get'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:39:in `synchronize'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:39:in `get'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:629:in `data_source'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:92:in `get'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_proxy.rb:67:in `real_timezone'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_proxy.rb:30:in `period_for_utc'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:549:in `current_period'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb:282:in `utc_offset'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb:243:in `block in []'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb:243:in `tap'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb:243:in `[]'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/core_ext/time/zones.rb:61:in `find_zone!'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-blog-3.5.3/lib/middleman-blog/extension.rb:106:in `after_configuration'
        from c:/source/middleman/middleman-core/lib/middleman-core/extension.rb:131:in `block in bind_after_configuration'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/extensions.rb:179:in `initialize'
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/data.rb:31:in `initialize'
        from c:/source/middleman/middleman-core/lib/middleman-core/application.rb:210:in `initialize'
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/request.rb:56:in `new'
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/request.rb:56:in `inst'
        from c:/source/middleman/middleman-core/lib/middleman-core/preview_server.rb:132:in `new_app'
        from c:/source/middleman/middleman-core/lib/middleman-core/preview_server.rb:33:in `start'
        from c:/source/middleman/middleman-core/lib/middleman-core/cli/server.rb:89:in `server'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/source/middleman/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/source/middleman/middleman-core/lib/middleman-core/cli.rb:20:in `start'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/bin/middleman:18:in `<top (required)>'
        from c:/Ruby21/bin/middleman:23:in `load'
        from c:/Ruby21/bin/middleman:23:in `<main>'
```
