### ISSUE TITLE
Can't start middleman server when internet connection is unavailable

### ISSUE THREAD

**Issue by ajsharp** [middleman/middleman#1621]
Using middleman 3.4.0. Tried to run `middleman server` when internet was unavailable, here's what i got:

```
/Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:793:in `send': Network is unreachable - sendto(2) for "224.0.0.251" port 5353 (Errno::ENETUNREACH)
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:793:in `send'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:673:in `request'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:529:in `block in fetch_resource'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:1096:in `block (3 levels) in resolv'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:1094:in `each'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:1094:in `block (2 levels) in resolv'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:1093:in `each'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:1093:in `block in resolv'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:1091:in `each'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:1091:in `resolv'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:520:in `fetch_resource'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:510:in `each_resource'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:407:in `each_address'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:2586:in `each_address'
        from /Users/ajsharp/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb:395:in `getaddresses'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/dns_resolver/basic_network_resolver.rb:36:in `getaddresses'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/dns_resolver.rb:65:in `block in ips_for'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/dns_resolver.rb:64:in `each'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/dns_resolver.rb:64:in `ips_for'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/preview_server/information.rb:110:in `resolve_me'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/preview_server/server_information.rb:52:in `information'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/preview_server/server_information.rb:115:in `bind_address'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/preview_server/server_information.rb:68:in `use'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/preview_server.rb:152:in `new_app'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/preview_server.rb:33:in `start'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/cli/server.rb:89:in `server'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:72:in `method_missing'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:20:in `start'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.4.0/bin/middleman:18:in `<top (required)>'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/bin/middleman:23:in `load'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/bin/middleman:23:in `<main>'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /Users/ajsharp/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ajsharp** [comment]
Looks like `Errno::ENETUNREACH` just needs to be added to the exception list in `basic_network_resolver.rb`. Would you guys accept a pull for that for the 3.4.x branch?

**Comment by tdreyno** [comment]
Ping @maxmeyer

**Comment by maxmeyer** [comment]
@tdreyno I think that makes sense.

**Comment by tdreyno** [comment]
Awesome, a PR would be great, @ajsharp

**Comment by preetpalS** [comment]
This issue still affects middleman version 4. Experienced it with version 4.1.9.

Taking a look at the relevant change (https://github.com/middleman/middleman/pull/1625/files), it does not seem to be applied to the master branch yet (https://github.com/middleman/middleman/blob/24a34aac7e6f9252d56d49d2fe32820480cb4a32/middleman-core/lib/middleman-core/dns_resolver/basic_network_resolver.rb).
