### ISSUE TITLE
How do you write Cucumber tests for v4.0.0.rc.1?

### ISSUE THREAD

**Issue by remino** [middleman/middleman#1675]
I'm trying to set up a new Middleman project and write a simple Cucumber feature test for it. I'm including `middleman-core/step_definitions` in my `features/support/env.rb` file, but I get these warnings and a fatal error when trying to run the tests with `cucumber`:

```
/usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gherkin3-3.1.2/lib/gherkin3/token_matcher.rb:6: warning: already initialized constant Gherkin3::TokenMatcher::LANGUAGE_PATTERN
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gherkin3-3.1.2/lib/gherkin3/token_matcher.rb:6: warning: previous definition of LANGUAGE_PATTERN was here
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gherkin3-3.1.2/lib/gherkin3/dialect.rb:4: warning: already initialized constant Gherkin3::DIALECT_FILE_PATH
/usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gherkin3-3.1.2/lib/gherkin3/dialect.rb:4: warning: previous definition of DIALECT_FILE_PATH was here
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gherkin3-3.1.2/lib/gherkin3/dialect.rb:5: warning: already initialized constant Gherkin3::DIALECTS
/usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gherkin3-3.1.2/lib/gherkin3/dialect.rb:5: warning: previous definition of DIALECTS was here
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/version.rb:5: warning: already initialized constant RSpec::Expectations::Version::STRING
/usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/version.rb:5: warning: previous definition of STRING was here
superclass mismatch for class Or (TypeError)
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/contracts.rb:57:in `<module:Contracts>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/contracts.rb:25:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/util.rb:12:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/util.rb:12:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/rack.rb:6:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/rack.rb:6:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/step_definitions/server_steps.rb:4:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/step_definitions/server_steps.rb:4:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/step_definitions.rb:4:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/step_definitions.rb:4:in `<top (required)>'
/home/user/site/features/support/env.rb:2:in `require'
/home/user/site/features/support/env.rb:2:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/rb_support/rb_language.rb:99:in `load'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/rb_support/rb_language.rb:99:in `load_code_file'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/runtime/support_code.rb:232:in `load_file'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/runtime/support_code.rb:99:in `block in load_files!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/runtime/support_code.rb:98:in `each'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/runtime/support_code.rb:98:in `load_files!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/runtime.rb:262:in `load_step_definitions'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/runtime.rb:65:in `run!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:32:in `execute!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cucumber-2.1.0/bin/cucumber:8:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/bin/cucumber:23:in `load'
/usr/local/opt/rbenv/versions/2.2.2/bin/cucumber:23:in `<main>'
```

Is there something specific I need to `require`? A specific gem or special version I need to use?

Here's my `Gemfile`:

```ruby
source 'https://rubygems.org'

gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

gem 'middleman', '>= 4.0.0.rc.1'
gem 'middleman-blog', '>= 3.6.0.beta.2'
gem 'middleman-compass', '>= 4.0.0.rc.1'
gem 'middleman-deploy', github: 'middleman-contrib/middleman-deploy',
  tag: 'master'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-sprockets', '>= 4.0.0.rc.1'
gem 'slim'

group :development do
  gem 'aruba'
  gem 'capybara'
  gem 'cucumber'
  gem 'pry-byebug'
  gem 'rake'
  gem 'rspec'
end
```

**Comment by tdreyno** [comment]
Currently, we require some very specific gem versions. They are:

https://github.com/middleman/middleman-sprockets/blob/master/Gemfile#L16-L18
