### ISSUE TITLE
Invalid scheme format. compiling JS

### ISSUE THREAD

**Issue by olliekav** [middleman/middleman#1704]
Getting a very strange build error when trying to compile one of my JS files through sprockets. I'm running 4.0.0.rc.2. I've tried ignoring it from the build but still no joy.
```
       error  build/javascripts/ScrollMagic.min-261b1403.js
Invalid scheme format.
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/addressable-2.3.8/lib/addressable/uri.rb:869:in `scheme='
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/addressable-2.3.8/lib/addressable/uri.rb:798:in `block in initialize'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/addressable-2.3.8/lib/addressable/uri.rb:2248:in `call'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/addressable-2.3.8/lib/addressable/uri.rb:2248:in `defer_validation'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/addressable-2.3.8/lib/addressable/uri.rb:795:in `initialize'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/addressable-2.3.8/lib/addressable/uri.rb:138:in `new'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/addressable-2.3.8/lib/addressable/uri.rb:138:in `parse'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-core-4.0.0.rc.2/lib/middleman-core/util.rb:339:in `block in rewrite_paths'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-core-4.0.0.rc.2/lib/middleman-core/util.rb:335:in `gsub'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-core-4.0.0.rc.2/lib/middleman-core/util.rb:335:in `rewrite_paths'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-core-4.0.0.rc.2/lib/middleman-core/middleware/inline_url_rewriter.rb:58:in `call'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/rack-1.6.4/lib/rack/mock.rb:74:in `request'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/rack-1.6.4/lib/rack/mock.rb:56:in `get'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-core-4.0.0.rc.2/lib/middleman-core/builder.rb:148:in `output_resource'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-core-4.0.0.rc.2/lib/middleman-core/builder.rb:78:in `each'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-core-4.0.0.rc.2/lib/middleman-core/builder.rb:78:in `output_files'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-core-4.0.0.rc.2/lib/middleman-core/builder.rb:58:in `run!'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-cli-4.0.0.rc.2/lib/middleman-cli/build.rb:65:in `build'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/gems/middleman-cli-4.0.0.rc.2/bin/middleman:23:in `<top (required)>'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/bin/middleman:23:in `load'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/bin/middleman:23:in `<main>'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/bin/ruby_executable_hooks:15:in `eval'
/Users/olliekav/.rvm/gems/ruby-2.2.3@capra/bin/ruby_executable_hooks:15:in `<main>'
```
I've search around and can't find anyone else with this issue. I'm assuming its related to addressable but currently I'm having to use this file from a CDN rather than using sprockets to include it.

The original file is at...

http://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js

**Comment by tdreyno** [comment]
Is `asset_hash` on

**Comment by olliekav** [comment]
Yep, it builds fine with it.

**Comment by tdreyno** [comment]
I think this is fixed on master now, give it a look

**Comment by olliekav** [comment]
Only thing to flag is the dependency on addressable 3.4.0 breaks Middleman Blog dependency addressable (~> 2.3.5)

**Comment by tdreyno** [comment]
Cool, I'll rev that right now

**Comment by tdreyno** [comment]
Done
