### ISSUE TITLE
middleman fails to install on ubuntu 14.04

### ISSUE THREAD

**Issue by jms1989** [middleman/middleman#1731]
Hello, I am trying to build a dev environment on ubuntu 14.04 with ruby 2.2.3. When I run `gem install middleman -v 3.4` I get a bunch of compiler errors. Running `gem install middleman` results in similar errors. I am just at a loss, I've repeated the error on two systems and I don't understand why. Please advise. Does this have something to do with the docs failing to compile? If so, how do I avoid it?

```ruby
jms1989@webdev:~/middleman/project2$ gem install middleman -v 3.4
Fetching: coffee-script-source-1.10.0.gem (100%)
Successfully installed coffee-script-source-1.10.0
Fetching: execjs-2.6.0.gem (100%)
Successfully installed execjs-2.6.0
Fetching: coffee-script-2.4.1.gem (100%)
Successfully installed coffee-script-2.4.1
Fetching: chunky_png-1.3.5.gem (100%)
Successfully installed chunky_png-1.3.5
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: sass-3.4.20.gem (100%)
Successfully installed sass-3.4.20
Fetching: compass-core-1.0.3.gem (100%)
Successfully installed compass-core-1.0.3
Fetching: compass-import-once-1.0.5.gem (100%)
Successfully installed compass-import-once-1.0.5
Fetching: rb-fsevent-0.9.7.gem (100%)
Successfully installed rb-fsevent-0.9.7
Fetching: ffi-1.9.10.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing middleman:
        ERROR: Failed to build gem native extension.

    /home/jms1989/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20160105-20337-1ox3ekn.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/jms1989/.rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:15:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/jms1989/.rvm/gems/ruby-2.2.3/gems/ffi-1.9.10 for inspection.
Results logged to /home/jms1989/.rvm/gems/ruby-2.2.3/extensions/x86_64-linux/2.2.0/ffi-1.9.10/gem_make.out
```

`gem install middleman`
```ruby
jms1989@webdev:~/middleman/project2$ gem install middleman
Fetching: tilt-1.4.1.gem (100%)
Successfully installed tilt-1.4.1
Fetching: haml-4.0.7.gem (100%)

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Successfully installed haml-4.0.7
Fetching: kramdown-1.9.0.gem (100%)
Successfully installed kramdown-1.9.0
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: middleman-cli-4.0.0.gem (100%)
Successfully installed middleman-cli-4.0.0
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: minitest-5.8.3.gem (100%)
Successfully installed minitest-5.8.3
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: activesupport-4.2.5.gem (100%)
Successfully installed activesupport-4.2.5
Fetching: addressable-2.4.0.gem (100%)
Successfully installed addressable-2.4.0
Fetching: backports-3.6.7.gem (100%)
Successfully installed backports-3.6.7
Fetching: mime-types-data-3.2015.1120.gem (100%)
Successfully installed mime-types-data-3.2015.1120
Fetching: mime-types-3.0.gem (100%)
Successfully installed mime-types-3.0
Fetching: mini_portile2-2.0.0.gem (100%)
Successfully installed mini_portile2-2.0.0
Fetching: nokogiri-1.6.7.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing middleman:
        ERROR: Failed to build gem native extension.

    /home/jms1989/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20160105-20361-1awcai7.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/jms1989/.rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
        from /home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:522:in `with_werror'
        from /home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
        from extconf.rb:80:in `nokogiri_try_compile'
        from extconf.rb:87:in `block in add_cflags'
        from /home/jms1989/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:619:in `with_cflags'
        from extconf.rb:86:in `add_cflags'
        from extconf.rb:336:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/jms1989/.rvm/gems/ruby-2.2.3/gems/nokogiri-1.6.7.1 for inspection.
Results logged to /home/jms1989/.rvm/gems/ruby-2.2.3/extensions/x86_64-linux/2.2.0/nokogiri-1.6.7.1/gem_make.out
```

**Comment by jms1989** [comment]
Solved it by running `sudo apt-get install libgmp-dev`. It appears it doesn't get auto-installed by anything, thus causing the error. :/
