### ISSUE TITLE
4.1.0.rc.1 breaks middleman-blog: undefined method `ignore'

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1749]
`Gemfile`:
```ruby
gem 'middleman', '4.1.0.rc.1'
gem 'middleman-blog', '~> 4.0'
```

When I run `middleman build`:

```
/Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-blog-4.0.0/lib/middleman-blog/extension.rb:109:in `after_configuration': undefined method `ignore' for #<Middleman::Application:0x70097030478740> (NoMethodError)
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.1.0.rc.1/lib/middleman-core/extension.rb:385:in `block in bind_after_configuration'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.1.0.rc.1/lib/middleman-core/callback_manager.rb:51:in `instance_exec'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.1.0.rc.1/lib/middleman-core/callback_manager.rb:51:in `block in execute'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.1.0.rc.1/lib/middleman-core/callback_manager.rb:51:in `execute'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.1.0.rc.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.1.0.rc.1/lib/middleman-core/application.rb:290:in `start_lifecycle'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.1.0.rc.1/lib/middleman-core/application.rb:262:in `initialize'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-cli-4.1.0.rc.1/lib/middleman-cli/build.rb:51:in `new'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-cli-4.1.0.rc.1/lib/middleman-cli/build.rb:51:in `build'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-cli-4.1.0.rc.1/bin/middleman:23:in `<top (required)>'
	from /Users/brh/.rvm/gems/ruby-2.2.1/bin/middleman:23:in `load'
	from /Users/brh/.rvm/gems/ruby-2.2.1/bin/middleman:23:in `<main>'
	from /Users/brh/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/brh/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

This is broken on `master` too (as of 56d71fe7d6bafa32b1874e7bbc2886fd217f3ad8). Tests are broken for `middleman-blog` too.

**Comment by tdreyno** [comment]
Removed `app.ignore` since it didn't look like anything was using it :-p

Turns out something was. Adding back.

**Comment by tdreyno** [comment]
I'll track down those other test failures on blog before 4.1 goes out

**Comment by bhollis** [comment]
Awesome, thanks!
