### ISSUE TITLE
Selenium Acceptance Test failure relating to sprockets/css

### ISSUE THREAD

**Issue by tansaku** [middleman/middleman#1757]
We've got a middleman site with some capybara acceptance tests running.  The default :rack_test driver runs fine, but we were hoping to use selenium since we want to use the send_keys method that hasn't yet been implemented in :rack_test or :selenium  https://github.com/thoughtbot/capybara-webkit/issues/870

Our spec_helper.rb looks like this:

```
require 'middleman'
require 'rspec'
require 'capybara/rspec'

require 'middleman-core/load_paths'
Middleman.setup_load_paths

Capybara.default_driver = :selenium

Capybara.app = Middleman::Application.server.inst do
  set :root, File.expand_path(File.join(File.dirname(__FILE__), '..'))
  set :environment, :test
  set :show_exceptions, false
end
```

Selenium opens the firefox browser for us, however we get the following failure:

```
Error: File to import not found or unreadable: makers_styles.
       Load paths:
         /Users/tansaku/Documents/Github/MakersAcademy/apply/source/stylesheets
         /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/compass-core-1.0.3/stylesheets
         Compass::SpriteImporter
        on line 5 of /Users/tansaku/Documents/Github/MakersAcademy/apply/source/stylesheets/site.css.scss

1: //= require _vendor/pygment_solarized_light
2: //= require _vendor/codemirror-solarized
3: //= require codemirror
4: 
5: @import "makers_styles";
6: 
7: .align-left {
8:   text-align: left;
9: }
10: 
```

Using the network panel I can see this further backtrace:

```
Backtrace:
/Users/tansaku/Documents/Github/MakersAcademy/apply/source/stylesheets/site.css.scss:5
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/import_node.rb:67:in `rescue in import'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/import_node.rb:45:in `import'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/import_node.rb:28:in `imported_file'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/import_node.rb:37:in `css_import?'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:311:in `visit_import'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `map'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:157:in `visit'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:8:in `visit'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/root_node.rb:36:in `css_tree'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/tree/root_node.rb:20:in `render'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sass-3.4.21/lib/sass/engine.rb:278:in `render'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:17:in `block in render'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:29:in `with_import_scope'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:16:in `render'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/renderers/sass.rb:87:in `evaluate'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb:303:in `render_individual_file'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb:181:in `_render_with_all_renderers'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb:149:in `render_template'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:127:in `block in render'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.14/lib/active_support/notifications.rb:161:in `instrument'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/util.rb:41:in `instrument'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/application.rb:235:in `instrument'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:14:in `instrument'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:100:in `render'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:260:in `process_request'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:210:in `block in call!'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:209:in `catch'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:209:in `call!'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:195:in `call'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/server.rb:19:in `call'
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/tansaku/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/tansaku/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/tansaku/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
*/
```

Any ideas? It all works fine in normal operation (we have makers_styles installed via bower, and all looks good outside of the test environment), but not in this capybara selenium setup ...

**Comment by tdreyno** [comment]
Looks like the broken version is going to through the non-sprockets code path so some gem paths are missing when it looks to load files.

Can you try bringing MM up to `3.4.x`?

**Comment by tansaku** [comment]
good idea @tdreyno - tried that and we get a dependency conflict:

```
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    opal (~> 0.8.1) ruby depends on
      sprockets (~> 3.1) ruby

    middleman (~> 3.4) ruby depends on
      middleman-sprockets (>= 3.1.2) ruby depends on
        sprockets (~> 2.1) ruby
```

I can fix that by going to middleman 4, however then middleman won't run without middleman-sprockets, which then leads to this error when middleman starts up:

```
== The Middleman is loading
/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:51:in `initialize': undefined method `include' for #<Middleman::Application:0x70171335216440> (NoMethodError)
```

It feels like we probably need to recreate the app from scratch in Middleman 4 or follow the upgrade path to see if that helps: https://middlemanapp.com/basics/upgrade-v4/

**Comment by tdreyno** [comment]
Looks like the problem is in `opal`. Doesn't seem like a language library should have a specific dependency on sprockets, but they do

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed.

(also, with Middleman 4 I'd suggest trying the external pipeline, no need for sprockets)
