### ISSUE TITLE
Javascript not included with default `middleman init` 4.0

### ISSUE THREAD

**Issue by pixelastic** [middleman/middleman#1776]
Hello,

I just ran the default middleman tutorial from the docs and realized the javascript assets did not seem to be parsed correctly.

Here is what I did:

```
$ gem install middleman
$ middleman version
Middleman 4.0.0
$ middleman init test
# Compass? No
# Livereload? Yes
# Rack? No
$ cd ./test
$ middleman serve
```

And then, when accessing http://127.0.0.1:4567/javascripts/all.js, all I got is:

```
//= require_tree .
```

I would have expected this code to include all the other js files from `/sources/javascripts`, so I added a dummy `test.js` to the directory with content `console.info('This should get printed')`. The file http://127.0.0.1:4567/javascripts/test.js is correctly created, but http://127.0.0.1:4567/javascripts/all.js still displays the `//= require_tree .`.

I tried `require 'test'` instead of `require_tree` without any more success.

Am I missing something here? Should I pass a special option to enable javascript inclusion? Should I name my files something specific?

**Comment by joshukraine** [comment]
`//= require_tree .` is sprockets syntax. As for v4.0, sprockets is not included by default. If you want to use it, you need to include `middleman-sprockets` in your gemfile.

https://github.com/middleman/middleman-sprockets

**Comment by pixelastic** [comment]
Thanks for your answer.

I tried adding `gem 'middleman-sprockets'` to my `Gemfile`, but this resulted in another error.

```
$ bundle install
[...]
Installing middleman-sprockets 3.4.2
[...]
$ middleman serve
== The Middleman is loading
/home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:51:in `initialize': undefined method `include' for #<Middleman::Application:0x31553260> (NoMethodError)
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/extension_manager.rb:64:in `new'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/extension_manager.rb:64:in `activate'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/extensions.rb:120:in `block in auto_activate'
        from /home/tim/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each_key'
        from /home/tim/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/extensions.rb:117:in `auto_activate'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/extension_manager.rb:26:in `auto_activate'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/extension_manager.rb:18:in `block (2 levels) in initialize'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `instance_exec'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `block in execute'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `execute'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:271:in `start_lifecycle'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:265:in `initialize'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/preview_server.rb:140:in `new'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/preview_server.rb:140:in `initialize_new_app'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.0.0/lib/middleman-core/preview_server.rb:33:in `start'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-cli-4.0.0/lib/middleman-cli/server.rb:86:in `server'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/middleman-cli-4.0.0/bin/middleman:23:in `<top (required)>'
        from /home/tim/.rvm/gems/ruby-2.2.3/bin/middleman:23:in `load'
        from /home/tim/.rvm/gems/ruby-2.2.3/bin/middleman:23:in `<main>'
        from /home/tim/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
        from /home/tim/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Not sure what I'm missing here. Should I use the `middleman-sprockets`  4.0.0 RC1 version?

**Comment by pixelastic** [comment]
Actually yes. Using the RC1 version seems to fix it.

Thanks for your help :)

**Comment by tdreyno** [comment]
Looks like I left the old Sprockets stuff in the template: https://github.com/middleman/middleman-templates-default/blob/master/template/source/javascripts/all.js

Will fix

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest closing this issue, since this should be fixed now.

If the problem resurfaces a repro or failing test would be a good start in solving this. Ideally also a patch with a fix.
