### ISSUE TITLE
Bundled templates appear to have JSON version issues

### ISSUE THREAD

**Issue by tamouse** [middleman/middleman#1777]
I installed middleman 4.0.0 a few days ago, and testing out the `html5`, `smacss`, and `mobile` templates all produced the same failure:

```
$ middleman init html5-boilerplate --template=html5
/Users/tamara/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2274:in `check_version_conflict': can't activate json-1.8.2, already activated json-1.8.3 (Gem::LoadError)
	from /Users/tamara/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1403:in `activate'
	from /Users/tamara/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /Users/tamara/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /Users/tamara/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /Users/tamara/.gem/ruby/2.3.0/gems/middleman-cli-4.0.0/lib/middleman-cli/init.rb:30:in `init'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/tamara/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/tamara/.gem/ruby/2.3.0/gems/middleman-cli-4.0.0/bin/middleman:23:in `<top (required)>'
	from /Users/tamara/.gem/ruby/2.3.0/bin/middleman:23:in `load'
	from /Users/tamara/.gem/ruby/2.3.0/bin/middleman:23:in `<main>'
```

OS: OSX 10.11.3
middleman: 4.0.0

Running the `init` command with no template works just fine.

I've run into similar errors attempting to use community-based templates as well, but I wasn't expecting it with the bundled templates.

**Comment by tdreyno** [comment]
You might try running `gem cleanup`, I think this is a Rubygems issue.

**Comment by tamouse** [comment]
@tdreyno -- I no longer get the error. However, now it does not find any of the bundled templates:

```
$ middleman init html5-project --template=html5
Template `html5` not found in Middleman Directory.
Did you mean to use a full `user/repo` path?
$ middleman init mobile-project --template=mobile
Template `mobile` not found in Middleman Directory.
Did you mean to use a full `user/repo` path?
$ middleman init smacss-project --template=smacss
Template `smacss` not found in Middleman Directory.
Did you mean to use a full `user/repo` path?
$ 
```

I uninstalled and reinstalled middleman and have the same error with the 3 templates.

**Comment by tdreyno** [comment]
@tamouse There are no more bundled templates in v4. Rather, they are all hosted on github (so they can be updated outside the normal MM release cycle).

`default` and `blog` are the ones we maintain ourselves. The others are from the community. `html5` was just a copy of https://html5boilerplate.com and `mobile` was https://html5boilerplate.com/mobile/

You can search the community templates here: https://directory.middlemanapp.com/#/templates/all

**Comment by tamouse** [comment]
@tdreyno -- so the documentation will be updated soon?

**Comment by tdreyno** [comment]
Done and done: https://github.com/middleman/middleman-guides/commit/173657e1bc2f1b3362516518dfeeb4b67133b102
