### ISSUE TITLE
Livereload/external_pipeline errors in 4.1.0.rc.2

### ISSUE THREAD

**Issue by joshukraine** [middleman/middleman#1778]
I put together a quick MM 4 app using Gulp and Browserify with the new external_pipeline feature. This seems to work fine with `middleman 4.0.0`. However, when I upgrade to the new `4.1.0.rc.2` version, I start getting a lot of errors in the server log. Livereload also stops reacting to changes. This what I'm seeing:

```sh
== The Middleman is loading
== Executing: `./node_modules/gulp/bin/gulp.js default`
WARN: tilt autoloading 'less' in a non thread-safe way; explicit require 'less' suggested.
WARN: tilt autoloading 'csv' in a non thread-safe way; explicit require 'csv' suggested.
WARN: tilt autoloading 'builder' in a non thread-safe way; explicit require 'builder' suggested.
WARN: tilt autoloading 'markaby' in a non thread-safe way; explicit require 'markaby' suggested.
WARN: tilt autoloading 'liquid' in a non thread-safe way; explicit require 'liquid' suggested.
WARN: tilt autoloading 'radius' in a non thread-safe way; explicit require 'radius' suggested.
WARN: tilt autoloading 'redcarpet' in a non thread-safe way; explicit require 'redcarpet' suggested.
WARN: tilt autoloading 'rdiscount' in a non thread-safe way; explicit require 'rdiscount' suggested.
WARN: tilt autoloading 'rdiscount' in a non thread-safe way; explicit require 'rdiscount' suggested.
WARN: tilt autoloading 'bluecloth' in a non thread-safe way; explicit require 'bluecloth' suggested.
WARN: tilt autoloading 'kramdown' in a non thread-safe way; explicit require 'kramdown' suggested.
WARN: tilt autoloading 'redcloth' in a non thread-safe way; explicit require 'redcloth' suggested.
WARN: tilt autoloading 'rdoc' in a non thread-safe way; explicit require 'rdoc' suggested.
WARN: tilt autoloading 'rdoc/markup' in a non thread-safe way; explicit require 'rdoc/markup' suggested.
WARN: tilt autoloading 'rdoc/markup/to_html' in a non thread-safe way; explicit require 'rdoc/markup/to_html' suggested.
WARN: tilt autoloading 'wikicloth' in a non thread-safe way; explicit require 'wikicloth' suggested.
WARN: tilt autoloading 'creole' in a non thread-safe way; explicit require 'creole' suggested.
WARN: tilt autoloading 'creole' in a non thread-safe way; explicit require 'creole' suggested.
WARN: tilt autoloading 'wikicloth' in a non thread-safe way; explicit require 'wikicloth' suggested.
WARN: tilt autoloading 'wikicloth' in a non thread-safe way; explicit require 'wikicloth' suggested.
WARN: tilt autoloading 'yajl' in a non thread-safe way; explicit require 'yajl' suggested.
WARN: tilt autoloading 'asciidoctor' in a non thread-safe way; explicit require 'asciidoctor' suggested.
WARN: tilt autoloading 'asciidoctor' in a non thread-safe way; explicit require 'asciidoctor' suggested.
WARN: tilt autoloading 'asciidoctor' in a non thread-safe way; explicit require 'asciidoctor' suggested.
== LiveReload accepting connections from ws://10.0.1.5:35729
== External: [18:26:50] Using gulpfile ~/code/middleman/mm4-example/gulpfile.js
== External: [18:26:50] Starting 'scripts'...
== External: [18:26:50] Finished 'scripts' after 17 ms
== External: [18:26:50] Starting 'default'...
== External: [18:26:50] Finished 'default' after 11 ms
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
E, [2016-01-24T18:26:52.419290 #45080] ERROR -- : exception while processing events: Contract violation for argument 2 of 2:
        Expected: String,
        Actual: #<Pathname:javascripts/bundle.js>
        Value guarded in: Middleman::Sources::find
        With Contract: Or, String, Maybe => Maybe
        At: /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.0.rc.2/lib/middleman-core/sources.rb:179  Backtrace:
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts.rb:48:in `block in <class:Contract>'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts.rb:154:in `failure_callback'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts/method_handler.rb:143:in `rescue in block in redefine_method'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts/method_handler.rb:136:in `block in redefine_method'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/config.rb:23:in `call'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/processor.rb:15:in `loop'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/processor.rb:15:in `loop_for'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

If I disable the external_pipeline, I don't get the tilt autoload warnings, but I still do get the "Contract violation error". And Livereload still does not react to changes. For example, when making a trivial html change to `layout.erb` I get this:

```sh
== The Middleman is loading
== LiveReload accepting connections from ws://10.0.1.5:35729
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
E, [2016-01-24T18:34:47.116634 #48049] ERROR -- : exception while processing events: Contract violation for argument 2 of 2:
        Expected: String,
        Actual: #<Pathname:layouts/layout.erb>
        Value guarded in: Middleman::Sources::find
        With Contract: Or, String, Maybe => Maybe
        At: /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.0.rc.2/lib/middleman-core/sources.rb:179  Backtrace:
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts.rb:48:in `block in <class:Contract>'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts.rb:154:in `failure_callback'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts/method_handler.rb:143:in `rescue in block in redefine_method'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts/method_handler.rb:136:in `block in redefine_method'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/config.rb:23:in `call'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/processor.rb:15:in `loop'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/processor.rb:15:in `loop_for'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- /Users/joshukraine/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

Complete app is on GitHub at the links below:

* [Master branch shows site using Middleman v4.0.0](https://github.com/joshukraine/mm4-example)
* [js-4.1.0.rc.2 banch shows site using Middleman v4.1.0.rc.2](https://github.com/joshukraine/mm4-example/tree/js-4.1.0.rc.2)

For what it's worth, I'm on OS X (10.11.3).

Any thoughts? Big thank-you to everyone who's working on this coming release!

**Comment by tdreyno** [comment]
Thank you for providing a great bug description and for helping test a RC. The access to your repo is very helpful.

Looks like an internal method is expecting a string and getting a Pathname.

I'll get it fixed ASAP

**Comment by tdreyno** [comment]
All better

**Comment by joshukraine** [comment]
Awesome, thanks! 🙌🏻
