### ISSUE TITLE
Could not find 'middleman-cli' error

### ISSUE THREAD

**Issue by ibarral** [middleman/middleman#1796]
When I call "middleman server" I get this error:

```
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'middleman-cli' (>= 0) among 41 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/nacho/.gem/ruby/2.3.0:/usr/local/lib/ruby/gems/2.3.0:/usr/local/Cellar/ruby/2.3.0/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/middleman:22:in `<main>'
```

Anyone can help?

Thanks!

**Comment by tdreyno** [comment]
Can you try `bundle exec middleman server`

**Comment by ibarral** [comment]
I just resolve it updating gem manager via gem update --system and then reinstalled middleman gem. 

Thanks!
