### ISSUE TITLE
Cannot access data from config.rb

### ISSUE THREAD

**Issue by alem0lars** [middleman/middleman#1810]
I've the following code snippet in `config.rb`:

``` ruby
activate :blog do |b|
  b.prefix    = data.site.blog.prefix
end
```

And in `data/site.yml` I have:

``` yaml
blog:
  prefix: articles
```

When I run `middleman`, I get the following exception:

```
❯ bundle exec middleman
== The Middleman is loading
/home/alem0lars/.gem/ruby/2.1.0/gems/middleman-blog-4.0.0/lib/middleman-blog/extension.rb:83:in `join': can't convert Middleman::CoreExtensions::Collections::LazyCollectorStep to String (Middleman::CoreExtensions::Collections::LazyCollectorStep#to_str gives Middleman::CoreExtensions::Collections::LazyCollectorStep) (TypeError)
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-blog-4.0.0/lib/middleman-blog/extension.rb:83:in `initialize'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-core-4.1.1/lib/middleman-core/extension_manager.rb:62:in `new'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-core-4.1.1/lib/middleman-core/extension_manager.rb:62:in `activate'
        from /data/tmp/blog/config.rb:39:in `evaluate_configuration!'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-core-4.1.1/lib/middleman-core/application.rb:302:in `instance_eval'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-core-4.1.1/lib/middleman-core/application.rb:302:in `evaluate_configuration!'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-core-4.1.1/lib/middleman-core/application.rb:272:in `initialize'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-core-4.1.1/lib/middleman-core/preview_server.rb:140:in `new'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-core-4.1.1/lib/middleman-core/preview_server.rb:140:in `initialize_new_app'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-core-4.1.1/lib/middleman-core/preview_server.rb:33:in `start'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-cli-4.1.1/lib/middleman-cli/server.rb:86:in `server'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/alem0lars/.gem/ruby/2.1.0/gems/middleman-cli-4.1.1/bin/middleman:23:in `<top (required)>'
        from /home/alem0lars/.gem/ruby/2.1.0/bin/middleman:23:in `load'
        from /home/alem0lars/.gem/ruby/2.1.0/bin/middleman:23:in `<main>'
```

In fact it seems that `data.site.blog.prefix` is being treated as a `LazyCollectorStep` object.

**Comment by tdreyno** [comment]
Ah... I can see why that's happening. I don't think I've seen people use data as extension config before. I'd suggest avoiding that. Basically data is parsed after config because config can set `data_dir`.

I'll think about if there is a way to make this work

**Comment by alem0lars** [comment]
I can avoid using data in config but if I do so, I need to access config in the template (to DRY)

**Comment by alem0lars** [comment]
Is it possible to access config in a template?

**Comment by tdreyno** [comment]
Sure,

So something like:

```
set :my_config, "value"
```

Then in template:

`<%= config[:my_config] %>`

**Comment by avinoth** [comment]
Is it a possibility now? Or if there is a way to have some content that can be accessed by both data and config would also fine. I wanted to generate dynamic pages via data, that's why.

**Comment by tdreyno** [comment]
That's the primary use-case for data. Ignore this bug, this is for something else (and is probably fixed anyways)

**Comment by nulltask** [comment]
I also caused same issue when I would generate dynamic pages via data. But I found workaround that is `proxy` method into `after_configuration` block.

@tdreyno Is it the correct solution?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed. Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.

**Comment by hayley** [comment]
I came across something similar to this a few days ago when I was upgrading a site to v4, but my workaround was to load the data I needed in `/data/` via normal yaml loading instead of through the middleman object.

**Comment by cveneziani** [comment]
Someone on Middleman Forum also pointed another workaround. Since I also struggled a bit on this, I thought it might be good to also share it here.

Instead of doing this:

```ruby
activate :blog do |b|
  b.prefix = data.site.blog.prefix
end
```

The person used `@app.data` this way:

```ruby
activate :blog do |b|
  b.prefix = @app.data.site.blog.prefix
end
```

Not sure it's a good idea to directly use `@app`

**Comment by joapuiib** [comment]
I ran into the same exact problem.
* __config.rb__:
```erb
puts data
data.each do |key, obj|
  puts key
end
```
The previous test lines give me the following error:
```
.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/contracts-0.16.1/lib/contracts.rb:135:in `+': can't convert Middleman::CoreExtensions::Collections::LazyCollectorStep to String (Middleman::CoreExtensions::Collections::LazyCollectorStep#to_str gives Middleman::CoreExtensions::Collections::LazyCollectorStep) (TypeError)
```
I also tried to place them inside the after_configuration block, and it gives me the same error.
```erb
after_configuration do
  puts data
  data.each do |key, obj|
    puts key
  end
end
```

I'm using Middleman v5 (5.0.0.rc.1)

**Comment by tdreyno** [comment]
@joapuiib can you try on the master branch?

**Comment by joapuiib** [comment]
I tried with Middleman v4.4.0 and it gives me the following error:
```
config.rb:43:in `puts': can't convert Middleman::CoreExtensions::Collections::LazyCollectorStep to Array (Middleman::CoreExtensions::Collections::LazyCollectorStep#to_ary gives Middleman::CoreExtensions::Collections::LazyCollectorStep) (TypeError)
```

**Comment by codyrobbins** [comment]
The bug as described above by @joapuiib is still present as of Middleman 4.5.1 unfortunately.
