### ISSUE TITLE
Error with 4.1.2/slim/asset_hash

### ISSUE THREAD

**Issue by Brixy** [middleman/middleman#1819]
Dear Middleman users and producers!

With the brand new version 4.1.2 of Middleman I receive the following error, although I did not change my setup.

```
/Users/Brixy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.2/lib/middleman-core/sitemap/extensions/proxies.rb:89:in `target_resource': Path tag/mytag.html proxies to unknown file tags.html:["index.html", ".htaccess", …]
```

The template language I use is is **slim.**

Here the config

```
activate :blog do |blog|
  blog.name = "journal"
  blog.permalink = ":title.html"
  blog.sources = "texte/:year-:month-:day-:title.html"
  blog.tag_template = "tags.html"
  blog.taglink = "tag/:tag.html"
end

configure :build do
  activate :minify_html
  activate :minify_css
  activate :minify_javascript
  activate :gzip
  activate :asset_hash
end
```

Maybe this question is more appropriate for the `middleman-blog` project?!

Thank you

**Comment by tdreyno** [comment]
Thanks for reporting. I suggest going back to 4.1.1 for now, I'll look into it.

**Comment by 5t111111** [comment]
I've encountered the same problem with a project using `middleman-blog` (https://github.com/5t111111/middleman-blog-drops-template) .

```
/Users/hirofumiwakasugi/Laboratory/middleman-blog-drops-template/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.2/lib/middleman-core/sitemap/extensions/proxies.rb:89:in `target_resource': Path 2015/11/20.html proxies to unknown file calendar.html:["2015/11/20.html", "javascripts/all.js.map", "404.html", "archives.html", "author.html", "by-year.html", "feed.xml", "images/drops.png", "images/favicon.png", "images/profile.png", "index.html", "posts/2015-11-20-this-is-an-example-article.html", "robots.txt", "tags.html", "tags/odd.html", "tags/even.html", "2015.html", "2015/11.html", "javascripts/all.js"] (RuntimeError)
```

**Comment by Brixy** [comment]
Hi!

not sure, whether this issue is related, but version 4.1.3 produces the following error message.

```
/Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'middleman-blog'. (Bundler::GemRequireError)
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.3/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.3/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
	from /Users/…/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.3/bin/middleman:10:in `<top (required)>'
	from /Users/…/.rbenv/versions/2.2.3/bin/middleman:23:in `load'
	from /Users/…/.rbenv/versions/2.2.3/bin/middleman:23:in `<main>'
```

That is I am still using version 4.1.1 for active development. Thanks again for investigating.

**Comment by Brixy** [comment]
Maybe, I found out what causes the error, @tdreyno.

After uninstalling all gems including bundler and re-installing gems required by middleman, I noticed that `bundle install` strangely installs `middleman-blog-0.1.5` instead of the current version 4.0.0.

Unfortunately, I am not familiar enough with github to check/update the source code online.

Now, middleman 4.1.4 is working.

**Comment by tdreyno** [comment]
Thanks for researching. That's very strange.
