### ISSUE TITLE
Middleman 4.1.2 on Windows with ruby 2.2.4p230 - ISSUE!

### ISSUE THREAD

**Issue by blakegades** [middleman/middleman#1828]
**I am using windows 7 with ruby 2.2.4p230 installed.**

_On fresh start I had gem list as_

```
$ gem list
bigdecimal (1.2.6)
io-console (0.4.3)
json (1.8.1)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
```

Then I installed middleman, and I had a gem list of : 

```
$ gem list
activesupport (4.2.5.2)
addressable (2.4.0)
backports (3.6.8)
bigdecimal (1.2.6)
bundler (1.11.2)
capybara (2.5.0)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
compass-import-once (1.0.5)
concurrent-ruby (1.0.1)
contracts (0.13.0)
erubis (2.7.0)
execjs (2.6.0)
fast_blank (1.0.0)
fastimage (1.8.1)
ffi (1.9.10 x86-mingw32)
haml (4.0.7)
hamster (3.0.0)
hashie (3.4.3)
i18n (0.7.0)
io-console (0.4.3)
json (1.8.1)
kramdown (1.10.0)
listen (3.0.6)
middleman (4.1.2)
middleman-cli (4.1.2)
middleman-core (4.1.2)
mime-types (3.0)
mime-types-data (3.2016.0221)
mini_portile2 (2.0.0)
minitest (5.8.4)
nokogiri (1.6.7.2 x86-mingw32)
padrino-helpers (0.13.1)
padrino-support (0.13.1)
parallel (1.6.2)
psych (2.0.8)
rack (1.6.4)
rack-test (0.6.3)
rake (10.4.2)
rb-fsevent (0.9.7)
rb-inotify (0.9.7)
rdoc (4.2.0)
sass (3.4.21)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
tzinfo (1.2.2)
uglifier (2.7.2)
xpath (2.0.0)

```

Then I did middleman init and got this:

```
$ middleman init test_project
         run  git clone --depth 1 git://github.com/middleman/middleman-templates-default.git C:/Users/DARKMI~1/AppData/Local/Temp/d20160305-3036-l0t69g from "."
Cloning into 'C:/Users/DARKMI~1/AppData/Local/Temp/d20160305-3036-l0t69g'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 22 (delta 0), reused 14 (delta 0), pack-reused 0
Receiving objects: 100% (22/22), 6.07 KiB | 0 bytes/s, done.
Checking connectivity... done.
       exist
      create  C:/Users/DarkMirror/AppData/Local/Temp/d20160305-3036-l0t69g/template/.gitignore
C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Invalid argument @ dir_s_mkdir - C:/Users/DarkMirror/middleman/test_project/C: (Errno::EINVAL)
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:210:in `each'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:61:in `block in invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:92:in `block in execute!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:80:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:80:in `execute!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:66:in `invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:52:in `directory'
        from C:/Users/DARKMI~1/AppData/Local/Temp/d20160305-3036-l0t69g/Thorfile:10:in `copy_default_files'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.2/lib/middleman-cli/init.rb:77:in `block in init'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `block in inside'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `inside'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.2/lib/middleman-cli/init.rb:71:in `init'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.2/bin/middleman:23:in `<top (required)>'
        from C:/Ruby22/bin/middleman:23:in `load'
        from C:/Ruby22/bin/middleman:23:in `<main>'
```

so I thought It couldn't copy the files from the template so I manually downloaded them by

```
 $ git clone git://github.com/middleman/middleman-templates-default.git

```

Then inside template folder I ran `bundle` before `middleman` it gave out

```
$ bundle
Fetching gem metadata from https://rubygems.org/.....
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using thread_safe 0.3.5
Installing wdm 0.1.1 with native extensions
Using bundler 1.11.2
Using tzinfo 1.2.2
Installing tzinfo-data 1.2016.1
Bundle complete! 2 Gemfile dependencies, 5 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

then when executing `bundle exec middleman` it gave out:

```
$ bundle exec middleman
C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.2/bin/middleman:3:in `require': cannot load such file -- middleman-core/profiling (LoadError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.2/bin/middleman:3:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/bin/middleman:23:in `load'
        from C:/Ruby22/lib/ruby/gems/2.2.0/bin/middleman:23:in `<main>'

```

added middleman-cli to Gemfile too and everything but now it seems like i've reached a dead end of my knowledge.
before logging out my process here I did try different versions of middleman but none of them seems to work.
Anybody know the solution?

**Comment by tdreyno** [comment]
Thank you for reporting.

For some reason, the windows versions of Ruby seem to require more explicit require statements than any other platform. I will add the profiling require to hopefully fix that second issue.

I suspect the first issue is an upstream Thor bug. Without a Windows machine myself, I can't debug.

**Comment by jawwadzafar** [comment]
You can use this template:

https://github.com/jawwadzafar/middleman-boilerplate.git

**Comment by jawwadzafar** [comment]
anyone facing problem on windows can use this :
https://github.com/jawwadzafar/middleman-boilerplate.git

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation as a starting point for discussion around this.
