### ISSUE TITLE
 `include': wrong argument type Class (expected Module) (TypeError)

### ISSUE THREAD

**Issue by dsignr** [middleman/middleman#1839]
When trying to import a custom extension, located inside a folder (one level outside of `sources` called `helpers`), I get this error.

Inside my `helpers` folder, there's a file called `post_helper.rb` with contents:

```ruby
class PostHelper < ::Middleman::Extension
  def initialize(app, options_hash={}, &block)
    super
  end

  #Helpers
  helpers do
    #Get Post Author
    def post_author(article)
      if article.data then article.data.author
      else "Anonymous" end
    end #End method
  end #End Helpers
end #End class

::Middleman::Extensions.register(:articles_helper, ArticlesHelper)
```

I actually followed this article which said something like the above can be done:
http://torspark.com/how-to-calculate-article-reading-time-with-a-custom-middleman-extension/

The error trace is as follows:

```ruby
/Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/core_extensions/external_helpers.rb:25:in `include': wrong argument type Class (expected Module) (TypeError)
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/core_extensions/external_helpers.rb:25:in `block in after_configuration'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/core_extensions/external_helpers.rb:18:in `each'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/core_extensions/external_helpers.rb:18:in `after_configuration'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/extension.rb:402:in `block in bind_after_configuration'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/contracts-0.12.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/contracts-0.12.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/contracts-0.12.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/application.rb:290:in `initialize'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/preview_server.rb:140:in `new'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/preview_server.rb:140:in `initialize_new_app'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/preview_server.rb:33:in `start'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-cli-4.1.1/lib/middleman-cli/server.rb:86:in `server'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/gems/middleman-cli-4.1.1/bin/middleman:23:in `<top (required)>'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/bin/middleman:23:in `load'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/bin/middleman:23:in `<main>'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/aiwa/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Any thoughts on this? Thanks.

**Comment by tdreyno** [comment]
Extensions != Helpers. Anything in `helpers/` is auto-parsed and included. Put this extension into `lib/`

**Comment by dsignr** [comment]
Wow, thank you! That's so cool. So, just to clarify, I am not looking to build an extension, I just want a way to have my helper methods included into the main app, to be used inside templates.

So, let's say, I create a file `helpers/foo.rb` whose contents are:

```ruby

def bar
"hello"
end
```

I can later access these in my templates as `= bar`?

Or.. do I need to put them inside a class like so:

```ruby
class Foo < Middleman::Helpers #Just an example
 def bar
  "Hi"
 end
end #End class
```

Thank you very much, I love this project :+1:

**Comment by dsignr** [comment]
Nevermind, I figured it, thanks :)

**Comment by tdreyno** [comment]
Helpers are modules (it's a ruby thing, I apologize if its not apparent. We're following the standards that Rails uses):

```
module ImageHelpers
  def do_image
  end
end
```

**Comment by dsignr** [comment]
Thank you, I also just realized it's on the documentation :D
