### ISSUE TITLE
More than 6 iterations of proxy crashes middleman

### ISSUE THREAD

**Issue by sandstrom** [middleman/middleman#1846]
I've run into a weird bug, where using proxy more than 6 times crashes middleman.

```ruby
# works
6.times do |i|
  path = "/tb/i-#{i.to_s}.html"
  proxy path, '/dyn/template.html', :ignore => true
end

# doesn't work
7.times do |i|
  path = "/tb/i-#{i.to_s}.html"
  proxy path, '/dyn/template.html', :ignore => true
end
```

The error message is something like this:

> ../middleman-core-4.1.2/lib/middleman-core/sitemap/extensions/proxies.rb:89:in `target_resource': Path other-unrelated-file.html proxies to unknown file localizable/other-unrelated-file.html

```
from /gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
from /gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
from /gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/extensions/proxies.rb:105:in `metadata'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/resource.rb:90:in `page_id'
from /gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
from /gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
from /gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/store.rb:241:in `block (5 levels) in ensure_resource_list_updated!'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/store.rb:238:in `each'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/store.rb:238:in `block (4 levels) in ensure_resource_list_updated!'
from /gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
from /gems/middleman-core-4.1.2/lib/middleman-core/util.rb:21:in `instrument'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/store.rb:230:in `block (3 levels) in ensure_resource_list_updated!'
from /gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
from /gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
from /gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/store.rb:229:in `block (2 levels) in ensure_resource_list_updated!'
from /gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
from /gems/middleman-core-4.1.2/lib/middleman-core/util.rb:21:in `instrument'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/store.rb:222:in `block in ensure_resource_list_updated!'
from /Users/cta/.rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/store.rb:219:in `ensure_resource_list_updated!'
from /gems/middleman-core-4.1.2/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
from /gems/middleman-core-4.1.2/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
from /gems/middleman-core-4.1.2/lib/middleman-core/callback_manager.rb:57:in `block in execute'
from /gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
from /gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
from /gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
from /gems/middleman-core-4.1.2/lib/middleman-core/callback_manager.rb:57:in `execute'
from /gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
from /gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
from /gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
from /gems/middleman-core-4.1.2/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
from /gems/middleman-core-4.1.2/lib/middleman-core/application.rb:293:in `initialize'
from /gems/middleman-cli-4.1.2/lib/middleman-cli/build.rb:60:in `new'
from /gems/middleman-cli-4.1.2/lib/middleman-cli/build.rb:60:in `block in build'
from /gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
from /gems/middleman-core-4.1.2/lib/middleman-core/util.rb:21:in `instrument'
from /gems/middleman-cli-4.1.2/lib/middleman-cli/build.rb:59:in `build'
from /gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
from /gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
from /gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
from /gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
from /gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
from /gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
from /gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
from /gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /gems/middleman-cli-4.1.2/bin/middleman:23:in `<top (required)>'
from /bin/middleman:23:in `load'
from /bin/middleman:23:in `<main>'
```

***

I can consistently reproduce this with our middleman site. Haven't been able to reproduce on a clean middleman install yet.

@tdreyno Any thoughts on why this may happen? The only thing I can think of is that some storage mechanism (the sitemap?) gets full, causing other pages to be pushed out and fail.

Happy to provide access via screen-sharing.

**Comment by stevenosloan** [comment]
@sandstrom this feels similar to an issue I had run into that was fixed by #1836, if you're not running of master after that's merged maybe give that a try?

**Comment by sandstrom** [comment]
@stevenosloan Awesome! `1000.times { "Thanks!" }`

This was driving me insane yesterday evening, trying to get it to work. And thanks @tdreyno for fixing the issue!

**Comment by tdreyno** [comment]
Will get a new release out within the next 36 hours

**Comment by puyo** [comment]
yvw ;-)
