### ISSUE TITLE
Upgrade from 4.0 to 4.1.7 middleman serve issue

### ISSUE THREAD

**Issue by ryankbales** [middleman/middleman#1899]
I'm not finding much on the internet in regards to the following error, so this very well could be something I have done incorrectly.  I updated to 4.1.7 from 4.0 and also ugraded to Ruby 2.2.2 and got a successful bundle after resolving the following:

```
Bundler could not find compatible versions for gem "middleman-core":
  In Gemfile:
    middleman (>= 4.1) ruby depends on
      middleman-core (= 4.1.0) ruby

    middleman-compass (>= 4.0.0) ruby depends on
      middleman-core (4.0.0)
```

and then

```
An error occurred while installing listen (3.1.1), and Bundler cannot continue.
Make sure that `gem install listen -v '3.1.1'` succeeds before bundling.
```

This is when I had to upgrade Ruby, and then I got a clean bundle.  When running `middleman serve`:

```
/usr/local/rvm/gems/ruby-2.2.2/gems/middleman-core-4.1.7/lib/middleman-core/extensions.rb:96:in `load': Tried to activate old-style extension: deploy. They are no longer supported. (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.2.2/gems/middleman-core-4.1.7/lib/middleman-core/extensions.rb:127:in `block in load_settings'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/middleman-core-4.1.7/lib/middleman-core/extensions.rb:125:in `each'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/middleman-core-4.1.7/lib/middleman-core/extensions.rb:125:in `load_settings'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/middleman-core-4.1.7/lib/middleman-core/extension_manager.rb:12:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/middleman-core-4.1.7/lib/middleman-core/application.rb:262:in `new'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/middleman-core-4.1.7/lib/middleman-core/application.rb:262:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/middleman-cli-4.1.7/bin/middleman:48:in `new'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/middleman-cli-4.1.7/bin/middleman:48:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/middleman:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/middleman:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

I'll keep plugging away, maybe reverting back and starting again.  Thanks.

**Comment by ryankbales** [comment]
Well, as soon as I posted the issue, I found the solution.  It was related to the `middleman-deploy` gem.  made the following adjustment to my Gemfile:

`gem 'middleman-deploy', github: 'middleman-contrib/middleman-deploy', branch: 'master'`

**Comment by tdreyno** [comment]
We should ask them to do a gem release

**Comment by ryankbales** [comment]
Done. [issue](https://github.com/middleman-contrib/middleman-deploy/issues/122)
