### ISSUE TITLE
Middleman fails with error when adding bower_components folder inside source/assets/vendor

### ISSUE THREAD

**Issue by rubytastic** [middleman/middleman#1908]
When adding a bower_components folder with serveral assets like bootstrap, font-awesome middleman crashes..

/sites/gems/tilt-1.4.1/lib/tilt/template.rb:144:in `require': cannot load such file -- less (LoadError)

I have rebuild a complete site adding and removing files untill this cause showed up.
Why is it not possible to store bower_components inside the source folder, its the ideal way to manage external dependencies. I use middleman 4 latest version in a clean rvm bundle and did a clean middleman init.

Full trace
```
from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/tilt-1.4.1/lib/tilt/template.rb:144:in `require_template_library'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/tilt-1.4.1/lib/tilt/css.rb:59:in `initialize_engine'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/tilt-1.4.1/lib/tilt/template.rb:56:in `initialize'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/tilt-1.4.1/lib/tilt.rb:98:in `new'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/tilt-1.4.1/lib/tilt.rb:98:in `block in []'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/tilt-1.4.1/lib/tilt.rb:96:in `each'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/tilt-1.4.1/lib/tilt.rb:96:in `[]'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources/source_watcher.rb:322:in `strip_extensions'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources/source_watcher.rb:310:in `record_file_change'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources/source_watcher.rb:257:in `block in update'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources/source_watcher.rb:256:in `each'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources/source_watcher.rb:256:in `update'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources/source_watcher.rb:204:in `poll_once!'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources.rb:239:in `block in poll_once!'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources.rb:239:in `each'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources.rb:239:in `reduce'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/sources.rb:239:in `poll_once!'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/core_extensions/file_watcher.rb:50:in `before_configuration'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-core-4.1.7/lib/middleman-core/application.rb:282:in `initialize'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-cli-4.1.7/bin/middleman:48:in `new'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/gems/middleman-cli-4.1.7/bin/middleman:48:in `<top (required)>'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/bin/middleman:23:in `load'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/bin/middleman:23:in `<main>'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/bin/ruby_executable_hooks:15:in `eval'
	from /Users/me2/.rvm/gems/ruby-2.3.1@sites/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tdreyno** [comment]
`bower_components` simply has too many files for Middleman to watch. It also, often, includes files you don't want to compile, like your dependencies' source files in `.less`.

`bower_components` and `node_modules` belong in the root of the project. Use either `middleman-sprockets` or the `import_path` command to integrate these files with your project.

Sprockets will allow you to `require` whichever components you need into JS and CSS.

`import_path` will simply make those files available as if they were in your source folder, but, without watching the files for changes.

**Comment by rubytastic** [comment]
Ok thank you my bad then, i think i have to reread the manuals for 4 then.

**Comment by tdreyno** [comment]
I'm not sure that we explicitly talk about bower in relation to Middleman... too many possible combinations of different techs.

**Comment by rubytastic** [comment]
How would one use the import_path ?
Could not find it in the documentation thank you

**Comment by tdreyno** [comment]
Like line #3 of this test: https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/import-app/config.rb#L3

We don't really document little-used features until enough folks need them. Trying to keep the docs slimmed down to the common use cases.
