### ISSUE TITLE
Error launching "middleman build --verbose" only when I put "active :minify_css" and/or "activate: minify_javascript"

### ISSUE THREAD

**Issue by aaromnido** [middleman/middleman#1915]
Hi there, I'm dealing with an issue that's make me crazy. Anyone can help me?

_OS X 10.11.4
Ruby 2.3.1 by RVM
Middleman 4.1.7_
**Only when I try to compile the project for deploy (middleman build) it raise this error (in --verbose way):**
```
== Finishing Request: index.html (0.05s)
       error  build/index.html
undefined method `try' for "text/html; charset=utf-8":String
Did you mean?  tr
               tr!
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/extensions/minify_css.rb:62:in `call'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/core_extensions/inline_url_rewriter.rb:61:in `call'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/mock.rb:74:in `request'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/mock.rb:56:in `get'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/builder.rb:230:in `block in output_resource'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/util.rb:21:in `instrument'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/builder.rb:223:in `output_resource'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:437:in `call_with_index'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:408:in `process_incoming_jobs'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:390:in `block in worker'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:383:in `fork'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:383:in `worker'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:374:in `block in create_workers'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:373:in `each'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:373:in `create_workers'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:315:in `work_in_processes'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/parallel-1.8.0/lib/parallel.rb:241:in `map'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/builder.rb:135:in `output_resources'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/builder.rb:129:in `output_files'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/builder.rb:71:in `block in run!'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/util.rb:21:in `instrument'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/builder.rb:70:in `run!'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-cli-4.1.7/lib/middleman-cli/build.rb:80:in `block in build'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.7/lib/middleman-core/util.rb:21:in `instrument'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-cli-4.1.7/lib/middleman-cli/build.rb:79:in `build'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/gems/middleman-cli-4.1.7/bin/middleman:67:in `<top (required)>'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/bin/middleman:23:in `load'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/bin/middleman:23:in `<main>'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/fernandovalanguas/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
      remove  build/images/hero-bg-dd829794.png
      remove  build/images/hero-bg-small-b64f4cf3.png
      remove  build/images/icon-arrow-bottom-cb47e0b5.png
      remove  build/images/icon-arrow-button-small-9c4fcca0.png
      remove  build/images/logo-footer-308fc5a1.png
      remove  build/images/logo-semanticmerge-f4a81290.png
      remove  build/images/picture-procedence-a53be784.png
      remove  build/images/robot-and-ufo-aa8c5890.png
      remove  build/images/screenshot-semanticmerge-2-b86105a0.png
      remove  build/images/sprite-social-bar-221d7b6c.png
There were errors during this build
➜  mid-semanticmerge 
`

**This is my "config.rb":**
`
Page options, layouts, aliases and proxies


 Per-page layout changes:

 With no layout
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

 With alternative layout
 page "/path/to/file.html", layout: :otherlayout

 Proxy pages (http://middlemanapp.com/basics/dynamic-pages/)
 proxy "/this-page-has-no-template.html", "/template-file.html", locals: {
  which_fake_page: "Rendering a fake page with a local variable" }

General configuration

Reload the browser automatically whenever files change
configure :development do
  activate :livereload
end

set :relative_links, true

 Ignore files
ignore ".DS_Store"
ignore "imageoptim.manifest.yml"



 Helpers


 Methods defined in the helpers block are available in templates
 helpers do
   def some_helper
     "Helping"
   end
end

Build-specific configuration
configure :build do
    Minify CSS on build
    activate :minify_css

    Minify Javascript on build
    activate :minify_javascript

    Enable cache buster
    activate :asset_hash

    Use relative URLs
    activate :relative_assets
end
`
**My "Gemfile":**
`If you do not have OpenSSL installed, change
the following line to use 'http://'
source 'https://rubygems.org'

For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'

SASS Libraries
gem 'bitters'
gem 'bourbon'
gem 'neat'
`
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    backports (3.6.8)
    bitters (1.3.1)
      bourbon (>= 5.0.0.beta.3)
      sass (~> 3.4)
      thor (~> 0.19)
    bourbon (5.0.0.beta.5)
      sass (~> 3.4)
      thor (~> 0.19)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.2)
    contracts (0.13.0)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.0.1)
    execjs (2.6.0)
    fast_blank (1.0.0)
    fastimage (2.0.0)
      addressable (~> 2)
    ffi (1.9.10)
    haml (4.0.7)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.4.4)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    json (1.8.3)
    kramdown (1.11.1)
    listen (3.1.3)
      rb-fsevent (~> 0.9, >= 0.9.7)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    middleman (4.1.7)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.7)
      middleman-core (= 4.1.7)
      sass (>= 3.4.0, < 4.0)
    middleman-cli (4.1.7)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.1.7)
      activesupport (~> 4.2)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      capybara (~> 2.5.0)
      contracts (~> 0.13.0)
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      servolux
      tilt (~> 1.4.1)
      uglifier (~> 3.0)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0221)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    neat (1.7.4)
      bourbon (>= 4.0)
      sass (>= 3.3)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    padrino-helpers (0.13.2)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.2)
      tilt (>= 1.4.1, < 3)
    padrino-support (0.13.2)
      activesupport (>= 3.1)
    parallel (1.8.0)
    rack (1.6.4)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    ruby_dep (1.3.1)
    sass (3.4.22)
    servolux (0.12.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.0)
      execjs (>= 0.3.0, < 3)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  bitters
  bourbon
  middleman (>= 4.0.0)
  middleman-livereload
  neat
  tzinfo-data
  wdm (~> 0.1.0)

BUNDLED WITH
   1.12.3

`GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    backports (3.6.8)
    bitters (1.3.1)
      bourbon (>= 5.0.0.beta.3)
      sass (~> 3.4)
      thor (~> 0.19)
    bourbon (5.0.0.beta.5)
      sass (~> 3.4)
      thor (~> 0.19)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.2)
    contracts (0.13.0)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.0.1)
    execjs (2.6.0)
    fast_blank (1.0.0)
    fastimage (2.0.0)
      addressable (~> 2)
    ffi (1.9.10)
    haml (4.0.7)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.4.4)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    json (1.8.3)
    kramdown (1.11.1)
    listen (3.1.3)
      rb-fsevent (~> 0.9, >= 0.9.7)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    middleman (4.1.7)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.7)
      middleman-core (= 4.1.7)
      sass (>= 3.4.0, < 4.0)
    middleman-cli (4.1.7)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.1.7)
      activesupport (~> 4.2)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      capybara (~> 2.5.0)
      contracts (~> 0.13.0)
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      servolux
      tilt (~> 1.4.1)
      uglifier (~> 3.0)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0221)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    neat (1.7.4)
      bourbon (>= 4.0)
      sass (>= 3.3)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    padrino-helpers (0.13.2)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.2)
      tilt (>= 1.4.1, < 3)
    padrino-support (0.13.2)
      activesupport (>= 3.1)
    parallel (1.8.0)
    rack (1.6.4)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    ruby_dep (1.3.1)
    sass (3.4.22)
    servolux (0.12.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.0)
      execjs (>= 0.3.0, < 3)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  bitters
  bourbon
  middleman (>= 4.0.0)
  middleman-livereload
  neat
  tzinfo-data
  wdm (~> 0.1.0)

BUNDLED WITH
   1.12.3
```

**Comment by aaromnido** [comment]
**Just fixed!!**

It seems there was a problem with my "legacy" Gemfile.lock. I only removed all the content in this file, "middleman build" again, and it works fine and my Gemfile.lock was regenerated with a correct list of gems.

_(This project is a fork from another older Middleman site, and this is the reason because I have legacy code.)_

**Comment by tdreyno** [comment]
yeah, this was a bug that got fixed last week. If you come to this ticket, simple get the latest gem.

**Comment by lwr** [comment]
that make me crazy too!!
very strange problem and ruby maybe just too hard to me.

I had found that this gem in `Gemfile.lock` maybe the problem source
```ruby
    padrino-helpers (0.13.2)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.2)
      tilt (>= 1.4.1, < 3)
```
After I change ` padrino-helpers` to version `0.13.1`, middleman successfully build
I dont know how it could happens

**Comment by aljaydavids** [comment]
Also had this problem, upgrading to middleman 4.1.0 fixed it for me
