### ISSUE TITLE
Rack Middleware "uninitialized constant" Error

### ISSUE THREAD

**Issue by oncomouse** [middleman/middleman#1929]
I'm having a problem using Rack middleware in Middleman 4.1 Whenever I load any middleware (and I've tried with rack-rewrite and rack-tidy), I get the following error (used rack-rewrite for the example, but I got the same error referencing `Middleman::Rack::Tidy` when using rack-tidy):

~~~ bash
bundler: failed to load command: middleman (/Users/apilsch/.rvm/gems/ruby-2.3.1/bin/middleman)
NameError: uninitialized constant Middleman::Rack::Rewrite
  /Users/apilsch/Projects/robotrhetor.io/config.rb:24:in `block in evaluate_configuration!'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:57:in `execute'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:58:in `instance_exec'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:58:in `block in execute'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:58:in `execute'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.9/lib/middleman-core/application.rb:305:in `initialize'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-cli-4.1.9/bin/middleman:51:in `new'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/gems/middleman-cli-4.1.9/bin/middleman:51:in `<top (required)>'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/bin/middleman:23:in `load'
  /Users/apilsch/.rvm/gems/ruby-2.3.1/bin/middleman:23:in `<top (required)>'
~~~

It looks like something is going on with namespacing in the config.rb file.

I'm using the following code for rack-rewrite to load font files from a bower package:

~~~ ruby
after_configuration do
	require 'rack/rewrite'
	use Rack::Rewrite do
	    rewrite %r{^\/fonts\/roboto\/(.*)}, File.join(File.join(Dir.pwd, "bower_components").gsub(/\/{0,1}source\//,'/'), "Materialize/fonts/roboto") + '/$1'
	end
end
~~~

I should also point out that the above configuration code was copied from a working middleman project that is still using v3.

**Comment by tdreyno** [comment]
You need to prefix top-level namespaces with `::`

So `::Rack::Rewrite` or `::Rack::Tidy`
