### ISSUE TITLE
Error intializing server on Middleman 4.1.9

### ISSUE THREAD

**Issue by josephgodwinkimani** [middleman/middleman#1940]
I get an error trying to intialize middleman server - from what I gather its that the middleman-cli is not bundled - the error stipulates that I add middleman-cli to Gemfile. I installed it manually and tried to add it to Gemfile and bundle it but gave an error. Here is the error:

```
C:\Bitnami\rubystack-2.2.5-3\projects>middleman init middlemanwebsite
         run  git clone --depth 1 https://github.com/middleman/middleman-templates-default.git C:/Users/jkimani/AppData/Local/Temp/d20160620-4080-1oe2emr from "."
Cloning into 'C:/Users/jkimani/AppData/Local/Temp/d20160620-4080-1oe2emr'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 22 (delta 0), reused 14 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.
Checking connectivity... done.
       exist
      create  .gitignore
      create  Gemfile
      create  config.rb
      create  source/images/middleman-logo.svg
      create  source/index.html.erb
      create  source/javascripts/all.js
      create  source/layouts/layout.erb
      create  source/stylesheets/_normalize.scss
      create  source/stylesheets/site.css.scss
Do you want to use Compass? yes
Do you want to use LiveReload? yes
      insert  Gemfile
      insert  Gemfile
      insert  config.rb
      insert  Gemfile
Do you want a Rack-compatible config.ru file? yes
      create  config.ru
         run  bundle install from "./middlemanwebsite"
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using thread_safe 0.3.5
Using wdm 0.1.1
Using bundler 1.12.5
Using tzinfo 1.2.2
Installing tzinfo-data 1.2016.5
Bundle complete! 2 Gemfile dependencies, 5 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

C:\Bitnami\rubystack-2.2.5-3\projects>cd middlemanwebsite

C:\Bitnami\rubystack-2.2.5-3\projects\middlemanwebsite>gem install middleman-cli
Successfully installed middleman-cli-4.1.9
Parsing documentation for middleman-cli-4.1.9
Installing ri documentation for middleman-cli-4.1.9
Done installing documentation for middleman-cli after 1 seconds
1 gem installed

C:\Bitnami\rubystack-2.2.5-3\projects\middlemanwebsite>bundle exec middleman server
C:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:322:in `block in replace_gem': middleman-cli is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
        from C:/Bitnami/rubystack-2.2.5-3/ruby/bin/middleman:22:in `<main>'

C:\Bitnami\rubystack-2.2.5-3\projects\middlemanwebsite>bundle install
Using thread_safe 0.3.5
Using wdm 0.1.1
Using bundler 1.12.5
Using tzinfo 1.2.2
Using tzinfo-data 1.2016.5
Bundle complete! 2 Gemfile dependencies, 5 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

C:\Bitnami\rubystack-2.2.5-3\projects\middlemanwebsite>bundle exec middleman server
C:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:322:in `block in replace_gem': middleman-cli is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
        from C:/Bitnami/rubystack-2.2.5-3/ruby/bin/middleman:22:in `<main>'

C:\Bitnami\rubystack-2.2.5-3\projects\middlemanwebsite>bundle exec middleman server
C:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.9/bin/middleman:3:in `require': cannot load such file -- middleman-core/profiling (LoadError)
        from C:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.9/bin/middleman:3:in `<top (required)>'
        from C:/Bitnami/rubystack-2.2.5-3/ruby/bin/middleman:23:in `load'
        from C:/Bitnami/rubystack-2.2.5-3/ruby/bin/middleman:23:in `<main>'

C:\Bitnami\rubystack-2.2.5-3\projects\middlemanwebsite>bundle show middleman-cli
Could not find gem 'middleman-cli'.
```

My project **Gemfile** looks like this:

```
# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
```

My project **Gemfile.lock** looks like this: 

```
GEM
  remote: https://rubygems.org/
  specs:
    middleman-cli (4.1.9)
      thor (>= 0.17.0, < 2.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    tzinfo-data (1.2016.5)
      tzinfo (>= 1.0.0)
    wdm (0.1.1)

PLATFORMS
  x86-mingw32

DEPENDENCIES
  middleman-cli
  tzinfo-data
  wdm (~> 0.1.0)

BUNDLED WITH
   1.12.5

```

**Comment by tdreyno** [comment]
There should be MM deps listed under `# Middleman Gems`. That's not good. You can add them manually, but the `init` command should have done it.
