### ISSUE TITLE
Middleman init not working

### ISSUE THREAD

**Issue by sebastiangraz** [middleman/middleman#1943]
Sorry for posting a common problem. In my case I havent been able to find out what is wrong, running middleman init gives me the following:

```
Sebastians-MacBook-Pro:middlemantest sebastiangraz$ middleman init
/Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/renderers/sass_functions.rb:114:in `<top (required)>': uninitialized constant SassC::Script (NameError)
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/renderers/sass.rb:34:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/extension_manager.rb:66:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/extension_manager.rb:66:in `activate'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:120:in `block in auto_activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:117:in `auto_activate'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/extension_manager.rb:28:in `auto_activate'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/extension_manager.rb:20:in `block (2 levels) in initialize'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:57:in `block in execute'
    from /Library/Ruby/Gems/2.0.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
    from /Library/Ruby/Gems/2.0.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:57:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
    from /Library/Ruby/Gems/2.0.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
    from /Library/Ruby/Gems/2.0.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.9/lib/middleman-core/application.rb:279:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-cli-4.1.9/bin/middleman:51:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/middleman-cli-4.1.9/bin/middleman:51:in `<top (required)>'
    from /usr/local/bin/middleman:22:in `load'
    from /usr/local/bin/middleman:22:in `<main>'

```

Running El Capitan (OS X 10.11.5 (15F34))

Using Sudo

Local gems: 

```
activesupport (4.2.6)
addressable (2.4.0)
backports (3.6.8)
bigdecimal (1.2.8)
bundler (1.12.5)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
compass-import-once (1.0.5)
concurrent-ruby (1.0.2)
contracts (0.13.0)
did_you_mean (1.0.0)
dotenv (2.1.1)
erubis (2.7.0)
execjs (2.7.0)
fast_blank (1.0.0)
fastimage (2.0.0)
ffi (1.9.10)
haml (4.0.7)
hamster (3.0.0)
hashie (3.4.4)
i18n (0.7.0)
io-console (0.4.5)
json (1.8.3)
kramdown (1.11.1)
listen (3.0.8)
memoist (0.14.0)
middleman (4.1.9)
middleman-cli (4.1.9)
middleman-core (4.1.9)
minitest (5.8.3)
net-telnet (0.1.1)
padrino-helpers (0.13.2)
padrino-support (0.13.2)
parallel (1.9.0)
power_assert (0.2.6)
psych (2.0.17)
rack (1.6.4)
rake (10.4.2)
rb-fsevent (0.9.7)
rb-inotify (0.9.7)
rdoc (4.2.1)
sass (3.4.22)
servolux (0.12.0)
test-unit (3.1.5)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
tzinfo (1.2.2)
uglifier (3.0.0)
```

**Comment by tdreyno** [comment]
Seems like MM is trying to boot up way too much during init. Let me look
