### ISSUE TITLE
Trying to run middleman from within Ubuntu Bash on Windows 10

### ISSUE THREAD

**Issue by OndrejKu** [middleman/middleman#1960]
I'm trying to run Middleman on Ubuntu 14.04 that is as a subsystem on Windows 10. 

The error I'm getting is this: 
`Errno::EINVAL: Invalid argument - getifaddrs` 

And here's the print of the screen: 

![image](https://cloud.githubusercontent.com/assets/9321195/16997544/500036ac-4e8c-11e6-8935-1ed7ed21614a.png)

I'm not sure if this is bug or if it's just because the Bash On Windows problem (since there's a lot of things that are happening here that aren't normal under "normal" Ubuntu. But if there's any solution to that I'd be grateful :)

**Comment by tdreyno** [comment]
Oh boy :) Happy for help and PRs on this one, but I use neither Ubuntu or Windows, so it's very unlikely I'll take a crack at this.

That said, I see you're on v3... Maybe try v4? This may be an issue in one of our dependencies that could have addressed it since v3.3.12

**Comment by OndrejKu** [comment]
If I'd do that I have dependency problem with middleman-livereload and middleman-vendor_bower which both depend on middleman-core ~>3.3. 

The error I'm getting is probably because of this bug here in the new Bash on Windows feature: https://github.com/Microsoft/BashOnWindows/issues/308

**Comment by tdreyno** [comment]
Livereload definitely supports v4

**Comment by OndrejKu** [comment]
Oh ok my bad. So next error after fixing dependencies: 

![image](https://cloud.githubusercontent.com/assets/9321195/17073409/103be6bc-5047-11e6-987d-5cd3afa315ec.png)

Looks like Reffils can't import Rails generators.

**Comment by cfabroni** [comment]
+1

**Comment by stevenosloan** [comment]
It looks like refills [requires rails](https://github.com/thoughtbot/refills/blob/master/lib/refills/import_generator.rb#L1), but doesn't include that in it's gemspec. If you don't already, you might try adding rails to your gemfile.

**Comment by aoozdemir** [comment]
I'm having this error trace.

```bash
 λ middleman serve
== The Middleman is loading
/home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:794:in `send': Invalid argument - sendto(2) for "ff02::fb" port 5353 (Errno::EINVAL)
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:794:in `send'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:673:in `request'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:529:in `block in fetch_resource'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:1097:in `block (3 levels) in resolv'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:1095:in `each'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:1095:in `block (2 levels) in resolv'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:1094:in `each'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:1094:in `block in resolv'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:1092:in `each'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:1092:in `resolv'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:520:in `fetch_resource'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:510:in `each_resource'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:464:in `each_name'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/2.4.0/resolv.rb:442:in `getnames'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/dns_resolver/basic_network_resolver.rb:23:in `getnames'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/dns_resolver.rb:48:in `block in names_for'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/dns_resolver.rb:47:in `each'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/dns_resolver.rb:47:in `names_for'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/preview_server/information.rb:112:in `resolve_me'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/preview_server/server_information.rb:54:in `information'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/preview_server/server_information.rb:119:in `bind_address'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/preview_server/server_information.rb:71:in `use'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/preview_server.rb:183:in `initialize_new_app'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/preview_server.rb:34:in `start'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/lib/middleman-cli/server.rb:53:in `server'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:40:in `block in register'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /home/ao/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:70:in `<top (required)>'
        from /home/ao/.rbenv/versions/2.4.1/bin/middleman:22:in `load'
        from /home/ao/.rbenv/versions/2.4.1/bin/middleman:22:in `<main>'
```
