### ISSUE TITLE
External pipeline fails to restart after editing config file

### ISSUE THREAD

**Issue by craigmdennis** [middleman/middleman#1977]
In my `development.rb` config file I have the following:

``` rb
activate :external_pipeline,
  name: :gulp,
  command: "npm run gulp",
  source: "./.tmp"
  latency: 1
```

Which triggers `gulp` when initially running `middleman serve`. When editing a helper or config file, the process is terminated and looks like it tries to call the external pipeline task but fails.

``` bash
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/craigmdennis/.nvm/versions/node/v5.6.0/bin/node" "/Users/craigmdennis/.nvm/versions/node/v5.6.0/bin/npm" "run" "gulp"
npm ERR! node v5.6.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! middleman-gulp-starter@1.4.1 gulp: `gulp`
npm ERR! Exit status 1
```

But it runs fine when initially calling `middleman serve`
- Ruby version: 2.3.0
- Middleman version: 4.1.1
- OS version:

**Comment by craigmdennis** [comment]
This is the contents of the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/craigmdennis/.nvm/versions/node/v5.6.0/bin/node',
1 verbose cli   '/Users/craigmdennis/.nvm/versions/node/v5.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'gulp' ]
2 info using npm@3.10.5
3 info using node@v5.6.0
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info lifecycle craigmdennis.com@10.0.1~pregulp: craigmdennis.com@10.0.1
6 silly lifecycle craigmdennis.com@10.0.1~pregulp: no script for pregulp, continuing
7 info lifecycle craigmdennis.com@10.0.1~gulp: craigmdennis.com@10.0.1
8 verbose lifecycle craigmdennis.com@10.0.1~gulp: unsafe-perm in lifecycle true
9 verbose lifecycle craigmdennis.com@10.0.1~gulp: PATH: /Users/craigmdennis/.nvm/versions/node/v5.6.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/craigmdennis/Sites/craigmdennis.com/node_modules/.bin:/Users/craigmdennis/.nvm/versions/node/v5.6.0/bin:/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin:/usr/local/var/rbenv/versions/2.3.0/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/craigmdennis/.nvm/versions/node/v5.6.0/bin:/usr/local/var/rbenv/shims:/usr/local/bin:/usr/local/bin/sublime:~/bin:/usr/local/mysql/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Users/craigmdennis/bin:/opt/local/lib/php/pear/bin:/opt/local/mysql/bin:/opt/local/apache2/bin:/opt/local/bin:/opt/local/sbin:/opt/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin
10 verbose lifecycle craigmdennis.com@10.0.1~gulp: CWD: /Users/craigmdennis/Sites/craigmdennis.com
11 silly lifecycle craigmdennis.com@10.0.1~gulp: Args: [ '-c', 'gulp' ]
12 silly lifecycle craigmdennis.com@10.0.1~gulp: Returned: code: 1  signal: null
13 info lifecycle craigmdennis.com@10.0.1~gulp: Failed to exec gulp script
14 verbose stack Error: craigmdennis.com@10.0.1 gulp: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/craigmdennis/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/craigmdennis/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid craigmdennis.com@10.0.1
16 verbose cwd /Users/craigmdennis/Sites/craigmdennis.com
17 error Darwin 15.6.0
18 error argv "/Users/craigmdennis/.nvm/versions/node/v5.6.0/bin/node" "/Users/craigmdennis/.nvm/versions/node/v5.6.0/bin/npm" "run" "gulp"
19 error node v5.6.0
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error craigmdennis.com@10.0.1 gulp: `gulp`
22 error Exit status 1
23 error Failed at the craigmdennis.com@10.0.1 gulp script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the craigmdennis.com package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs craigmdennis.com
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls craigmdennis.com
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by tdreyno** [comment]
Is it possible to start your gulp twice (like in 2 different terminals)? I'm wondering if the restart is not cleaning stopping the old gulp

**Comment by ryanhageman** [comment]
Is this still an issue?

**Comment by judewang** [comment]
#2353
