### ISSUE TITLE
Partials like _foo.sass.erb work in "server", but fail the "build"

### ISSUE THREAD

**Issue by GSI** [middleman/middleman#2007]
## Expected behavior and actual behavior

I have a file **source/stylesheets/partials/_variables.sass.erb** with this content:

    $langs: <%= app.extensions[:i18n].options.langs.join(' ') %>

In `middleman server` the file is processed from erb to sass, leaving the variable **langs** filled with the expected values. This variable can then be used as expected to refer to those languages in sass files.

`middleman build`, however, fails with this error:
`Sass::SyntaxError: File to import not found or unreadable: partials/variables.`

Here is the entire trace:

```
:image_optim is deprecated. Please use `:imageoptim` instead.
== Locales: de, en, fr, it (Default false)
bundler: failed to load command: middleman (~/.gem/ruby/2.1.8/bin/middleman)
Sass::SyntaxError: File to import not found or unreadable: partials/variables.
Load paths:
  /foobar/source/javascripts
  /foobar/source/stylesheets
  /foobar/source
  /foobar/source/stylesheets/new.css.sass:7
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/import_node.rb:67:in `rescue in import'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/import_node.rb:45:in `import'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/import_node.rb:28:in `imported_file'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/import_node.rb:37:in `css_import?'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:313:in `visit_import'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `visit'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:160:in `block in visit'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/stack.rb:79:in `block in with_base'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/stack.rb:115:in `with_frame'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/stack.rb:79:in `with_base'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:160:in `visit'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `map'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `visit_children'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:169:in `block in visit_children'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:181:in `with_environment'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:168:in `visit_children'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `block in visit'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:188:in `visit_root'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `visit'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:159:in `visit'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:8:in `visit'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/root_node.rb:36:in `css_tree'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/tree/root_node.rb:20:in `render'
  ~/.gem/ruby/2.1.8/gems/sass-3.4.22/lib/sass/engine.rb:281:in `render'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/sass_processor.rb:74:in `block in call'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/utils.rb:167:in `module_include'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/sass_processor.rb:73:in `call'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/sass_processor.rb:30:in `call'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `yield'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:23:in `block in call'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/utils.rb:196:in `dfs'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:24:in `call'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `yield'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/environment.rb:30:in `find_asset'
  ~/.gem/ruby/2.1.8/gems/sprockets-3.7.0/lib/sprockets/base.rb:92:in `[]'
  ~/.gem/ruby/2.1.8/gems/middleman-sprockets-4.0.0/lib/middleman-sprockets/resource.rb:37:in `block in sprockets_asset'
  ~/.gem/ruby/2.1.8/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-sprockets-4.0.0/lib/middleman-sprockets/resource.rb:36:in `sprockets_asset'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  ~/.gem/ruby/2.1.8/gems/middleman-sprockets-4.0.0/lib/middleman-sprockets/extension.rb:129:in `map'
  ~/.gem/ruby/2.1.8/gems/middleman-sprockets-4.0.0/lib/middleman-sprockets/extension.rb:129:in `linked_resources'
  ~/.gem/ruby/2.1.8/gems/middleman-sprockets-4.0.0/lib/middleman-sprockets/extension.rb:142:in `linked_resources!'
  ~/.gem/ruby/2.1.8/gems/middleman-sprockets-4.0.0/lib/middleman-sprockets/extension.rb:96:in `block in manipulate_resource_list'
  ~/.gem/ruby/2.1.8/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-sprockets-4.0.0/lib/middleman-sprockets/extension.rb:95:in `manipulate_resource_list'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'
  ~/.gem/ruby/2.1.8/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
  ~/.gem/ruby/2.1.8/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  ~/.gem/ruby/2.1.8/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  ~/.gem/ruby/2.1.8/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
  ~/.gem/ruby/2.1.8/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
  ~/.rubies/ruby-2.1.8/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  ~/.gem/ruby/2.1.8/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  ~/.gem/ruby/2.1.8/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  ~/.gem/ruby/2.1.8/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `execute'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  ~/.gem/ruby/2.1.8/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/application.rb:308:in `initialize'
  ~/.gem/ruby/2.1.8/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:63:in `new'
  ~/.gem/ruby/2.1.8/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:63:in `block in build'
  ~/.gem/ruby/2.1.8/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
  ~/.gem/ruby/2.1.8/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:62:in `build'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  ~/.gem/ruby/2.1.8/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  ~/.gem/ruby/2.1.8/gems/middleman-cli-4.1.10/bin/middleman:72:in `<top (required)>'
  ~/.gem/ruby/2.1.8/bin/middleman:23:in `load'
  ~/.gem/ruby/2.1.8/bin/middleman:23:in `<top (required)>'

```

## Additional information

- Ruby version: 2.1.8
- Middleman version: 4.1.10

**Comment by GSI** [comment]
Suspecting this might be a middleman-sprockets issue (fails in 4.0.0 as well as 4.1.0).

Also tried with Ruby 2.2.4 and MM 4.1.11;

**Comment by GSI** [comment]
Turns out I was wrong - `middleman server` doesn't find the file either.

Any way I can have the desired funtionality anyway? I mean getting the langs from config.rb to sass?

**Comment by vvasabi** [comment]
I could be wrong, but I don’t think you can import an erb from sass. You could try implementing a custom sass function that provides variables from config.rb. [See this repo for an example.](https://github.com/vvasabi/middleman-custom-sass-function)

**Comment by GSI** [comment]
The expected behaviour would be for sprockets to process the .sass.erb down to a .sass before the Sass engine even reads it.

At least that's my understanding of how chaining file extensions is supposed to work.
(compare to .html.erb, for example)

**Comment by vvasabi** [comment]
I suspect the problem comes from Sass engine’s behaviour, where it does its own file IO and bypasses the ERB engine, when it needs to import a file via the `@import` directive. You can, however, include a .sass.erb file in another one via Sprockets by using the `//=require` directive, but that won’t allow you to share variables between two sass files.

It is probably not impossible to enable ERB processing when the Sass engine needs to import a file, but code will need to be written to hook into the internals of the Sass engine. In the meantime, your best bet is probably to implement a custom sass function in Ruby.
