### ISSUE TITLE
Accents in data file raises ArgumentError

### ISSUE THREAD

**Issue by eemi** [middleman/middleman#2014]
## Expected behavior and actual behaviour
If a YML data file  has values with accents (i.e.: "asignación"), when launching middleman an error is raised. Data file is saved as UTF-8 (I checked and double checked!!).

**YML data file example**

```
igf_topes: "Los ingresos del grupo familiar deben encontrarse entre los topes mínimo y máximo vigentes, tanto el individual como el del grupo familiar."
```

**Error raised when booting up machine**

I'm using Docker with OSX as host.

```
web_1  | /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/util/data.rb:60:in 'match': invalid byte sequence in US-ASCII (ArgumentError)
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/util/data.rb:60:in 'parse'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/data.rb:108:in 'touch_file'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/data.rb:89:in 'each'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/data.rb:89:in 'update_files'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:366:in 'call'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:366:in 'block in run_callbacks'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in 'each'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in 'traverse_depth_first'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in 'each'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:359:in 'run_callbacks'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:349:in 'did_change'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in 'instance_exec'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in 'block in execute'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in 'each'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in 'traverse_depth_first'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in 'each'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in 'execute'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:28:in 'block in install_methods!'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources/source_watcher.rb:279:in 'update'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources/source_watcher.rb:204:in 'poll_once!'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:239:in 'block in poll_once!'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:239:in 'each'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:239:in 'reduce'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sources.rb:239:in 'poll_once!'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/file_watcher.rb:50:in 'before_configuration'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in 'instance_exec'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in 'block in execute'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in 'each'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in 'traverse_depth_first'
web_1  |  from /usr/local/bundle/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in 'each'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in 'execute'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in 'send_to'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in 'call_with'
web_1  |  from /usr/local/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in 'block in redefine_method'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:28:in 'block in install_methods!'
web_1  |  from /usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/application.rb:282:in 'initialise'
web_1  |  from /usr/local/bundle/gems/middleman-cli-4.1.10/bin/middleman:51:in 'new'
web_1  |  from /usr/local/bundle/gems/middleman-cli-4.1.10/bin/middleman:51:in '<top (required)>'
web_1  |  from /usr/local/bundle/bin/middleman:16:in 'load'
web_1  |  from /usr/local/bundle/bin/middleman:16:in '<main>'
web_1  | /usr/local/bundle/gems/middleman-breadcrumbs-0.4.1/lib/middleman-breadcrumbs/version.rb
web_1  | /usr/local/bundle/gems/middleman-breadcrumbs-0.4.1/lib/middleman-breadcrumbs/breadcrumbs.rb
middleman_web_1 exited with code 1
```

If the data file is emptied before booting up the machine, things go ok. Then I can add the content with accents to the YML file and everything will work ok.

## Additional information

- Ruby version: 2.2.0
- Middleman version: 4.1.10 (previously reported the non-existing version 4.1.19)
- OS version: Ubuntu / Docker (happens in OSX too)
- config.rb has "Encoding.default_external = Encoding::UTF_8"
- **I love Middleman**

**Comment by tdreyno** [comment]
That seems like a serious problem when trying to localize :(

The fact that it thinks it is `US-ASCII` seems like a warning flag.

That said, our tests are passing and our japanese-language documentation site is building correctly, so... maybe it's something we can troubleshoot.

Can you try checking out Ruby 2.3.x?

**Comment by eemi** [comment]
Tested 4 different scenarios (just in case), with the same results (ArgumentError)

- Ruby 2.2.0 & Middleman 4.1.10
- Ruby 2.2.0 & Middleman 4.1.12
- Ruby 2.3.0 & Middleman 4.1.10
- Ruby 2.3.0 & Middleman 4.1.12

 The weird thing is that I can *get stuff done* (accents won't stop me!) by following the trick of emptying the data files just before launching the server. So maybe there's one check that is 

I'm happy to help testing whatever is needed, it sucks a bit that my coding skills are a bit limited.

**Comment by tdreyno** [comment]
Can you send me a test case and I'll see if I can get the same error?

**Comment by eemi** [comment]
I don't know how to do it :( I searched around, but still I just don't get how to help you. I can share with you the actual iml file and how I'm calling it, that could help?

**Comment by eemi** [comment]
The problem was solve on Docker by setting the locales to UTF-8.

**Comment by eemi** [comment]
Just in case somebody else is interested, I added this to my Dockerfile

```
RUN apt-get clean && apt-get update
RUN apt-get install locales
RUN locale-gen en_US.UTF-8
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
```
