### ISSUE TITLE
Middleman fails whenever there is a .rb file present in sources directory

### ISSUE THREAD

**Issue by tuxmark5** [middleman/middleman#2015]
## Expected behavior and actual behavior
Launching middleman with 'middleman' or 'middleman build' causes middleman to crash if there is a .rb file present anywhere in the sources directory. 
I use middleman to host some .rb source files. 
It's currently even impossible to ignore those files, because middleman fails before even config is read.
This happens with a fresh installation.

```
/home/angel/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `require': cannot load such file -- opal (LoadError)
        from /home/angel/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `block in lazy_load'
        from /home/angel/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `each'
        from /home/angel/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `lazy_load'
        from /home/angel/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:216:in `lookup'
        from /home/angel/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:154:in `[]'
        from /home/angel/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt.rb:48:in `[]'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources/source_watcher.rb:336:in `strip_extensions'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources/source_watcher.rb:324:in `record_file_change'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources/source_watcher.rb:265:in `block in update'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources/source_watcher.rb:264:in `each'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources/source_watcher.rb:264:in `update'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources/source_watcher.rb:212:in `poll_once!'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources.rb:241:in `block in poll_once!'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources.rb:241:in `each'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources.rb:241:in `reduce'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/sources.rb:241:in `poll_once!'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/core_extensions/file_watcher.rb:47:in `before_configuration'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from /home/angel/.gem/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /home/angel/.gem/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /home/angel/.gem/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/callback_manager.rb:57:in `execute'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/angel/.gem/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-core-4.1.12/lib/middleman-core/application.rb:283:in `initialize'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-cli-4.1.12/bin/middleman:51:in `new'
        from /home/angel/.gem/ruby/2.3.0/gems/middleman-cli-4.1.12/bin/middleman:51:in `<top (required)>'
        from /home/angel/.gem/ruby/2.3.0/bin/middleman:23:in `load'
        from /home/angel/.gem/ruby/2.3.0/bin/middleman:23:in `<main>'
```

## Steps to reproduce the problem (from a clean middleman installation)
middleman build

## Additional information

- Ruby version: 2.3.1p112
- Middleman version: 
- OS version:

**Comment by tdreyno** [comment]
God damn Tilt 2 really shit the bed. Okay, I need to take some time and add much calmer "no please don't render this" error catching around their freak out code.

**Comment by paulmsmith** [comment]
I'm getting this issue: 

```
paulsmith@afmbp : ~/Sites/blog on master!
± bundle exec middleman server
bundler: failed to load command: middleman (/Users/paulsmith/.rbenv/versions/2.3.1/bin/middleman)
LoadError: cannot load such file -- opal
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `require'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `block in lazy_load'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `each'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `lazy_load'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:216:in `lookup'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:154:in `[]'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt.rb:48:in `[]'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources/source_watcher.rb:336:in `strip_extensions'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources/source_watcher.rb:324:in `record_file_change'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources/source_watcher.rb:265:in `block in update'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources/source_watcher.rb:264:in `each'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources/source_watcher.rb:264:in `update'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources/source_watcher.rb:212:in `poll_once!'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources.rb:241:in `block in poll_once!'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources.rb:241:in `each'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources.rb:241:in `reduce'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/sources.rb:241:in `poll_once!'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/core_extensions/file_watcher.rb:47:in `before_configuration'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/callback_manager.rb:57:in `execute'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/application.rb:283:in `initialize'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.14/bin/middleman:49:in `new'
  /Users/paulsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.14/bin/middleman:49:in `<top (required)>'
  /Users/paulsmith/.rbenv/versions/2.3.1/bin/middleman:23:in `load'
  /Users/paulsmith/.rbenv/versions/2.3.1/bin/middleman:23:in `<top (required)>'
```

**Comment by chufucious** [comment]
Really weird, I get this same error too - happened suddenly...

**Comment by betabong** [comment]
Right now we have no way to avoid Tilt from throwing an error when it finds "known file extensions" in the source directory. Let's say I want to compile .coffee or .es6 files with Gulp (thanks to external pipeline), I'd still have to add the coffeescript and babel libraries to the Gemfile. We just somehow need to be able to work around Tilt's default mappings.

**Comment by thechile** [comment]
Arghhhhhh this was driving me mad !!!! created debug .rb file in source and forgot about it. Then this madness started. Reinstalled ruby, gems etc.. Thank goodness i checked here.

**Comment by MelSumner** [comment]
Hi! I'm getting this error today. If anyone comes up with a solution, I'd love to hear about it!

**Comment by NealJMD** [comment]
Yup, just got this error today too.

**Comment by toadle** [comment]
👍 

I got this too. My scenario: Just typing `middleman init <new project>` in my regular 'Ruby-Projects'-directory. Which always has a `.rb`-file somehwere down there.

Also went through the whole reinstall-`rbenv`-cycle already. Thank god I found this post now.

**Comment by wkoszek** [comment]
I wish I googled this bug report before starting debugging. Would have no f^&*( idea about this. Scenario: under `source/newsletter` I've made myself `export.rb` and `summarize_month.rb` and suddenly started to get this error message.

**Comment by inuritdino** [comment]
Just added `middleman-search` gem and `bundle`-d. After that, the same error... Everything is down! How to make *anything* up?

**Comment by inuritdino** [comment]
My error was:
```/var/lib/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:243:in `require' : cannot load such file -- org-ruby (LoadError)```
Looking closely, I found out that `tilt` is sort of templating modes handler, hence the `org-ruby` problem (org mode for Emacs). After installation of `org-ruby` everything is up again.
Sorry! (I am new to Ruby, however, I believe the installation of the `require`-d packages must be handled automatically by a package manager).
All the best!

**Comment by takeit** [comment]
Adding a line:

```
gem 'opal'
```

to `Gemfile` and running `bundle install` command solved the issue for me.

**Comment by nancycarroll** [comment]
Yes.  @takeit your solution worked for me also.  Thank you.

**Comment by unRARed** [comment]
Ran into this same issue today. Adding `gem 'opal'` gets past the first error, but a new one is thrown: `uninitialized constant Opal::Processor (NameError)`

**Comment by caseyscarborough** [comment]
Specifying version `0.10.6` in the `Gemfile` resolved the `uninitialized constant Opal::Processor` error for me:

```ruby
gem 'opal', '~> 0.10.6'
```
