### ISSUE TITLE
4.2.0: "syntax error, unexpected keyword_do_block, expecting '}' (SyntaxError)" on run

### ISSUE THREAD

**Issue by xeraa** [middleman/middleman#2028]
## Expected behavior and actual behavior

Expecting Middleman to start the server, but it fails:

```
$ bundle exec middleman
bundler: failed to load command: middleman (/usr/local/bin/middleman)
SyntaxError: /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:194: syntax error, unexpected keyword_do_block, expecting '}'
      layout: proc do |file, app|
                     ^
/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:194: syntax error, unexpected '|', expecting '='
   layout: proc do |file, app|
                              ^
/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:197: syntax error, unexpected '}', expecting keyword_end
    }, 'Callbacks that can exclude 
     ^
/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:460: syntax error, unexpected keyword_end, expecting end-of-input
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:4:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:4:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core.rb:13:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core.rb:13:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-4.2.0/lib/middleman.rb:1:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-4.2.0/lib/middleman.rb:1:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `block in require'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler.rb:106:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.0/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
  /usr/local/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.0/bin/middleman:10:in `<top (required)>'
  /usr/local/bin/middleman:22:in `load'
  /usr/local/bin/middleman:22:in `<top (required)>'
```

## Steps to reproduce the problem (from a clean middleman installation)

Try to run the project with any project or see the Travis build for 4.2.0 showing the same error: https://travis-ci.org/middleman/middleman/jobs/186502846

## Additional information

- Ruby version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
- Middleman version: 4.2.0
- OS version: macOS 10.12.2

**Comment by tdreyno** [comment]
@xeraa is this only Ruby 2.4.0?

**Comment by xeraa** [comment]
@tdreyno haven't tried it locally, but according to Travis https://travis-ci.org/middleman/middleman/builds/186502845:

* 2.4 has a syntax error (see above)
* 2.3.1 has one failing scenario (`cucumber features/liquid.feature:3 # Scenario: Rendering liquid`)
* 2.2.4 has two failing scenarios (`cucumber features/i18n_link_to.feature:146 # Scenario: url_for is i18n aware` & `cucumber features/liquid.feature:3 # Scenario: Rendering liquid`)

So I'd say yes, only on 2.4.0.

**Comment by klittlepage** [comment]
This is a bug in ruby 2.4.0: https://bugs.ruby-lang.org/issues/13073. It was already patched so hopefully they'll make a point release soon.

**Comment by awicaksi** [comment]
Upgrading to middleman 4.2.1 (and removing Gemfile.lock) fix the problem on my env.

env:
- ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
- macOS Sierra (10.12.2)

**Comment by danielbayerlein** [comment]
Issue can be closed. Works with middleman 4.2.1 🎉
