### ISSUE TITLE
Issues with Fixnum page_id's on 4.2

### ISSUE THREAD

**Issue by kennethkalmer** [middleman/middleman#2032]
I'm trying to upgrade [kennethkalmer/opensourcery.co.za](https://github.com/kennethkalmer/opensourcery.co.za) to 4.2.0 and having some issues along the way.

The blocker for me now is that numeric (Fixnum) `id` values in the frontmatter are blowing up like the stacktrace at the end of the issue.

I've tried renaming the [offending files](https://github.com/kennethkalmer/opensourcery.co.za/blob/master/source/2005-02-06-introduction-to-open-sourcery.md) to be ".html.markdown" but no change.

Upon inspecting the repo I found the _queryable-app_ fixture site that has numeric _id_ values in the frontmatter, but I can see the last time it was used in a test was prior to 1e43784cc2fa6585f0c6ce7265bd54156b00aeaa when the tests got removed.

I'm more than willing to make a pull request, but need some help on taming this beast.

The easy fix would be to add a missing [`to_s` to store.rb:252](https://github.com/middleman/middleman/blob/7c968b9572923fd0f7fb176ca8e52a91727adf84/middleman-core/lib/middleman-core/sitemap/store.rb#L252), but I fear that is only a bandaid...

```
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:252:in `block (5 levels) in ensure_resource_list_updated!': undefined method `to_sym' for 3:Fixnum (NoMethodError)
Did you mean?  to_s
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:251:in `each'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:251:in `block (4 levels) in ensure_resource_list_updated!'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:309:in `initialize'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/preview_server.rb:144:in `new'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/preview_server.rb:144:in `initialize_new_app'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/preview_server.rb:34:in `start'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/lib/middleman-cli/server.rb:53:in `server'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:40:in `block in register'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/bin/middleman:70:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.3.3/bin/middleman:22:in `load'
	from /usr/local/opt/rbenv/versions/2.3.3/bin/middleman:22:in `<main>'
```

## Additional information

- Ruby version: 2.3.3
- Middleman version: 4.2.0 
- OS version: macos sierra

**Comment by tdreyno** [comment]
It's gross, but I think `page_id.to_s.to_sym` would be the safest change. That was the data structure doesn't change. I looked, it seems like Fixnum used to have `to_sym`, but it got removed at some point. Probably during all the Symbol changes in Ruby 2.3

**Comment by kennethkalmer** [comment]
@tdreyno I opened #2033 for this one.
