### ISSUE TITLE
Failing to compile source because of SVG

### ISSUE THREAD

**Issue by rniller** [middleman/middleman#2035]
Ran into this issue this evening. Tried finding the source of the failure and routed it to the /images directory in my source. If I save an svg to that directory and try to compile the source, I receive this error. If I remove the svg and save any other file format, the source compiles.
```
$ bundler exec middleman build
bundler: failed to load command: middleman (/usr/local/bin/middleman)
ArgumentError: invalid byte sequence in UTF-8
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util/data.rb:60:in `match'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util/data.rb:60:in `parse'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/core_extensions/front_matter.rb:79:in `data'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/core_extensions/front_matter.rb:41:in `block in manipulate_resource_list'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/core_extensions/front_matter.rb:36:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/core_extensions/front_matter.rb:36:in `manipulate_resource_list'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
  /usr/local/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /usr/local/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /usr/local/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /usr/local/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:309:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/lib/middleman-cli/build.rb:63:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/lib/middleman-cli/build.rb:63:in `block in build'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/lib/middleman-cli/build.rb:62:in `build'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:40:in `block in register'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/bin/middleman:70:in `<top (required)>'
  /usr/local/bin/middleman:22:in `load'
  /usr/local/bin/middleman:22:in `<top (required)>'
```
**Update 1**
I dragged some old SVGs into that folder and compiled the source. That worked perfectly. I also attempeted to save a new SVG file from Illustrator and Sketch, to that folder. That would not allow me to compile the source.

Anyone else experiencing this issue?

**Update 2**
I've been keeping my project on a volume, directly connected to my device. This could be the issue. Remade project outside of the volume and compiled just fine. This issue can be marked as resolved.

**Comment by tdreyno** [comment]
Something about the file system on that volume is claiming that the contents of the file are not UTF-8. Not sure if that helps.
