### ISSUE TITLE
`--data-dir` option does not work with absolute paths

### ISSUE THREAD

**Issue by preist** [middleman/middleman#2042]
## Expected behavior and actual behavior
When running `middleman build --data-dir=/absolute/path` data does not get loaded from the given directory. However if you run `middleman build --data-dir=../relative/path` it works as expected.

## Steps to reproduce the problem (from a clean middleman installation)
1. Create a new directory `mkdir data2`
2. Create a new file called `people.json` with the following content:
```JSON
{
  "friends": [
    "Tom",
    "Dick",
    "Harry"
  ]
}
```
3. Add this to the main view file `index.html.ebr`:
```ERB
<% data.people.friends.each do |friend| %>
  <%= friend %>
<% end %>
```

4. Running `middleman build --data-dir=./data2 --verbose` should work fine.

5. Running `middleman build --data-dir=/absolute/path/to/project/data2 --verbose` fails with the following output:

```TEXT
       ...
       error  build/index.html
undefined method `people' for #<Middleman::CoreExtensions::Data::DataStore:0x007f968a867950>
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/core_extensions/data.rb:178:in `method_missing'
/Users/<hidden>/middleman-project/source/index.html.erb:1:in `block in singleton class'
/Users/<hidden>/middleman-project/source/index.html.erb:-8:in `instance_eval'
/Users/<hidden>/middleman-project/source/index.html.erb:-8:in `singleton class'
/Users/<hidden>/middleman-project/source/index.html.erb:-10:in `__tilt_70142277138980'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/file_renderer.rb:79:in `render'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/template_renderer.rb:184:in `_render_with_all_renderers'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/template_renderer.rb:147:in `block in render'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/template_renderer.rb:146:in `render'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/resource.rb:154:in `render'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/rack.rb:112:in `process_request'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/rack.rb:66:in `block in call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/rack.rb:65:in `catch'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/rack.rb:65:in `call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/core_extensions/inline_url_rewriter.rb:74:in `call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/mock.rb:74:in `request'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/mock.rb:56:in `get'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/builder.rb:232:in `block in output_resource'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/builder.rb:225:in `output_resource'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:462:in `call_with_index'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:433:in `process_incoming_jobs'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:415:in `block in worker'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:406:in `fork'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:406:in `worker'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:397:in `block in create_workers'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:396:in `each'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:396:in `each_with_index'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:396:in `create_workers'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:338:in `work_in_processes'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/parallel-1.10.0/lib/parallel.rb:252:in `map'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/builder.rb:137:in `output_resources'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/builder.rb:131:in `output_files'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/builder.rb:71:in `block in run!'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/builder.rb:70:in `run!'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-cli-4.2.0/lib/middleman-cli/build.rb:80:in `block in build'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-cli-4.2.0/lib/middleman-cli/build.rb:79:in `build'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:40:in `block in register'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/gems/middleman-cli-4.2.0/bin/middleman:70:in `<top (required)>'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/bin/middleman:22:in `load'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/bin/middleman:22:in `<main>'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/<hidden>/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
There were errors during this build
```

## Additional information

- Ruby version: *ruby 2.3.3p222 [x86_64-darwin14]*
- Middleman version: *4.2.0*
- OS version: *macOS Sierra Version 10.12.2*

**Comment by preist** [comment]
Bump! 🤔

**Comment by tdreyno** [comment]
Yeah, looks like it's hard coded to be relative:

```
        @watcher = app.files.watch :data,
                                   path: File.join(app.root, dir),
                                   only: DATA_FILE_MATCHER
```

**Comment by tdreyno** [comment]
Okay, made a commit that might help this. Try pointing your Gemfile at Github master and see if it helps.

**Comment by preist** [comment]
@tdreyno Great! And thanks for looking into this.
