### ISSUE TITLE
Build error using liquid

### ISSUE THREAD

**Issue by andrezimpel** [middleman/middleman#2083]
I'm using middleman 4.0 with the liquid template engine. Running the middleman server everything is fine and I get no errors. As soon as I want to build the website I get this error:

`Template local 'data' tried to overwrite an existing context value. Please rename the key when passing to 'locals'`.

To be honest I don't know where the error could be since I'm using everything as it shipped, so no extra config except the `set :liquid, :layout_engine => :liquid` in the config.rb. I only got a index.html.liquid file with some includes.

I hope somebody can help me out on this one. Thank you!

**Comment by iwarner** [comment]
@tdreyno @andrezimpel 

Verified this.

Seems a raw liquid usage is producing this error

http://www.rubydoc.info/github/middleman/middleman/Middleman/Renderers/Liquid

```
def manipulate_resource_list(resources)
  return resources unless app.extensions[:data]

  resources.each do |resource|
    next if resource.file_descriptor.nil?
    next unless resource.file_descriptor[:full_path].to_s =~ %r{\.liquid$}

    # Convert data object into a hash for liquid
    resource.add_metadata locals: {
      data: stringify_recursive(app.extensions[:data].data_store.to_h)
    }
  end
end
```

data is reference here

I have tested with and without the data folder and its producing this issue.

**Comment by iwarner** [comment]
@tdreyno 

Just looking into liquid more, definite issue here I think, if you want to include partials from another directory - it will fail

Should be an easy fix, but just wondered if you have some magic for this.

```
# File 'middleman-core/lib/middleman-core/renderers/liquid.rb', line 14

def read_template_file(template_path)
  file = app.files.find(:source, "_#{template_path}.liquid")
  raise ::Liquid::FileSystemError, "No such template '#{template_path}'" unless file
  file.read
end
```

**Comment by zofrex** [comment]
I have run into this and can confirm it happens out of the box.

### Steps to reproduce:

* `middleman init`
* Add 'liquid' to Gemfile and `bundle install`
* Rename `source/index.html.erb` to `source/index.html.liquid`
* `middleman build`

Produces the error:

<details>
<summary>
uncaught throw "Template local `data` tried to overwrite an existing context value. Please rename the key when passing to `locals`"</summary>

```
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/template_renderer.rb:140:in `throw'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/template_renderer.rb:140:in `block in render'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/template_renderer.rb:134:in `each'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/template_renderer.rb:134:in `render'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/sitemap/resource.rb:154:in `render'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/rack.rb:112:in `process_request'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/rack.rb:66:in `block in call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/rack.rb:65:in `catch'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/rack.rb:65:in `call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-autoprefixer-2.10.1/lib/middleman-autoprefixer/extension.rb:55:in `call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/mock.rb:84:in `request'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/mock.rb:57:in `get'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/builder.rb:232:in `block in output_resource'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:170:in `instrument'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/util.rb:21:in `instrument'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/builder.rb:225:in `output_resource'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:508:in `call_with_index'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:472:in `process_incoming_jobs'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:454:in `block in worker'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:445:in `fork'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:445:in `worker'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:436:in `block in create_workers'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `each'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `each_with== Finishing Request: javascripts/site.js (0.0s)
_index'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `create_workers'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:374:in `work_in_processes'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:278:in `map'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/builder.rb:137:in `output_resources'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/builder.rb:131:in `output_files'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/builder.rb:71:in `block in run!'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:170:in `instrument'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/util.rb:21:in `instrument'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/builder.rb:70:in `run!'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-cli-4.3.8/lib/middleman-cli/build.rb:84:in `block in build'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:170:in `instrument'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.8/lib/middleman-core/util.rb:21:in `instrument'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-cli-4.3.8/lib/middleman-cli/build.rb:83:in `build'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:40:in `block in register'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/middleman-cli-4.3.8/bin/middleman:70:in `<top (required)>'
/Users/zofrex/.rbenv/versions/2.7.1/bin/middleman:23:in `load'
/Users/zofrex/.rbenv/versions/2.7.1/bin/middleman:23:in `<top (required)>'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:476:in `exec'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/zofrex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/Users/zofrex/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/zofrex/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
```
</details>

**Comment by tdreyno** [comment]
Pushing v4.3.9 out. This was already fixed on the main branch, but not the 4.x series

**Comment by zofrex** [comment]
Wow, that's a fast fix. Thank you!
