### ISSUE TITLE
Livereload broken on master

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman#2142]
This commit broke Livereload plugin: 936d19cbb3567835fffc4e03abd32370167d688e

```
C:\workspace>bundle exec middleman server
ansi: 'gem install win32console' to use color on Windows
yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.61s.
== The Middleman is loading
yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.60s.
== Executing: `yarn run server`
== External: yarn run v1.3.2
== External: $ node ./node_modules/webpack/bin/webpack.js --env=dev --watch -d --progress --color
 10% building modules 2/2 modules 0 active== External: Webpack is watching the f 10% building modules 3/4 modules 1 active ...ce\ts_home\webpack\javascripts\app. 11% building modules 10/13 modules 3 active ...\node_modules\style-loader\fixUrls.jsC:/ruby24/lib/ruby/gems/2.4.0/gems/middleman-livereload-3.4.6/lib/middleman-livereload/extension_3_1.rb:45:in `block in initialize': undefined local variable or method `files' for #<Middleman::LiveReloadExtension:0x0000000ad99bd0> (NameError)
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:78:in `block in call_with'
        from C:/ruby24/lib/ruby/gems/2.4.0/bundler/gems/middleman-79c39b5d880a/middleman-core/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from C:/ruby24/lib/ruby/gems/2.4.0/bundler/gems/middleman-79c39b5d880a/middleman-core/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from C:/ruby24/lib/ruby/gems/2.4.0/bundler/gems/middleman-79c39b5d880a/middleman-core/lib/middleman-core/callback_manager.rb:57:in `execute'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
```

**Comment by johnnyshields** [comment]
@tdreyno this is still happening and needs to be fixed before 4.3.x can be released.

**Comment by johnnyshields** [comment]
@tdreyno ?

**Comment by tjdo** [comment]
Confirmed, same behavior

**Comment by Bramanga** [comment]
Same here 👍

**Comment by pschfr** [comment]
Also happening here.

**Comment by dtflowers** [comment]
In the process of updating a middlman project from 3.4 to 4.3 and am experiencing this exact issue with livereload.   Apparently still broken?

**Comment by tdreyno** [comment]
I've personally never used this feature, but someone else was maintaining it. You might submit this over at that repo: https://github.com/middleman/middleman-livereload
