### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by mbajur** [middleman/middleman#2146]
## Expected behavior and actual behavior

Middleman should start

## Steps to reproduce the problem (from a clean middleman installation)

That's not that easy to reproduce it as my use case is pretty special. But here is what's going one: One of my clients wants to use middleman as a front-end for wordpress backend exposed using REST api. I'm using a pretty basic rake task to fetch all the posts from the backend and generate a blog posts on the middleman side. However, it seems that there are some illegal characters somewhere in these posts and middleman can't handle them. I also can't track which file is causing the issue as there are about 700 of them. 

Full error backtrace:
https://gist.github.com/mbajur/2ca655da9addb45d980943559bc8f644

The backtrace is also not very helpfull as it can't say which file is causing me a trouble.

## Additional information

- Ruby version: 2.5.0
- Middleman version: 4.2.1
- OS version: macOS 10.12.6

**Comment by BerkhanBerkdemir** [comment]
Did you solve that problem, @mbajur?

**Comment by frystpingvin** [comment]
@BerkhanBerkdemir do you have a similar problem?

I seem to be having a similar problem when running any middleman command.

```
/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/util/data.rb:60:in `match': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/util/data.rb:60:in `parse'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions/data.rb:111:in `touch_file'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions/data.rb:89:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions/data.rb:89:in `update_files'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:368:in `block in run_callbacks'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:361:in `run_callbacks'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:351:in `did_change'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `execute'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources/source_watcher.rb:288:in `update'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources/source_watcher.rb:212:in `poll_once!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:241:in `block in poll_once!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:241:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:241:in `reduce'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:241:in `poll_once!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions/file_watcher.rb:47:in `before_configuration'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /usr/local/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `execute'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:283:in `initialize'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `new'
        from /usr/local/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `<top (required)>'
        from /usr/local/bin/middleman:22:in `load'
        from /usr/local/bin/middleman:22:in `<main>'
```

**Comment by BerkhanBerkdemir** [comment]
Hello @mbajur and @frystpingvin 

I'm using Turkish and English in one [blog](https://blog.berkhanberkdemir.com). I haven't seen this error yet. Could you share with us what you tried.

Thank you.

**Comment by frystpingvin** [comment]
@mbajur My problem occurred when I used the integrated terminal in VSCode. When I used standard Mac terminal the problem did not occurred.

Try using the Mac Terminal if you use VSCode.

**Comment by foureyesup** [comment]
I'm having the same issue with the data file (I'm importing files from Prismic) using Mac Terminal :(

**Comment by leighmcculloch** [comment]
I'm also seeing the same thing with v4.2.1 of middleman, ruby v2.6.0. It works fine on my terminal, but then on Google Cloud Build inside the `ruby:2.6.0` image I see this exact same error and stack trace.

**Comment by tdreyno** [comment]
@leighmcculloch If you have a chance, can you replicate this in a local copy of that docker image? I find it odd that the encoding would change, but maybe something about the Cloud Build checkout from git is different.

**Comment by leighmcculloch** [comment]
From what I've managed to gleam is that the ruby image picks up the locale of the underlying system the container is running in. I'm guessing for Google Cloud Build this is US-ASCII by default. I tried to change that by using env vars and for whatever reason it wasn't working. I ended up working around it by removing the characters from my files that were beyond ASCII.

**Comment by mbajur** [comment]
Not sure if that's important but i'm an author of this issue so you all probably deserve any feedback from me - it was like a year ago but i finally dropped the middleman and moved on to some other tool without figuring out what needs to be done to fix this + i don't need this anymore.

I'm still using middleman for other projects but this one is not in my hands anymore so i can't provide any valuable feedback in here.

Thanks fo all the replies,
Cheers!

**Comment by leighmcculloch** [comment]
This issue might not be worth keeping open. Looking around I see lots of other ruby projects with similar issues opened. Given that my project works in one locale and then not in another environment I'm going to take a guess it's environmental.

The reason the problem showed up for me was because the middleman is using regex to find frontmatter at the top of HTML and YAML files, and ruby's regex can't compare strings of different encodings. So it might be possible to find some way around that and to rewrite the code that does the regex match to not use regex, or to normalize the files as they are imported, but given that ASCII has such a small character space we're likely to just replace the existing error with a new error saying a file can't be re-encoded.

**Comment by tdreyno** [comment]
Middleman existed over the Ruby 1.x-2.x gap so there's tons of random code messing with encodings. Could even be doing more harm than good these days.

I think if I can SSH into a broken build I could diagnose it. I might end up using Cloud Build myself this year at work, so it might be worthwhile.

**Comment by noraj** [comment]
fix locale did it for me, see https://github.com/fastlane/fastlane/issues/227

**Comment by andradei** [comment]
I tried using the locale solution mentioned by @noraj in a docker image:

```dockerfile
FROM ruby:2.6.1

WORKDIR /app
EXPOSE 4567

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

COPY . .

RUN apt update \
  && apt upgrade -y \
  && bundle install

RUN bundle exec middleman build

CMD middleman server
```

But without success.

**Comment by andradei** [comment]
My solution was explained right there at the official Ruby Docker image... amazing what reading the entire documentation does.

It is in the "Encoding" section of
https://hub.docker.com/_/ruby

**Comment by oatw** [comment]
I'm use middleman 4.3.5 with this gitlab-ci configuration and it works well. 

**The key is `export LANG=C.UTF-8`**.
Hope this helps.

```yml
image: ruby:2.6.3
cache:
  paths:
    - vendor
pages:
  stage: deploy
  script:
    - export LANG=C.UTF-8
    - apt-get update -yqqq
    - apt-get install -y nodejs
    - gem install bundler -v 2.1.1
    - bundle install --path vendor
    - bundle exec middleman build  --verbose
  artifacts:
    paths:
      - public
  only:
    - master
```

**Comment by shivabhusal** [comment]
This worked for me as suggested by @oatw 

```yml
# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: ruby:2.6.3

cache:
  paths:
    - vendor

test:
  script:
    - apt-get update -yqqq
    - apt-get install -y nodejs
    - bundle install --path vendor
    - bundle exec middleman build
  except:
    - master

pages:
  script:
    - export LANG=C.UTF-8
    - apt-get update -yqqq
    - apt-get install -y nodejs
    - gem install bundler
    - bundle install --path vendor
    - bundle exec middleman build  --verbose
  artifacts:
    paths:
      - public
  only:
    - master

```

**Comment by logemann** [comment]
Getting same error but local without any docker image stuff. I really wonder what lousy Stacktrace this is... you really dont know what middleman is trying to parse.
```

         3: from /Library/Ruby/Gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
         2: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/core_extensions/front_matter.rb:79:in `data'
         1: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/util/data.rb:60:in `parse'
/Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/util/data.rb:60:in `match': invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by noraj** [comment]
stale bots...

**Comment by noraj** [comment]
unstale

**Comment by noraj** [comment]
unstale

**Comment by noraj** [comment]
unstale

**Comment by tdreyno** [comment]
@noraj is the above `export LANG=C.UTF-8` solution not applicable to you?

**Comment by noraj** [comment]
> fix locale did it for me, see [fastlane/fastlane#227](https://github.com/fastlane/fastlane/issues/227)

@tdreyno Yes it was. Seems that everyone else have solve this. The issue can be closed I guess.
