### ISSUE TITLE
middleman init error on windows10

### ISSUE THREAD

**Issue by renard-david** [middleman/middleman#2281]
## Expected behavior and actual behavior
Instead of having successfully middleman init , the command middleman init block on the wdm package installation

## Steps to reproduce the problem (from a clean middleman installation)
1.Download and install of Ruby installer for windows 64bit  (rubyinstaller-devkit-2.6.3-1-x64.exe)

2. Download and install of RubyGem (rubygems-3.0.4.zip)
gem install rubygems-update =>ok
update_rubygems => ok

3. Install Middleman 4.3.4 on windows 10
gem install middleman =>ok

4. Middleman init => Error:
```
_C:\Ruby26-x64\bin>middleman init
         run  git clone --depth 1 https://github.com/middleman/middleman-templates-default.git C:/Users/renard/AppData/Local/Temp/d20190628-16772-cql2sk from "."
Cloning into 'C:/Users/renard/AppData/Local/Temp/d20190628-16772-cql2sk'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 19 (delta 0), reused 16 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), done.
       exist
      create  .gitignore
      create  Gemfile
      create  config.rb
      create  source/images/.keep
      create  source/index.html.erb
      create  source/javascripts/site.js
      create  source/layouts/layout.erb
      create  source/stylesheets/site.css.scss
         run  bundle install from "."
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for x64-mingw32 but the dependency is only for x86-mswin32, x86-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 java`.
The dependency wdm (~> 0.1) will be unused by any of the platforms Bundler is installing for. Bundler is installing for x64-mingw32 but the dependency is only for x86-mswin32, x86-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Unable to find a spec satisfying tzinfo-data (>= 0) in the set. Perhaps the
lockfile is corrupted?_
```
5. Debug unsuccessfull by trying to install separately wdm-0.1.1:
gem install wdm -v '0.1.1' --source 'https://rubygems.org/' 
=> ok but same error on middleman init

## Additional information

- Ruby version: 2.6.3-1
- Middleman version: 4.3.4
- OS version: windows 10 pro 64bit with java 32 jdk (jdk1.8.0_171)
-RubyGem 3.0.4

**Comment by tdreyno** [comment]
Hmm, can you open the `Gemfile` and add `x64-mingw32` to the list of "windows" platforms for tzinfo-data and wdm?

**Comment by renard-david** [comment]
Hello Thomas,
thanks for the reply. I opened the file named "gemfile" in C:\Ruby26-x64\bin\ and modify as you indicated me:
```
source 'https://rubygems.org'
gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]

```
and also send 2 commands directly:
gem install 'tzinfo-data' --platform=mingw --platform=mswin --platform=x64_mingw
=> ok
gem install 'wdm' --platform=mingw --platform=mswin --platform=x64_mingw
=> ok
gem cleanup
=> ok
and now the middleman init command seems to work fine:
```
C:\Ruby26-x64\bin>middleman init
         run  git clone --depth 1 https://github.com/middleman/middleman-templates-default.git C:/Users/renard/AppData/Local/Temp/d20190701-29288-1xp8sou from "."
Cloning into 'C:/Users/renard/AppData/Local/Temp/d20190701-29288-1xp8sou'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 19 (delta 0), reused 16 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), done.
       exist
   identical  .gitignore
    conflict  Gemfile
Overwrite C:/Ruby26-x64/bin/Gemfile? (enter "h" for help) [Ynaqdhm] n
        skip  Gemfile
   identical  config.rb
   identical  source/images/.keep
   identical  source/index.html.erb
   identical  source/javascripts/site.js
   identical  source/layouts/layout.erb
   identical  source/stylesheets/site.css.scss
         run  bundle install from "."
Using rake 12.3.2
Using concurrent-ruby 1.1.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.0.7.2
Using public_suffix 3.1.1
Using addressable 2.6.0
Using execjs 2.7.0
Using autoprefixer-rails 9.6.0
Using backports 3.15.0
Using bundler 1.17.3
Using coffee-script-source 1.12.2
Using coffee-script 2.4.1
Using contracts 0.13.0
Using dotenv 2.7.4
Using erubis 2.7.0
Using fast_blank 1.0.0
Using fastimage 2.1.5
Using ffi 1.11.1 (x64-mingw32)
Using temple 0.8.1
Using tilt 2.0.9
Using haml 5.1.1
Using hamster 3.0.0
Using hashie 3.6.0
Using kramdown 1.17.0
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using listen 3.0.8
Using memoist 0.16.0
Using thor 0.20.3
Using middleman-cli 4.3.4
Using padrino-support 0.13.3.4
Using padrino-helpers 0.13.3.4
Using parallel 1.17.0
Using rack 2.0.7
Using sassc 2.0.1
Using servolux 0.13.0
Using uglifier 3.2.0
Using middleman-core 4.3.4
Using middleman 4.3.4
Using middleman-autoprefixer 2.10.1
Using tzinfo-data 1.2019.1
Using wdm 0.1.1
Bundle complete! 4 Gemfile dependencies, 45 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
C:\Ruby26-x64\bin>
```

It does not ask for reinstalling wdm and  tzinfo-data . so i think the "middleman init problem" is fixed.
-----
But i used it in allready defined project, which someone gave to me, it says:
```
D:\DEV\StreamWorkshop_12.1\StreamWorkshopInstaller\src\Documentation>C:\Ruby26-x64\bin\ruby.exe "D:\DEV\StreamWorkshop_12.1\StreamWorkshopInstaller\src\Documentation\middleman"
Traceback (most recent call last):
        5: from D:/DEV/StreamWorkshop_12.1/StreamWorkshopInstaller/src/Documentation/middleman:23:in `<main>'
        4: from D:/DEV/StreamWorkshop_12.1/StreamWorkshopInstaller/src/Documentation/middleman:23:in `load'
        3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/middleman-cli-4.3.4/bin/middleman:10:in `<top (required)>'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:29:in `setup_bundler'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:29:in `exist?': no implicit conversion of nil into String (TypeError)

D:\DEV\StreamWorkshop_12.1\StreamWorkshopInstaller\src\Documentation>middleman server

D:\DEV\StreamWorkshop_12.1\StreamWorkshopInstaller\src\Documentation>rem C:\Ruby26-x64\bin\ruby.exe "D:\DEV\StreamWorkshop_12.1\StreamWorkshopInstaller\src\Documentation\middleman" server

D:\DEV\StreamWorkshop_12.1\StreamWorkshopInstaller\src\Documentation>ruby.exe middleman C:\Ruby26-x64\bin\source_STR
Traceback (most recent call last):
        5: from middleman:23:in `<main>'
        4: from middleman:23:in `load'
        3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/middleman-cli-4.3.4/bin/middleman:10:in `<top (required)>'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:29:in `setup_bundler'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:29:in `exist?': no implicit conversion of nil into String (TypeError)
D:\DEV\StreamWorkshop_12.1\StreamWorkshopInstaller\src\Documentation>

```
The question is : is it an other topic , or the problem is still there?
Thanks
David

**Comment by tdreyno** [comment]
Seems like this means we need to explicitly add support for x64 windows in our template?

**Comment by renard-david** [comment]
Yes I think it would be a good idea . A lot of people have Ubuntu and windows 10 64bits on the same pc and we have to be able to continue any task in any OS. In a company you cannot decide to redevelop a code you don’t like , there is not enough time for it.
Thanks for your fast response. 
Regards
David

**Comment by renard-david** [comment]
And thanks again everything works fine now thanks to the x64_mingw platform option.

**Comment by tdreyno** [comment]
@renard-david does this look right to you? https://github.com/middleman/middleman-templates-default/pull/12/files

**Comment by renard-david** [comment]
I tested on my windows10 64 bits platform, this is working for me.
thanks

**Comment by renard-david** [comment]
by the way, i corrected myself in my documentation, a mistake in the "middleman.bat " file located in the ruby directory.

initially, it was: (which does not work for my computer):
```
@ECHO OFF
@"%~dp0ruby.exe" "%~dpn0" %*
```


and now i replaced the content by:
```
rem C:\Ruby26-x64\bin\middleman.bat
bundle exec middleman build
```
