### ISSUE TITLE
Error when exec middleman server

### ISSUE THREAD

**Issue by TheoGam** [middleman/middleman#2290]
Hi ! (I'm french developer so i apologize for my English)
I need help please with middleman for running project.
When i exec "bundle exec middleman server" i have this : 

```
:image_optim is deprecated. Please use `:imageoptim` instead.
Traceback (most recent call last):
        23: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/bin/middleman:23:in `<main>'
        22: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/bin/middleman:23:in `load'
        21: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-cli-4.3.5/bin/middleman:49:in `<top (required)>'
        20: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-cli-4.3.5/bin/middleman:49:in `new'
        19: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/application.rb:280:in `initialize'
        18: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        17: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        16: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        15: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        14: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/callback_manager.rb:57:in `execute'
        13: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        12: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        11: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        10: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/callback_manager.rb:57:in `block in execute'
         9: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
         8: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/extension_manager.rb:20:in `block (2 levels) in initialize'
         7: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/extension_manager.rb:28:in `auto_activate'
         6: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/extensions.rb:117:in `auto_activate'
         5: from C:/Ruby26-x64/lib/ruby/2.6.0/set.rb:338:in `each'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/set.rb:338:in `each_key'
         3: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/extensions.rb:120:in `block in auto_activate'
         2: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/extension_manager.rb:66:in `activate'
         1: from C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/extension_manager.rb:66:in `new'
C:/Users/theog/zelty-website/vendor/bundle/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/core_extensions/default_helpers.rb:36:in `initialize': uninitialized constant Padrino::Helpers::TagHelpers (NameError)
```

## Additional information

Do u need my Gemfile and Gemfile.lock ? (I'm beginner with Ruby devlopment)

- Ruby version: 2.6.4p104 (2019-08-28 revision 67798) [x64-mingw32]
- Middleman version: 4.3.5
- OS version: Windows 10

Thank's for yours answers !

**Comment by tdreyno** [comment]
Never hurts, but more likely the issue is something about Windows or the shell.

**Comment by TheoGam** [comment]
@tdreyno it's maybe my Ruby's version the problem, i'll try with another so ...
