### ISSUE TITLE
[ERROR] undefined method `title' for nil:NilClass

### ISSUE THREAD

**Issue by matbrgz** [middleman/middleman#2291]
I am developing a benchmark of the page generation time of the different SSGs, middleman is not conducting as expected.

## Expected behavior and actual behavior

The middleman builds the site.

## Steps to reproduce the problem (from a clean middleman installation)

Run middleman build.

## Additional information
Data: 
```
source/posts/2019-09-21-01.md
---
layout: post
date: 2019-09-21
title: "2019-09-21-01"
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum euismod luctus massa. Pellentesque porta augue non varius semper. In vitae pulvinar dolor. Nunc erat sem, facilisis eu augue in, aliquam viverra magna. Quisque porttitor sodales diam, a vestibulum sem semper vel. Integer tempus quam eu ex egestas, sed auctor neque venenatis. Fusce mattis metus pellentesque iaculis euismod. Vestibulum a dictum lectus, a porta odio. Etiam sit amet lobortis lorem. Mauris iaculis ornare risus, at dictum nullam.
```

```
bundle exec middleman build --verbose
== Activating: file_watcher
== Activating: front_matter
== Activating: data
== Activating: inline_url_rewriter
== Activating: sitemap_ondisk
== Activating: sitemap_import
== Activating: sitemap_endpoint
== Activating: sitemap_proxies
== Activating: sitemap_redirects
== Activating: sitemap_move_files
== Activating: sitemap_ignore
== Activating: external_helpers
== Activating: erb_renderer
== Activating: coffee_renderer
== Activating: haml_renderer
== Activating: sass_renderer
== Activating: markdown_renderer
== Failed Activation `liquid_renderer` : cannot load such file -- liquid
== Failed Activation `slim_renderer` : cannot load such file -- slim
== Failed Activation `less_renderer` : cannot load such file -- less
== Failed Activation `stylus_renderer` : cannot load such file -- stylus
== Activating: default_helpers
== Activating: lorem
== Activating: routing
== Activating: collections
== Change (#<Set: {:data}>): links.yml
== Rebuilding resource list
== Requesting resource list rebuilding: touched_data_file
== Change (#<Set: {:source}>): index.html.erb
== Change (#<Set: {:source}>): layouts/post.erb
== Change (#<Set: {:source}>): layouts/page.erb
== Change (#<Set: {:source}>): layouts/layout.erb
== Change (#<Set: {:source}>): about.html.md
== Change (#<Set: {:source}>): posts/2019-09-21-05.md
== Change (#<Set: {:source}>): posts/2019-09-21-06.md
== Change (#<Set: {:source}>): posts/2019-09-21-10.md
== Change (#<Set: {:source}>): posts/2019-09-21-01.md
== Change (#<Set: {:source}>): posts/2019-09-21-08.md
== Change (#<Set: {:source}>): posts/2019-09-21-09.md
== Change (#<Set: {:source}>): posts/2019-09-21-03.md
== Change (#<Set: {:source}>): posts/2019-09-21-04.md
== Change (#<Set: {:source}>): posts/2019-09-21-02.md
== Change (#<Set: {:source}>): posts/2019-09-21-07.md
== Change (#<Set: {:source, :no_frontmatter}>): partials/_head.erb
== Change (#<Set: {:source, :no_frontmatter}>): partials/_footer.erb
== Change (#<Set: {:source, :no_frontmatter}>): partials/_header.erb
== Change (#<Set: {:source}>): stylesheets/style.css
== Rebuilding resource list
== Reading: Local config: config.rb
== Activating: blog
Loaded extensions:
== Extension: file_watcher
== Extension: front_matter
== Extension: data
== Extension: inline_url_rewriter
== Extension: sitemap_ondisk
== Extension: sitemap_import
== Extension: sitemap_endpoint
== Extension: sitemap_proxies
== Extension: sitemap_redirects
== Extension: sitemap_move_files
== Extension: sitemap_ignore
== Extension: external_helpers
== Extension: erb_renderer
== Extension: coffee_renderer
== Extension: haml_renderer
== Extension: sass_renderer
== Extension: markdown_renderer
== Extension: default_helpers
== Extension: lorem
== Extension: routing
== Extension: collections
== Extension: blog instance_0
== Change (#<Set: {:data}>): links.yml
== Requesting resource list rebuilding: touched_data_file
== Change (#<Set: {:source}>): index.html.erb
== Change (#<Set: {:source}>): layouts/post.erb
== Change (#<Set: {:source}>): layouts/page.erb
== Change (#<Set: {:source}>): layouts/layout.erb
== Change (#<Set: {:source}>): about.html.md
== Change (#<Set: {:source}>): posts/2019-09-21-05.md
== Change (#<Set: {:source}>): posts/2019-09-21-06.md
== Change (#<Set: {:source}>): posts/2019-09-21-10.md
== Change (#<Set: {:source}>): posts/2019-09-21-01.md
== Change (#<Set: {:source}>): posts/2019-09-21-08.md
== Change (#<Set: {:source}>): posts/2019-09-21-09.md
== Change (#<Set: {:source}>): posts/2019-09-21-03.md
== Change (#<Set: {:source}>): posts/2019-09-21-04.md
== Change (#<Set: {:source}>): posts/2019-09-21-02.md
== Change (#<Set: {:source}>): posts/2019-09-21-07.md
== Change (#<Set: {:source, :no_frontmatter}>): partials/_head.erb
== Change (#<Set: {:source, :no_frontmatter}>): partials/_footer.erb
== Change (#<Set: {:source, :no_frontmatter}>): partials/_header.erb
== Change (#<Set: {:source}>): stylesheets/style.css
== Rebuilding resource list
== Requesting resource list rebuilding: touched_file
== Requesting resource list rebuilding: registered_new_manipulator_front_matter
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_ondisk
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_import
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_endpoint
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_proxies
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_redirects
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_move_files
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_ignore
== Requesting resource list rebuilding: registered_new_manipulator_routing
== Requesting resource list rebuilding: registered_new_manipulator_routing
== Requesting resource list rebuilding: registered_new_manipulator_collections
== Requesting resource list rebuilding: registered_new_manipulator_blog_blog1_articles
== Blog Sources: posts/{year}-{month}-{day}-{title}.html (:prefix + :sources)
== Rebuilding resource list
== Running manipulator: sitemap_ondisk (0)
== Running manipulator: sitemap_endpoint (0)
== Running manipulator: sitemap_proxies (0)
== Running manipulator: sitemap_redirects (0)
== Running manipulator: sitemap_ignore (0)
== Running manipulator: sitemap_import (1)
== Running manipulator: routing (10)
== Running manipulator: front_matter (20)
== Running manipulator: blog_blog1_articles (50)
== Running manipulator: sitemap_move_files (101)
== Running manipulator: collections (110)
== Running manipulator: routing (130)
== Prerendering CSS
== Request: /stylesheets/style.css
== Finishing Request: stylesheets/style.css (0.0s)
      create  build/stylesheets/style.css
== Building files
== Request: /index.html
== Finishing Request: index.html (0.04s)
      create  build/index.html
== Request: /posts/2019-09-21-06
       error  build/posts/2019-09-21-06
== Request: /posts/2019-09-21-05
       error  build/posts/2019-09-21-05
undefined method `title' for nil:NilClass
layouts/post.erb:6:in `block (2 levels) in singleton class'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/core_extensions/default_helpers.rb:20:in `capture_from_template'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/core_extensions/default_helpers.rb:75:in `capture_html'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/template_context.rb:82:in `wrap_layout'
layouts/post.erb:1:in `block in singleton class'
layouts/post.erb:-8:in `instance_eval'
layouts/post.erb:-8:in `singleton class'
layouts/post.erb:-11:in `__tilt_47434818192820'
/var/lib/gems/2.5.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `call'
/var/lib/gems/2.5.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `evaluate'
/var/lib/gems/2.5.0/gems/tilt-2.0.9/lib/tilt/template.rb:109:in `render'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/file_renderer.rb:79:in `render'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/template_renderer.rb:157:in `block in render'
/var/lib/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/template_renderer.rb:156:in `render'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/sitemap/resource.rb:154:in `render'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:112:in `process_request'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:66:in `block in call'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:65:in `catch'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:65:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/lint.rb:49:in `_call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/lint.rb:37:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/mock.rb:74:in `request'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/mock.rb:56:in `get'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:232:in `block in output_resource'
/var/lib/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:225:in `output_resource'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:504:in `call_with_index'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:471:in `process_incoming_jobs'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:453:in `block in worker'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:444:in `fork'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:444:in `worker'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:435:in `block in create_workers'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `each'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `each_with_index'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `create_workers'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:373:in `work_in_processes'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:277:in `map'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:137:in `output_resources'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:131:in `output_files'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:71:in `block in run!'
/var/lib/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:70:in `run!'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-cli-4.3.5/lib/middleman-cli/build.rb:84:in `block in build'
/var/lib/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-cli-4.3.5/lib/middleman-cli/build.rb:83:in `build'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.5.0/gems/middleman-cli-4.3.5/bin/middleman:70:in `<top (required)>'
/usr/local/bin/middleman:23:in `load'
/usr/local/bin/middleman:23:in `<main>'
undefined method `title' for nil:NilClass
layouts/post.erb:6:in `block (2 levels) in singleton class'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/core_extensions/default_helpers.rb:20:in `capture_from_template'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/core_extensions/default_helpers.rb:75:in `capture_html'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/template_context.rb:82:in `wrap_layout'
layouts/post.erb:1:in `block in singleton class'
layouts/post.erb:-8:in `instance_eval'
layouts/post.erb:-8:in `singleton class'
layouts/post.erb:-11:in `__tilt_47434818192820'
/var/lib/gems/2.5.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `call'
/var/lib/gems/2.5.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `evaluate'
/var/lib/gems/2.5.0/gems/tilt-2.0.9/lib/tilt/template.rb:109:in `render'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/file_renderer.rb:79:in `render'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/template_renderer.rb:157:in `block in render'
/var/lib/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/template_renderer.rb:156:in `render'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/sitemap/resource.rb:154:in `render'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:112:in `process_request'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:66:in `block in call'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:65:in `catch'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:65:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/lint.rb:49:in `_call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/lint.rb:37:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/mock.rb:74:in `request'
/var/lib/gems/2.5.0/gems/rack-2.0.7/lib/rack/mock.rb:56:in `get'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:232:in `block in output_resource'
/var/lib/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:225:in `output_resource'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:504:in `call_with_index'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:471:in `process_incoming_jobs'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:453:in `block in worker'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:444:in `fork'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:444:in `worker'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:435:in `block in create_workers'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `each'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `each_with_index'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `create_workers'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:373:in `work_in_processes'
/var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:277:in `map'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:137:in `output_resources'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:131:in `output_files'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:71:in `block in run!'
/var/lib/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:70:in `run!'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/var/lib/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/var/lib/gems/2.5.0/gems/middleman-cli-4.3.5/lib/middleman-cli/build.rb:84:in `block in build'
/var/lib/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/var/lib/gems/2.5.0/gems/middleman-cli-4.3.5/lib/middleman-cli/build.rb:83:in `build'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.5.0/gems/middleman-cli-4.3.5/bin/middleman:70:in `<top (required)>'
/usr/local/bin/middleman:23:in `load'
/usr/local/bin/middleman:23:in `<main>'
```

- Ruby version: 2.5
- Middleman version: >=4
- OS version: Docker Ubuntu 1804

**Comment by tdreyno** [comment]
What's going on in `layouts/post.erb`?

**Comment by MatheusRV** [comment]
```
<% wrap_layout :layout do %>

<div class="post">

  <header class="post-header">
    <h1 class="post-title"><%= current_article.title %></h1>
    <p class="post-meta"><%= current_article.date.strftime('%b %-d, %Y') %></p>
  </header>

  <article class="post-main">
    <%= yield %>
  </article>

</div>

<div>
    <b>More News 'n' Updates</b>
    <ul>
      <% blog.articles.each do |article| %>
        <li><%= link_to article.title, article.url %></li>
      <% end %>
    </ul>
</div>

<% end %>

```
