### ISSUE TITLE
When a file in deps.yml is deleted, build fails

### ISSUE THREAD

**Issue by smcgivern** [middleman/middleman#2292]
## Expected behavior and actual behavior

When using the new dependency tracking feature in master, the build fails if a file in deps.yml is deleted. I can reproduce this by running `middleman build --track-dependencies --only-changed` twice on the same Middleman site, but deleting a source file in between.

## Steps to reproduce the problem (from a clean middleman installation)

I started by installing using the repository:

```shell
$ middleman-cli/bin/middleman init test-app
$ cd test-app
$ # change Gemfile to point to local copy of repository; for instance, path: '~/Code/middleman'
$ bundle # use the local gem
$ echo foo > source/foo.html
$ bundle exec middleman build --track-dependencies --only-changed
deps.yml was missing. Dependency graph must be rebuilt.
      create  build/stylesheets/site.css
      create  build/images/.keep
      create  build/foo.html
      create  build/javascripts/site.js
      create  build/index.html
Project built successfully.
$ rm source/foo.html
$ bundle exec middleman build --track-dependencies --only-changed
bundler: failed to load command: middleman (/Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bin/middleman)
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/seanmcgivern/Code/middleman/test-app/source/foo.html
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/2.6.0/digest.rb:50:in `initialize'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/2.6.0/digest.rb:50:in `open'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/2.6.0/digest.rb:50:in `file'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/2.6.0/digest.rb:35:in `file'
  /Users/seanmcgivern/Code/middleman/middleman-core/lib/middleman-core/util/files.rb:154:in `hash_file'
  /Users/seanmcgivern/Code/middleman/middleman-core/lib/middleman-core/dependencies/vertices/file_vertex.rb:61:in `hash_file'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/seanmcgivern/Code/middleman/middleman-core/lib/middleman-core/dependencies/vertices/file_vertex.rb:36:in `valid?'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/seanmcgivern/Code/middleman/middleman-core/lib/middleman-core/dependencies/graph.rb:132:in `reject'
  /Users/seanmcgivern/Code/middleman/middleman-core/lib/middleman-core/dependencies/graph.rb:132:in `invalidated'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/seanmcgivern/Code/middleman/middleman-core/lib/middleman-core/builder.rb:87:in `run!'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/seanmcgivern/Code/middleman/middleman-cli/lib/middleman-cli/build.rb:124:in `block in build'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
  /Users/seanmcgivern/Code/middleman/middleman-core/lib/middleman-core/util.rb:18:in `instrument'
  /Users/seanmcgivern/Code/middleman/middleman-cli/lib/middleman-cli/build.rb:123:in `build'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/seanmcgivern/Code/middleman/middleman-cli/bin/middleman:67:in `<top (required)>'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bin/middleman:23:in `load'
  /Users/seanmcgivern/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bin/middleman:23:in `<top (required)>'
```

`deps.yml` looks like:

```yaml
---
data_depth: .inf
global:
  Gemfile.lock: a7c38563b4bee06b4d0bb582f34106c4e678d4fe
  config.rb: 8b774273b472bebdbf35d4f4f0e7429438c0c4dc
edges:
  source/index.html.erb:
  - source/layouts/layout.erb
vertices:
  file:
    source/foo.html: f1d2d2f924e986ac86fdf7b36c94bcdf32beec15
    source/index.html.erb: 2b2372dfaa5f735c88254678f6497c41422217e3
    source/javascripts/site.js: 954757c224da31e45602b19f7e61c454e2bc62d1
    source/layouts/layout.erb: 197bfb5c74771b85e1132bc21f699cbab4ab45d7
    source/stylesheets/site.css.scss: de58f9e82a6feabdfa37471c70cddde6b1765502
```

## Additional information

- Ruby version: 2.6.3
- Middleman version: master
- OS version: OS X 10.14.6

I think that `Middleman::Dependencies::FileVertex#valid?` should simply return false if the file no longer exists? https://github.com/middleman/middleman/blob/3d359378b34b00215f636094db34e03da46421bf/middleman-core/lib/middleman-core/dependencies/vertices/file_vertex.rb#L34-L38

**Comment by tdreyno** [comment]
On it.

**Comment by tdreyno** [comment]
@smcgivern Should be good on master now. Thanks

**Comment by smcgivern** [comment]
Thanks @tdreyno! 🙇
