### ISSUE TITLE
Redirect regression in 5.0 version

### ISSUE THREAD

**Issue by skryukov** [middleman/middleman#2299]
## Expected behavior and actual behavior

`bundle exec middleman build` returns error when a [redirect](https://middlemanapp.com/basics/redirects) is used.

Backlog:
```
...
== Building files
     skipped  build/images/.keep
       error  build/realy/old/index.html
Contract violation for argument 2 of 2:
        Expected: #<Contracts::IsA:0x00007ff1ad8b2760>,
        Actual: nil
        Value guarded in: Middleman::Dependencies::FileVertex::from_source_file
        With Contract: Contracts::IsA, Contracts::IsA => Middleman::Dependencies::FileVertex
        At: bundler/gems/middleman-ba2098ec63db/middleman-core/lib/middleman-core/dependencies/vertices/file_vertex.rb:23
gems/contracts-0.16.0/lib/contracts.rb:49:in `block in <class:Contract>'
gems/contracts-0.16.0/lib/contracts.rb:155:in `failure_callback'
gems/contracts-0.16.0/lib/contracts/method_handler.rb:143:in `rescue in block in redefine_method'
gems/contracts-0.16.0/lib/contracts/method_handler.rb:136:in `block in redefine_method'
bundler/gems/middleman-ba2098ec63db/middleman-core/lib/middleman-core/builder.rb:369:in `block in output_resource'
gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
bundler/gems/middleman-ba2098ec63db/middleman-core/lib/middleman-core/util.rb:18:in `instrument'
bundler/gems/middleman-ba2098ec63db/middleman-core/lib/middleman-core/builder.rb:336:in `output_resource'
gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
bundler/gems/middleman-ba2098ec63db/middleman-core/lib/middleman-core/builder.rb:214:in `block (2 levels) in output_resources'
bundler/gems/middleman-ba2098ec63db/middleman-core/lib/middleman-core/builder.rb:214:in `map!'
bundler/gems/middleman-ba2098ec63db/middleman-core/lib/middleman-core/builder.rb:214:in `block in output_resources'
...
```

## Steps to reproduce the problem (from a clean middleman installation)
Add `redirect 'really/old/index.html', to: 'index.html'` to `config.rb`
Run `bundle exec middleman build`

## Additional information

- Ruby version: `2.6.2`
- Middleman version: `5.0.0.rc.1` and `master`
- OS version: macOS

**Comment by tdreyno** [comment]
Thank you. I'll track this down.

**Comment by pwim** [comment]
#2328 resolved this.

**Comment by skryukov** [comment]
@pwim, thank you!
