### ISSUE TITLE
middleman init <project> doesn't work on ruby 2.7.0

### ISSUE THREAD

**Issue by jimmynguyc** [middleman/middleman#2307]
## Expected behavior and actual behavior
```bash
$ ruby -v
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]

$ middleman init foo
         run  git clone --depth 1 https://github.com/middleman/middleman-templates-default.git /var/folders/q2/sgvdqm3j0tx45mtgclkdn0g40000gn/T/d20200107-4588-4emhe5 from "."
Cloning into '/var/folders/q2/sgvdqm3j0tx45mtgclkdn0g40000gn/T/d20200107-4588-4emhe5'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 19 (delta 0), reused 13 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), done.
       exist  
      create  .gitignore
      create  Gemfile
      create  config.rb
      create  source/images/.keep
      create  source/index.html.erb
      create  source/javascripts/site.js
      create  source/layouts/layout.erb
      create  source/stylesheets/site.css.scss
         run  bundle install from "./foo"

...
```

```bash
$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

$ middleman init foo
Main thread
Main thread
Main thread
Main thread
Main thread
Main thread
Main thread
Main thread

...

Forked thread
Forked thread
Forked thread
Forked thread
^CForked thread
Forked thread
Forked thread
Forked thread
Forked thread
Forked thread
Traceback (most recent call last):
        25: from /Users/jimmy/.rbenv/versions/2.7.0/bin/middleman:23:in `<main>'
        24: from /Users/jimmy/.rbenv/versions/2.7.0/bin/middleman:23:in `load'
        23: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-cli-4.3.5/bin/middleman:49:in `<top (required)>'
        22: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-cli-4.3.5/bin/middleman:49:in `new'
        21: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/application.rb:263:in `initialize'
        20: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/application.rb:263:in `new'
        19: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/extension_manager.rb:12:in `initialize'
        18: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/extensions.rb:125:in `load_settings'
        17: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/extensions.rb:125:in `each'
        16: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/extensions.rb:127:in `block in load_settings'
        15: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/extensions.rb:91:in `load'
        14: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/core_extensions/rendering.rb:23:in `block in <top (required)>'
        13: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        12: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        11: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/renderers/sass.rb:1:in `<top (required)>'
        10: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         9: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         8: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sassc-2.2.1/lib/sassc.rb:34:in `<top (required)>'
         7: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sassc-2.2.1/lib/sassc.rb:34:in `require_relative'
         6: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sassc-2.2.1/lib/sassc/util.rb:9:in `<top (required)>'
         5: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         4: from /Users/jimmy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         3: from /Users/jimmy/Projects/playground/thread.rb:7:in `<top (required)>'
         2: from /Users/jimmy/Projects/playground/thread.rb:7:in `puts'
         1: from /Users/jimmy/Projects/playground/thread.rb:7:in `puts'
/Users/jimmy/Projects/playground/thread.rb:7:in `write': Interrupt
```

## Steps to reproduce the problem (from a clean middleman installation)
Use with ruby 2.7.0p0

## Additional information

- Ruby version: ruby 2.7.0p0
- Middleman version: 4.3.5
- OS version: macOS Catalina 10.15.2 (19C57)

**Comment by tdreyno** [comment]
Thanks. I'll start by adding 2.7 to our CI and go from there.

**Comment by tdreyno** [comment]
Hi @jimmynguyc, CI passes with 2.7.0 and I was able to init on my Catalina machine with 2.7.0

Your error looks interesting, especially with the error happening in `/Users/jimmy/Projects/playground/thread.rb`, which isn't part of Middleman.

I wonder if we're accidentally importing something we don't need?

Sometimes folders with nested Gemfiles can be a problem too

**Comment by jimmynguyc** [comment]
I'm sorry I'm an idiot. Should have noticed `thread.rb` in the logs, which content looks like this 

```ruby
Thread.fork {
  while true
    puts "Forked thread"
  end
}
while true
  puts "Main thread"
end
```

I wonder why it didn't make a fuss with ruby 2.6.x
