### ISSUE TITLE
macOS Big Sur (11.0.1) - Errors when running middleman commands

### ISSUE THREAD

**Issue by aluminumbirdy** [middleman/middleman#2404]
Since upgrading to macOS Big Sur (11.0.1) I've been unable to init projects or run `bundle exec middleman server`. Below are two outputs I receive from both commands. From first glance, maybe this is a ruby version issue? I have included execJs in the gem file on an existing project, so not sure if that would be an issue.

**middleman init prejectName**

```
        Traceback (most recent call last):
	16: from /usr/local/bin/middleman:23:in `<main>'
	15: from /usr/local/bin/middleman:23:in `load'
	14: from /Library/Ruby/Gems/2.6.0/gems/middleman-cli-4.3.11/bin/middleman:49:in `<top (required)>'
	13: from /Library/Ruby/Gems/2.6.0/gems/middleman-cli-4.3.11/bin/middleman:49:in `new'
	12: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/application.rb:263:in `initialize'
	11: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/application.rb:263:in `new'
	10: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extension_manager.rb:12:in `initialize'
	 9: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions.rb:125:in `load_settings'
	 8: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions.rb:125:in `each'
	 7: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions.rb:127:in `block in load_settings'
	 6: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions.rb:91:in `load'
	 5: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/core_extensions/rendering.rb:11:in `block in <top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require': cannot load such file -- coffee_script (LoadError)
	23: from /usr/local/bin/middleman:23:in `<main>'
	22: from /usr/local/bin/middleman:23:in `load'
	21: from /Library/Ruby/Gems/2.6.0/gems/middleman-cli-4.3.11/bin/middleman:49:in `<top (required)>'
	20: from /Library/Ruby/Gems/2.6.0/gems/middleman-cli-4.3.11/bin/middleman:49:in `new'
	19: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/application.rb:263:in `initialize'
	18: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/application.rb:263:in `new'
	17: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extension_manager.rb:12:in `initialize'
	16: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions.rb:125:in `load_settings'
	15: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions.rb:125:in `each'
	14: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions.rb:127:in `block in load_settings'
	13: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions.rb:91:in `load'
	12: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/core_extensions/rendering.rb:11:in `block in <top (required)>'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 9: from /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	 5: from /Library/Ruby/Gems/2.6.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
	 1: from /Library/Ruby/Gems/2.6.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/Library/Ruby/Gems/2.6.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
```

**bundle exec middleman build**

```
bundler: failed to load command: middleman (/usr/local/bin/middleman)
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
  /Library/Ruby/Gems/2.6.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
  /Library/Ruby/Gems/2.6.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
  /Library/Ruby/Gems/2.6.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
  /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
  /Library/Ruby/Gems/2.6.0/gems/middleman-core-4.3.11/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
  /Library/Ruby/Gems/2.6.0/gems/middleman-cli-4.3.11/bin/middleman:10:in `<top (required)>'
  /usr/local/bin/middleman:23:in `load'
  /usr/local/bin/middleman:23:in `<top (required)>'
```

Any thoughts on what's going on here and how to fix it?

**Comment by tdreyno** [comment]
```
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
```

Usually means installing Node. Or therubyracer gem (however, I heard that gem is currently broken on Big Sur as well). Apple used to include their own option by default called JavaScriptCore, but they may have stopped that for Big Sur.

**Comment by aluminumbirdy** [comment]
Thanks for quick reply. I'll see if installing Node fixes anything. That's a bummer on the exclusion from Apple. Another year and another hurdle from macOS lol.

**Comment by aluminumbirdy** [comment]
Okay, I installed Node. I can confirm, installing the latest version of Node fixed this issue.
