### ISSUE TITLE
Commonmark markdown renderer

### ISSUE THREAD

**Issue by noraj** [middleman/middleman#2420]
Markdown rendering is brought by [tilt](https://github.com/rtomayko/tilt/) but the option supported in middleman are limited

![image](https://user-images.githubusercontent.com/16578570/103028616-693d5d80-4558-11eb-8949-074ada4e8bf6.png)

compared to the ones available in tilt:

![image](https://user-images.githubusercontent.com/16578570/103028673-84a86880-4558-11eb-8e56-253121035825.png)

None of the supported libraries in middleman is supporting commonmark but tilt already support [commonmarker](https://github.com/gjtorikian/commonmarker), a ruby renderer that does. So as tilt already does it it should not be much paint to support in middleman too.

**Comment by tdreyno** [comment]
Agree, its just an allow-list of Tilt's option so adding new ones is pretty straightforward.

**Comment by mb21** [comment]
You can already do now:

    bundle add commonmarker

and in `config.rb`:

    set :markdown_engine, :commonMarker

But this will have non-default extensions disabled...

**Comment by movermeyer** [comment]
> But this will have non-default extensions disabled... 

Exactly. I don't think I have a single Markdown file that doesn't use at least one extension. 😢

**Comment by noraj** [comment]
stale bots...

**Comment by waldyrious** [comment]
This should remain open.

**Comment by waldyrious** [comment]
Sigh... bump.

**Comment by noraj** [comment]
This bot is annoying.

**Comment by noraj** [comment]
naughty bot

**Comment by tdreyno** [comment]
PR's welcome. No reason to keep re-opening this issue.

**Comment by noraj** [comment]
@tdreyno Why not leaving this issue open and removing this useless stalebot? So people wanting to PR would see the issue.

**Comment by waldyrious** [comment]
If someone could offer a bit more insight into what changes are needed, I'd be happy to prepare a PR. In particular, I am not sure I understand @tdreyno's [comment](https://github.com/middleman/middleman/issues/2420#issuecomment-751277800) that

> its just an allow-list of Tilt's option

Where is that allow-list defined? For example, [searching for "bluecloth"](https://github.com/middleman/middleman/search?q=bluecloth&type=code) (mentioned in @noraj's list at the opening comment of this issue) doesn't yield any results in the code :raised_eyebrow:

And furthermore, what does one need to do (besides adding an entry to that list, wherever it is) to add support for commonmarker?

**Comment by mb21** [comment]
> its just an allow-list of Tilt's option

@waldyrious probably [around here](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/renderers/markdown.rb#L15)? I tried to get this to work a year ago, but somehow didn't succeed... don't remember what the errors were...

**Comment by waldyrious** [comment]
@mb21 I had already read through that code (which you pointed out above) with my limited understanding of Ruby, and I couldn't figure out how it results in the subset listed by @noraj in the opening comment of this issue. In particular, as I mentioned in my previous comment, I can't figure out where BlueCloth is included in the allow-list. Could it be that the list is incorrect? :thinking:

**Comment by verhovsky** [comment]
I tried adding 

```ruby
set :markdown_engine, :commonMarker
```

to [my site's config.rb](https://github.com/adambard/learnxinyminutes-site/blob/16efe425936a7682efe5ea4759b7650a682020a3/config.rb) but I get this error when opening a url that uses markdown

```
NameError: uninitialized constant Tilt::CommonMarkerTemplate::CommonMarker
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/tilt-2.0.11/lib/tilt/commonmarker.rb:80:in `evaluate'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/tilt-2.0.11/lib/tilt/template.rb:109:in `render'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/file_renderer.rb:79:in `render'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/template_renderer.rb:184:in `_render_with_all_renderers'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/template_renderer.rb:147:in `block in render'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:208:in `instrument'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/util.rb:20:in `instrument'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/template_renderer.rb:146:in `render'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/sitemap/resource.rb:154:in `render'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/rack.rb:113:in `process_request'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/rack.rb:67:in `block in call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/rack.rb:66:in `catch'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/middleman-core-4.5.1/lib/middleman-core/rack.rb:66:in `call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/show_exceptions.rb:23:in `call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/head.rb:12:in `call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/lint.rb:50:in `_call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/lint.rb:38:in `call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/builder.rb:244:in `call'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/handler/webrick.rb:95:in `service'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
```

- M1 macOS 15.1.1
- `ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin24]`
- `gem "commonmarker", "~> 2.0"`
- `gem 'middleman', '~> 4.5'`

**Comment by tdreyno** [comment]
Likely some logic needs to be added here to map from the symbol to whatever the correct class Tilt uses to render is called: https://github.com/middleman/middleman/blob/47223f5768ce079e24865ceef836a0d95a154398/middleman-core/lib/middleman-core/renderers/markdown.rb#L22-L28

**Comment by waldyrious** [comment]
> whatever the correct class Tilt uses to render is called

It's been a long time since I looked at this, but the relevant Tilt class [does seem to be called](https://github.com/rtomayko/tilt/blob/9e2dba10cfd7a11b8e7b2b8f6214ad85ef2caac7/lib/tilt/commonmarker.rb) `CommonMarkerTemplate`, so I'm not sure @verhovsky's error

> NameError: uninitialized constant Tilt::CommonMarkerTemplate::CommonMarker

...would necessarily be fixed by an additional entry in that mapping :thinking:

But just to be on the safe side, I interpreted your suggestion as meaning a change somewhat like this:

```diff
 # Map symbols to classes
 markdown_engine_klass = if app.config[:markdown_engine].is_a? Symbol
   engine = app.config[:markdown_engine].to_s
-  engine = engine == 'rdiscount' ? 'RDiscount' : engine.camelize 
+    engine = case engine
+    when 'rdiscount' then 'RDiscount'
+    when 'commonmarker' then 'CommonMarker'
+    else engine.camelize
+    end
   app.config[:markdown_engine_prefix].const_get("#{engine}Template")
 else
   app.config[:markdown_engine_prefix]
 end
```

Is that roughly what you had in mind, or am I off the mark?

**Comment by waldyrious** [comment]
Just for future reference, and following up on my [previous comment](https://github.com/middleman/middleman/issues/2420#issuecomment-1073075844):

> I am not sure I understand @tdreyno's [comment](https://github.com/middleman/middleman/issues/2420#issuecomment-751277800) that [middleman's list of supported options for markdown, listed in the [opening comment](https://github.com/middleman/middleman/issues/2420#issue-773986611) of this issue]
>
>> is just an allow-list of Tilt's options
>
> Where is that allow-list defined?

and the later one:

> I had already read through [the code in [lib/middleman-core/renderers/markdown.rb](https://github.com/middleman/middleman/blob/47223f5768ce079e24865ceef836a0d95a154398/middleman-core/lib/middleman-core/renderers/markdown.rb#L13-L32)] [...], and I couldn't figure out how it results in the subset listed by @noraj in the opening comment of this issue.

I dug up where indeed that list came from, and it seems it was originally introduced in https://github.com/middleman/middlemanapp.com/commit/78b265931acf52a496c3b9dac1c86a7c819a5beb, from 17 Nov 2011; and as the commit message alludes to ("all possible Tilt templating engines"), that list indeed came straight from what Tilt supported at the time: see the [table in their README](https://github.com/rtomayko/tilt/blob/8aae30643b4072a5a4020ce5044aab2aad87ef61/README.md), and [lib/tilt/markdown.rb](https://github.com/rtomayko/tilt/blob/8aae30643b4072a5a4020ce5044aab2aad87ef61/lib/tilt/markdown.rb), both of which indeed indicated the following list at the time:

- RDiscount (`Tilt::RDiscountTemplate`)
- Redcarpet (`Tilt::RedcarpetTemplate`)
- BlueCloth (`Tilt::BlueClothTemplate`)
- Kramdown (`Tilt::KramdownTemplate`)
- Maruku (`Tilt::MarukuTemplate`)

CommonMarker was only added later, in https://github.com/rtomayko/tilt/pull/281 (7 Apr 2016). The current list

So it seems like Middleman's [documentation](https://github.com/middleman/middlemanapp.com/blob/master/source/localizable/advanced/template-engine-options.html.markdown) needs to be updated to include the new entries (CommonMarker and Pandoc), although this should only happen once the usage of the new options is confirmed to work (see @verhovsky's comment [above](https://github.com/middleman/middleman/issues/2420#issuecomment-2510768928)).

**Comment by verhovsky** [comment]
You can try to reproduce the issue like this:

```sh
cd /tmp

git clone https://github.com/adambard/learnxinyminutes-site.git
cd learnxinyminutes-site
git checkout 299fc33a17fbfef820ef0c6e4a2b41f0ff7dd726
git clone https://github.com/adambard/learnxinyminutes-docs.git source/docs

sed 's|^set :markdown_engine, :redcarpet|set :markdown_engine, :commonMarker|' config.rb > config.tmp && mv config.tmp config.rb
echo >> Gemfile
echo "gem 'commonmarker'" >> Gemfile

gem install bundler
bundle install
bundle exec middleman serve
```

Though when I tried this just now I got this error before even changing from redcarpet to commonmarker

```
/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require': cannot load such file -- asciidoctor (LoadError)
```

and if I do

```
echo "gem 'asciidoctor'" >> Gemfile
echo "gem 'less'" >> Gemfile
echo "gem 'therubyracer'" >> Gemfile
bundle install
```

I get this error

```
dyld[10716]: missing symbol called
Abort trap: 6
```
