### ISSUE TITLE
With middleman-blog, multibyte tag produces error `incompatible character encodings: UTF-8 and ASCII-8BIT`

### ISSUE THREAD

**Issue by ikuwow** [middleman/middleman#2485]
### Actual

```
$ bundle exec middleman build --verbose

[...]

       error  build/tags/作った/index.html
incompatible character encodings: UTF-8 and ASCII-8BIT
layouts/layout.erb:12:in `__tilt_70312138047440'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `render'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/file_renderer.rb:79:in `render'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/template_renderer.rb:157:in `block in render'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/notifications.rb:205:in `instrument'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/util.rb:21:in `instrument'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/template_renderer.rb:156:in `render'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/sitemap/resource.rb:154:in `render'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/rack.rb:113:in `process_request'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/rack.rb:67:in `block in call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/rack.rb:66:in `catch'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/rack.rb:66:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/extensions/minify_javascript.rb:55:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/extensions/minify_css.rb:65:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/htmlcompressor-0.2.0/lib/htmlcompressor/rack.rb:36:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/core_extensions/inline_url_rewriter.rb:74:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/mock.rb:84:in `request'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/mock.rb:57:in `get'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/builder.rb:232:in `block in output_resource'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/notifications.rb:205:in `instrument'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/util.rb:21:in `instrument'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/builder.rb:225:in `output_resource'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:507:in `call_with_index'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:477:in `process_incoming_jobs'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:459:in `block in worker'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `fork'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `worker'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:441:in `block in create_workers'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each_with_index'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `create_workers'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:380:in `work_in_processes'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:283:in `map'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/builder.rb:137:in `output_resources'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/builder.rb:131:in `output_files'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/builder.rb:71:in `block in run!'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/notifications.rb:205:in `instrument'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/util.rb:21:in `instrument'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/builder.rb:70:in `run!'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-cli-4.4.0/lib/middleman-cli/build.rb:84:in `block in build'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/notifications.rb:205:in `instrument'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.0/lib/middleman-core/util.rb:21:in `instrument'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-cli-4.4.0/lib/middleman-cli/build.rb:83:in `build'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:40:in `block in register'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/middleman-cli-4.4.0/bin/middleman:70:in `<top (required)>'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/bin/middleman:23:in `load'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/bin/middleman:23:in `<top (required)>'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli/exec.rb:63:in `load'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli/exec.rb:28:in `run'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli.rb:497:in `exec'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli.rb:30:in `dispatch'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli.rb:24:in `start'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/exe/bundle:49:in `block in <top (required)>'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/exe/bundle:37:in `<top (required)>'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/bin/bundle:23:in `load'
/Users/degawaikuo/.asdf/installs/ruby/2.6.6/bin/bundle:23:in `<main>'
```

* `middleman server` produces same error
* My failing build: https://github.com/ikuwow/query_ok/pull/302

### Expected

the build succeeds

## Steps to reproduce the problem (from a clean middleman installation)

```
bundle exec middleman build --verbose
```

## Additional information

- Ruby version: 2.6.6
- Middleman version: 4.3.11, 4.4.0
    - 4.3.9 produces no errors
- Middleman blog version: 4.0.3
- OS version: macOS 11.4

**Comment by tdreyno** [comment]
Looks like a change in activesupport, I'll take a look

**Comment by ikuwow** [comment]
Update:
This problem exists from Middleman 4.3.11. 
4.3.9 produces no errors.
So https://github.com/middleman/middleman/compare/v4.3.10...v4.3.11 may break multibyte tags.

(my failing build)
https://github.com/ikuwow/query_ok/pull/317
https://github.com/ikuwow/query_ok/pull/302

**Comment by ikuwow** [comment]
middleman-core 5.0.0.rc.2 works fine with multibyte tags:
https://github.com/middleman/middleman-blog/pull/381
