### ISSUE TITLE
Missing middleman-core/profiling on 4.4.1

### ISSUE THREAD

**Issue by MasterOdin** [middleman/middleman#2511]
## Expected behavior and actual behavior

[Build suite](https://github.com/slatedocs/slate/runs/4085552148) for our project failed on trying to upgrade to middleman 4.4.1 from 4.4.0 with the following error:
```
bundler: failed to load command: middleman (/home/runner/work/slate/slate/vendor/bundle/ruby/2.5.0/bin/middleman)
/home/runner/work/slate/slate/vendor/bundle/ruby/2.5.0/gems/middleman-cli-4.4.1/bin/middleman:3:in `require': cannot load such file -- middleman-core/profiling (LoadError)
	from /home/runner/work/slate/slate/vendor/bundle/ruby/2.5.0/gems/middleman-cli-4.4.1/bin/middleman:3:in `<top (required)>'
	from /home/runner/work/slate/slate/vendor/bundle/ruby/2.5.0/bin/middleman:25:in `load'
	from /home/runner/work/slate/slate/vendor/bundle/ruby/2.5.0/bin/middleman:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `load'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/cli.rb:474:in `exec'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/cli.rb:30:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/cli.rb:24:in `start'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/exe/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.2.22/exe/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle:23:in `<main>'
```

This failure happened across all ruby versions 2.5+.

## Steps to reproduce the problem (from a clean middleman installation)

Clone https://github.com/slatedocs/slate/pull/1528, run:

```bash
bundle install
bundle exec middleman build
```

## Additional information

Looks similar to https://github.com/middleman/middleman/issues/2375?

- Ruby version: 2.5+
- Middleman version: 4.4.1

**Comment by MasterOdin** [comment]
Looks like whatever was broken in 4.4.1 was fixed in 4.4.2.
