### ISSUE TITLE
Cannot start server ( or use cli)  with Ruby 3.0 and Middleman 4

### ISSUE THREAD

**Issue by shaunakv1** [middleman/middleman#2539]
## Expected behavior and actual behavior

Trying to upgrade an existing middleman 4 app from ruby 2.6 to ruby 3.0. Bundle installs successfully, however when I run 

`bundle exec middleman s`

It throws the following error: 

```bash
bundler: failed to load command: middleman (/usr/local/bundle/bin/middleman)
/usr/local/bundle/gems/middleman-cli-4.4.2/lib/middleman-cli/console.rb:4:in `<module:Cli>': superclass mismatch for class Console (TypeError)
        from /usr/local/bundle/gems/middleman-cli-4.4.2/lib/middleman-cli/console.rb:2:in `<top (required)>'
        from /usr/local/bundle/gems/middleman-cli-4.4.2/bin/middleman:66:in `require'
        from /usr/local/bundle/gems/middleman-cli-4.4.2/bin/middleman:66:in `<top (required)>'
        from /usr/local/bundle/bin/middleman:25:in `load'
        from /usr/local/bundle/bin/middleman:25:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/cli.rb:484:in `exec'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/cli.rb:25:in `start'
        from /usr/local/bundle/gems/bundler-2.3.0/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.0/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.3.0/exe/bundle:36:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:23:in `load'
        from /usr/local/bundle/bin/bundle:23:in `<main>'
```
## Steps to reproduce the problem (from a clean middleman installation)

Actual Docker Command Used
```bash
 docker run --rm -it --name digitalcoast -p 4567:4567 ocm/digitalcoast bundle exec middleman server
```

Here's my Dockerfile

```dockerfile
FROM ruby:3.0
ENV BUNDLER_VERSION 2.3


SHELL ["/bin/bash", "-o", "pipefail", "-c"]

#install node
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -\
    && apt-get update -qq && apt-get install -qq --no-install-recommends \
    nodejs \
    && apt-get upgrade -qq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /site
WORKDIR /site

#COPY .bundle /site/.bundle
COPY Gemfile /site/Gemfile
#COPY Gemfile.lock /site/Gemfile.lock
COPY extensions /site/extensions

RUN gem install bundler:${BUNDLER_VERSION}
RUN bundle install --jobs `expr $(cat /proc/cpuinfo | grep -c "cpu cores") - 1` --retry 3

COPY . /site

EXPOSE 4567

## Run Middleman Server
# CMD /bin/bash bundle exec middleman server
```

Gemfile: 

```ruby
# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.4.2'

# Sprockets
gem "middleman-sprockets"

#Blog gem for creating site sections as blog
gem "middleman-blog"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.4.7"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.1", :platforms => [:mswin, :mingw, :jruby, :x64_mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby, :x64_mingw]

#Replaces Middleman's built-in console with Pry, à la pry-rails.
gem 'middleman-pry'

# To minify output html
gem 'middleman-minify-html'

# To Generate Sitemaps
gem 'middleman-search_engine_sitemap'

# Inline debugging 
gem "debug"

# Custom extensions
gem "middleman-remote_source", path: "extensions/middleman-remote_source"
gem "middleman-remote_images", path: "extensions/middleman-remote_images"


#Integration testing harness
gem 'rake', '~> 10.4'
gem 'rspec', '~> 3.4'
gem 'capybara'

```

## Additional information

- Ruby version:  3.0
- Middleman version:  4.4.2
- OS version:  Docker

**Comment by tdreyno** [comment]
Which 4.4.0 tried to add some support for Ruby 3, I would not suggest relying on it. It is far too much work to support projects as old as 2008 and a language released in 2020 at the same time.

Patches welcome or if you want to live dangerously the `master` branch and 5.0x series will be Ruby 3.1+ only

**Comment by shaunakv1** [comment]
Thanks @tdreyno 

Figured 4.x was unstable Ruby 3. Wish I had enough time left to investigate and patch after the day job! 

In any case thanks for the reply. 

Quick question: 

Is there an estimate on when 5.x might be a stable release?  We are in the middle of an update to put middleman site and debating if it's worth porting over to 5x rc. It might be worth it if a stable release is on the horizon.

**Comment by tdreyno** [comment]
I'm not certain 5.x will ever be released. the brave are welcome to use the master branch, and fixes are going in to it for modern support, but I also don't have enough time in the day to support a large release.

I think with a Dockerized environment (or VM, whatever) a Middleman 4 site should be able to output a basic website forever. I know its boring, but atleast your team won't spend their days messing with alpha software and dependency changes over time.

**Comment by shaunakv1** [comment]
unstale!

**Comment by markets** [comment]
Hello @shaunakv1 👋🏼 some related changes have been merged to `4.x` branch: https://github.com/middleman/middleman/compare/v4.4.2...4.x. Maybe it's worth to make a try pointing your Gemfile to that branch.

**Comment by henrique-ft** [comment]
Here works pretty well with Ruby `3.0.2` and middleman `4.4.2`

**Comment by markets** [comment]
Thanks for confirming @henrique-ft 👍🏼 

@tdreyno we can already close this one.
