### ISSUE TITLE
undefined local variable or method `path' for #<Middleman::Extensions::MinifyJavascript::Rack:0x00007f194be07480> (NameError)

### ISSUE THREAD

**Issue by desokroshan** [middleman/middleman#2548]
## Expected behavior and actual behavior

```
/local/p4clients/pkgbuild-xN2v7/workspace/env/WfmGroceryOrdering-1.0/test-runtime/ruby2.3.x/lib/ruby/gems/2.3.0/gems/middleman-core-3.3.12/lib/middleman-more/extensions/minify_javascript.rb:97:in `rescue in minify': undefined local variable or method `path' for #<Middleman::Extensions::MinifyJavascript::Rack:0x00007f194be07480> (NameError)
    from /local/p4clients/pkgbuild-xN2v7/workspace/env/WfmGroceryOrdering-1.0/test-runtime/ruby2.3.x/lib/ruby/gems/2.3.0/gems/middleman-core-3.3.12/lib/middleman-more/extensions/minify_javascript.rb:94:in `minify'
    from /local/p4clients/pkgbuild-xN2v7/workspace/env/WfmGroceryOrdering-1.0/test-runtime/ruby2.3.x/lib/ruby/gems/2.3.0/gems/middleman-core-3.3.12/lib/middleman-more/extensions/minify_javascript.rb:57:in `
```

Need add `path` parameter to the minify method or be removed so that failure to minify does not break the client
 
## Additional information

- Ruby version: 23x
- Middleman version: 3.3.x 
- OS version:

**Comment by desokroshan** [comment]
https://github.com/middleman/middleman/pull/2549

**Comment by markets** [comment]
Hey @desokroshan since the pull request #2549 has been merged, do you think you can close this issue? Thanks!

**Comment by markets** [comment]
@tdreyno we can close this one too!

**Comment by markets** [comment]
hey @tdreyno 👋🏼 This issue can be closed!
