### ISSUE TITLE
CI fails only with Ruby 3.0 on 4.x

### ISSUE THREAD

**Issue by tnir** [middleman/middleman#2555]
## Expected behavior and actual behavior

No errors are expected, but we are having errors as follow in `cd middleman-core; bundle exec rake test`:
```
An error occurred while loading ./spec/middleman-core/core_extensions/data_spec.rb.
Failure/Error: SimpleCov.start
RuntimeError:
  coverage measurement is already setup
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/ruby -I/home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/rspec-core-3.10.1/lib:/home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/rspec-support-3.10.2/lib /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*/\*_spec.rb --color --format documentation failed
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ./spec/middleman-core/core_extensions/data_spec.rb:1:in `require'
# ./spec/middleman-core/core_extensions/data_spec.rb:1:in `<top (required)>'
An error occurred while loading ./spec/middleman-core/dns_resolver_spec.rb.
Failure/Error: SimpleCov.start
RuntimeError:
  coverage measurement is already setup
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:[48](https://github.com/middleman/middleman/runs/7333435349?check_suite_focus=true#step:7:49):in `start'
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ./spec/middleman-core/dns_resolver_spec.rb:1:in `require'
# ./spec/middleman-core/dns_resolver_spec.rb:1:in `<top (required)>'
An error occurred while loading ./spec/middleman-core/preview_server/server_hostname_spec.rb.
Failure/Error: SimpleCov.start
RuntimeError:
  coverage measurement is already setup
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ./spec/middleman-core/preview_server/server_hostname_spec.rb:1:in `require'
# ./spec/middleman-core/preview_server/server_hostname_spec.rb:1:in `<top (required)>'
An error occurred while loading ./spec/middleman-core/preview_server/server_ip_address_spec.rb.
Failure/Error: SimpleCov.start
RuntimeError:
  coverage measurement is already setup
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ./spec/middleman-core/preview_server/server_ip_address_spec.rb:1:in `require'
# ./spec/middleman-core/preview_server/server_ip_address_spec.rb:1:in `<top (required)>'
An error occurred while loading ./spec/middleman-core/util_spec.rb.
Failure/Error: SimpleCov.start
RuntimeError:
  coverage measurement is already setup
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
# /home/runner/work/middleman/middleman/vendor/bundle/ruby/3.1.0/gems/simplecov-0.12.0/lib/simplecov.rb:48:in `start'
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ./spec/middleman-core/util_spec.rb:1:in `require'
# ./spec/middleman-core/util_spec.rb:1:in `<top (required)>'
Finished in 0.00003 seconds (files took 0.27[57](https://github.com/middleman/middleman/runs/7333435349?check_suite_focus=true#step:7:58)4 seconds to load)
0 examples, 0 failures, 5 errors occurred outside of examples
```

## Steps to reproduce the problem (from a clean middleman installation)

1. Set up Ruby 3.0 (3.0.4 was used)
2. Install `rsync` (apt install rsync)
3. `git clone` this repo
4. `cd middleman-core; bundle exec rake test`

## Additional information

Relates to #2424

**Comment by tnir** [comment]
@markets Thanks. Closing this and improving yet another thing in #2559
