### ISSUE TITLE
YAML Exception ...: Tried to load unspecified class: Date

### ISSUE THREAD

**Issue by richardTowers** [middleman/middleman#2614]
This affects versions of ruby > 3.1

Ruby 3.1 upgraded Psych to the 4.x branch, which changes `Psych.load` to call `Psych.safe_load` instead of `Psych.unsafe_load`. This means it no longer parses dates unless it's provided with `permitted_classes: [Date, ...]`.

The currently released versions of middleman (4.4.3 and 5.0.0-rc1) [call YAML.load](https://github.com/middleman/middleman/blob/v4.4.2/middleman-core/lib/middleman-core/util/data.rb#L123), so the behavour depends on your ruby version.

When I originally raised this issue this looked like it was already fixed in `master`, but the default branch is `main` now and I can't see the fix anymore. (edit: updated since I can't find the fix anymore)

(Note: this isn't a problem if you use formats like YYYY/MM/dd which are parsed as strings - it's only YYYY-MM-dd which YAML thinks is a date)

## Expected behavior and actual behavior

Create a file with a date value in its frontmatter:

```
---
date: 1970-01-01
---
```

And then `middleman build --verbose`

Expected behaviour: No errors, frontmatter is parsed as `{"date"=>#Date<1970-01-01>}`
Actual behaviour:
```
== Running manipulator: front_matter (20)
YAML Exception parsing ...: Tried to load unspecified class: Date
```

## Steps to reproduce the problem (from a clean middleman installation)

```
$ middleman init test
...
$ cd test
$ cat > source/index.html.md
---
date: 1970-01-01
---
# Hello world!
^D
$ middleman build --verbose
...
== Running manipulator: front_matter (20)
YAML Exception parsing .../test/source/index.html.erb: Tried to load unspecified class: Date
...
```

This error is skipped over (just producing a warning), but it means that all of the frontmatter for this page will be ignored (not just the field with a date in).

## Additional information

- Ruby version: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
- Middleman version: 4.4.3
- OS version: Ubuntu 20.04.5 LTS

**Comment by tdreyno** [comment]
Middleman 4.x does not explicitly support Ruby 3.1. I would suggest folks stick on 2.7 until the heat death of the universe.

That said, if that change passes CI @markets, I'm good to merge it

**Comment by markets** [comment]
Ok! I'll send a patch, let's see how it goes in CI

**Comment by benui-dev** [comment]
I am still seeing this error with Middleman 4.2 and Ruby 3.2.2 on windows

```
YAML Exception parsing C:/Projects/GitHub/personalsite3/data/bits.yml: Tried to load unspecified class: Time
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- less (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tilt-2.0.11/lib/tilt/less.rb:2:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tilt-2.0.11/lib/tilt/mapping.rb:243:in `block in lazy_load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tilt-2.0.11/lib/tilt/mapping.rb:241:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tilt-2.0.11/lib/tilt/mapping.rb:241:in `lazy_load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tilt-2.0.11/lib/tilt/mapping.rb:216:in `lookup'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tilt-2.0.11/lib/tilt/mapping.rb:154:in `[]'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tilt-2.0.11/lib/tilt.rb:48:in `[]'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources/source_watcher.rb:338:in `strip_extensions'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources/source_watcher.rb:326:in `record_file_change'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources/source_watcher.rb:265:in `block in update'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources/source_watcher.rb:264:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources/source_watcher.rb:264:in `update'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources/source_watcher.rb:212:in `poll_once!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources.rb:241:in `block in poll_once!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources.rb:241:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources.rb:241:in `reduce'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/sources.rb:241:in `poll_once!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/core_extensions/file_watcher.rb:47:in `before_configuration'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/callback_manager.rb:57:in `execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-core-4.5.1/lib/middleman-core/application.rb:283:in `initialize'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-cli-4.5.1/bin/middleman:49:in `new'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/middleman-cli-4.5.1/bin/middleman:49:in `<top (required)>'
        from C:/Ruby32-x64/bin/middleman:32:in `load'
        from C:/Ruby32-x64/bin/middleman:32:in `<main>'
       ```

**Comment by richardTowers** [comment]
>  Tried to load unspecified class: Time

The [code currently only permits Date and Symbol](https://github.com/alphagov/middleman/blob/main/middleman-core/lib/middleman-core/util/data.rb#L121), not Time. Probably we should add Time to the allowlist.

Alternatively, you could change your YAML frontmatter so it only specifies the date, not the full timestamp, and ruby will parse it as a Date instead of a Time (which is allowed).

**Comment by tdreyno** [comment]
Seems reasonable to add Time to the allowlist

**Comment by markets** [comment]
If I'm not wrong, this was already fixed in https://github.com/middleman/middleman/commit/73b281eac235927b7ecd30422881369f67d9b58f, but probably unreleased?
