### ISSUE TITLE
Middleman on Rails 

### ISSUE THREAD

**Issue by lgs** [middleman/middleman#556]
`I'll post this here, because the forum reset password doesn't seem to work`

Hi, is there a way to integrate Middleman in an existing Rails app ? I just see something really intresting for jekyll called bloggy :

<pre>
   http://www.engineyard.com/products/cloud/features/cli 
   https://github.com/zbruhnke/bloggy
</pre>

Should be great having something similar for Middleman, anyway if you know some other way to integrate smoothly is wellcome.

**Comment by oiojin831** [comment]
I am little confused.
Should I put those code on config.ru?

**Comment by tdreyno** [comment]
For rack, yes. For rails, you can mount `Middleman.server`

**Comment by oiojin831** [comment]
Thanks, but I still don't get it.
I might not understand something about rack app.

So I got it running the rack server, however I think when the middleman app tried to build the website it gave me "middleman-cli"  error like below

```sh
Bundler is using a binstub that was created for a different gem.                                                                                                                                                                                                          
This is deprecated, in future versions you may need to `bundle binstub middleman-cli` to work around a system/bundle conflict.                                                                                                                                            
/home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearance-1.11.0/lib/clearance/authentication.rb:3:in `<module:Authentication>': uninitialized constant Clearance::Authentication::ActiveSupport (NameError)                                               
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearance-1.11.0/lib/clearance/authentication.rb:2:in `<module:Clearance>'                                                                                                                    
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearance-1.11.0/lib/clearance/authentication.rb:1:in `<top (required)>'                                                                                                                      
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearance-1.11.0/lib/clearance/controller.rb:1:in `require'                                                                                                                                   
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearance-1.11.0/lib/clearance/controller.rb:1:in `<top (required)>'                                                                                                                          
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearance-1.11.0/lib/clearance.rb:6:in `require'                                                                                                                                              
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearance-1.11.0/lib/clearance.rb:6:in `<top (required)>'                                                                                                                                     
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'                                                                                                                                         
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'                                                                                                                     
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'                                                                                                                                            
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'                                                                                                                                
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'                                                                                                                                            
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'                                                                                                                                         
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'                                                                                                                                                
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/lib/middleman-core/load_paths.rb:37:in `setup_load_paths'                                                                                                                
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/bin/middleman:10:in `<top (required)>'                                                                                                                                   
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/middleman:23:in `load'                                                                                                                                                                         
        from /home/oiojin831/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/middleman:23:in `<main>'                          
```
Can anyone help me with this?

Thank you

**Comment by tdreyno** [comment]
The binstub warning is fine, usually a different between global ruby and the project rbenv version.

The actual error seems to be in Clearance. Not sure why that library would be starting when running middleman. Might be because Bundler automatically requires everything in `Gemfile`. Maybe add `require: false` to the `gem "clearance"` line

**Comment by oiojin831** [comment]
I think Gemfile in my rails project and middleman are conflicting.
When I tried ```gem "clearance", require: false``` in Middleman's Gemfile, my Rails project can't find clearance. I might be doing something wrong in the first place.

**Comment by tdreyno** [comment]
No, that makes sense. You might file a bug with Clearance, seems like they've either got some module pathing issues or have an undeclared/required dependency on `ActiveSupport` which isn't loaded before they are in a MM context.
