### ISSUE TITLE
Frontmatter is using system default encoding instead of template encoding or even app.encoding

### ISSUE THREAD

**Issue by utensil** [middleman/middleman#589]
Minimal reproduce:

For a haml file

```
--- 
title: 中文
date: 2012/09/08
tags: tech

---

%div
  blah
```

 with its layout file

```
-# coding: utf-8
!!! 5
%html
  %head
    %meta{:charset => "utf-8"}
      / Always force latest IE rendering engine (even in intranet) &amp; Chrome Frame
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
      /[if lt IE 9]
        %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js", :type => "text/javascript"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= current_page.data.title 
    = yield_content :head
  %body
    #container
      #main{:role => "main"}
        %div.content
          = yield
```

 will encounter

```
Encoding::CompatibilityError at /tech_blog/2012/09/08/encoding-test.html
incompatible character encodings: UTF-8 and GBK
```

I looked around, and it seems that when middleman render the template, it's using the encoding of the haml file(the `-# coding: utf-8`) or the encoding set in config.rb(the `set :encoding,    "utf-8"`), and when middleman parse the frontmatter, it's using the system default encoding(in my case, GBK), so when meta data is concating into template(`%title= current_page.data.title`), encodings got incompatible.

Specifically, in C:\Ruby192\lib\ruby\gems\1.9.1\gems\middleman-core-3.0.2\lib\middleman-core\core_extensions\front_matter.rb:

``` ruby
      # Get the frontmatter and plain content from a file
      # @param [String] path
      # @return [Array<Thor::CoreExt::HashWithIndifferentAccess, String>]
      def frontmatter_and_content(path)
        full_path = File.expand_path(path, @app.source_dir)

        content = File.read(full_path)
        data = {}

        begin
          if content =~ /\A.*coding:/
            lines = content.split(/\n/)
            lines.shift
            content = lines.join("\n")
          end

          if result = parse_yaml_front_matter(content)
            data, content = result
          elsif result = parse_json_front_matter(content)
            data, content = result
          end
        rescue => e
          # Probably a binary file, move on
        end
```

The `content` in `content = File.read(full_path)` is GBK, so when it's parsed by `parse_yaml_front_matter(content)`, strings in metadata are GBK. That's what's causing the problem.

Other than simply `bundle exec middleman server`, I also tried `LANG=zh_CN.utf-8 bundle exec middleman server` under MinGW/MSYS, but gem `execjs` can't work in that case(due to trying to split PATH(which is GBK) as utf-8), I have to stick to not setting `Encoding.default_external` or `Encoding.default_internal`.

**Comment by lwr** [comment]
It is too bad the above ending is not happy enough.

Problem still exists while loading YAML files in data


```ruby
application.rb
---------------------------
281      # Before config is parsed. Mostly used for extensions.
282      execute_callbacks(:before_configuration)
... ...
298      if Object.const_defined?(:Encoding)
299        Encoding.default_external = config[:encoding]
300      end
```

error stacktrace
```
/usr/local/rvm/gems/ruby-2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/util/data.rb:60:in `match': invalid byte sequence in GB18030 (ArgumentError)
        from /usr/local/rvm/gems/ruby-2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/util/data.rb:60:in `parse'
... ...
        from /usr/local/rvm/gems/ruby-2.1.8/gems/middleman-core-4.1.10/lib/middleman-core/application.rb:282:in `initialize'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/middleman-cli-4.1.10/bin/middleman:51:in `new'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/middleman-cli-4.1.10/bin/middleman:51:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.8/bin/middleman:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.8/bin/middleman:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `<main>'
```

Can I reopen this issue or make a new?
